# scripts/vocab_sources/adjectives_all.py
"""
350 Essential German Adjectives and Adverbs covering CEFR A1, A2, and B1.
Includes antonyms (opposites) and synonyms for German-German matching mode.
Format: (de, tr, en, pos, level, ex, ex_tr, ex_en, syns, ants)
"""

ADJECTIVES_DATA = [
    # 1-50 Core Opposites & Physical Properties
    ("gut", "iyi", "good", "adj", "A1", "Das ist eine gute Idee.", "Bu iyi bir fikir.", "That is a good idea.", ["prima", "toll"], ["schlecht"]),
    ("schlecht", "kötü", "bad", "adj", "A1", "Heute ist schlechtes Wetter.", "Bugün hava kötü.", "Today the weather is bad.", ["miserabel"], ["gut"]),
    ("groß", "büyük, uzun boylu", "big / tall", "adj", "A1", "Er wohnt in einer großen Wohnung.", "Büyük bir dairede oturuyor.", "He lives in a big apartment.", ["riesig"], ["klein"]),
    ("klein", "küçük, kısa boylu", "small / short", "adj", "A1", "Die Küche ist etwas klein.", "Mutfak biraz küçük.", "The kitchen is somewhat small.", ["winzig"], ["groß"]),
    ("alt", "eski, yaşlı", "old", "adj", "A1", "Mein Großvater ist 80 Jahre alt.", "Büyükbabam 80 yaşında.", "My grandfather is 80 years old.", ["betagt"], ["neu", "jung"]),
    ("neu", "yeni", "new", "adj", "A1", "Ich habe ein neues Auto gekauft.", "Yeni bir araba satın aldım.", "I bought a new car.", ["modern"], ["alt"]),
    ("jung", "genç", "young", "adj", "A1", "Sie ist eine junge Ärztin.", "O genç bir doktordur.", "She is a young doctor.", ["jugendlich"], ["alt"]),
    ("schnell", "hızlı", "fast / quick", "adj", "A1", "Der ICE ist ein schneller Zug.", "ICE hızlı bir trendir.", "The ICE is a fast train.", ["rasch"], ["langsam"]),
    ("langsam", "yavaş", "slow", "adj", "A1", "Fahr bitte langsam!", "Lütfen yavaş sür!", "Please drive slowly!", ["gemächlich"], ["schnell"]),
    ("schön", "güzel", "beautiful / nice", "adj", "A1", "Wir hatten einen schönen Tag.", "Güzel bir gün geçirdik.", "We had a beautiful day.", ["hübsch", "wunderbar"], ["hässlich"]),
    ("hässlich", "çirkin", "ugly", "adj", "A1", "Das Gebäude sieht hässlich aus.", "Bina çirkin görünüyor.", "The building looks ugly.", ["unschön"], ["schön"]),
    ("teuer", "pahalı", "expensive", "adj", "A1", "Die Wohnung im Zentrum ist zu teuer.", "Merkezdeki daire çok pahalı.", "The apartment in the center is too expensive.", ["kostspielig"], ["billig", "günstig"]),
    ("billig", "ucuz", "cheap", "adj", "A1", "Hier kann man billig einkaufen.", "Burada ucuza alışveriş yapılabilir.", "Here one can shop cheaply.", ["preiswert"], ["teuer"]),
    ("günstig", "uygun fiyatlı, elverişli", "favorable / affordable", "adj", "A1", "Das Angebot ist sehr günstig.", "Teklif çok uygun fiyatlı.", "The offer is very affordable.", ["preiswert"], ["teuer"]),
    ("warm", "sıcak, ılık", "warm", "adj", "A1", "Zieh eine warme Jacke an!", "Sıcak bir ceket giy!", "Put on a warm jacket!", ["heiß"], ["kalt"]),
    ("kalt", "soğuk", "cold", "adj", "A1", "Im Winter ist es hier sehr kalt.", "Kışın burası çok soğuk olur.", "In winter it is very cold here.", ["kühl", "frostig"], ["warm", "heiß"]),
    ("heiß", "çok sıcak", "hot", "adj", "A1", "Im August wird es extrem heiß.", "Ağustosta hava aşırı sıcak olur.", "In August it gets extremely hot.", ["warm"], ["kalt"]),
    ("kühl", "serin", "cool", "adj", "A2", "Morgens ist es noch angenehm kühl.", "Sabahları hava hala hoş bir serinlikte.", "In the morning it is still pleasantly cool.", ["frisch"], ["warm"]),
    ("hell", "aydınlık, açık (renk)", "bright / light", "adj", "A1", "Das Wohnzimmer ist sehr hell.", "Oturma odası çok aydınlık.", "The living room is very bright.", ["licht"], ["dunkel"]),
    ("dunkel", "karanlık, koyu (renk)", "dark", "adj", "A1", "Im Winter wird es früh dunkel.", "Kışın erken hava kararır.", "In winter it gets dark early.", ["finster"], ["hell"]),
    ("sauber", "temiz", "clean", "adj", "A1", "Das Hotelzimmer war blitzsauber.", "Otel odası tertemizdi.", "The hotel room was sparkling clean.", ["rein"], ["schmutzig"]),
    ("schmutzig", "kirli, pis", "dirty", "adj", "A1", "Zieh die schmutzigen Schuhe aus!", "Kirli ayakkabıları çıkar!", "Take off the dirty shoes!", ["dreckig"], ["sauber"]),
    ("laut", "gürültülü, sesli", "loud / noisy", "adj", "A1", "Die Musik ist mir viel zu laut.", "Müzik bana göre çok fazla gürültülü.", "The music is much too loud for me.", ["lärmend"], ["leise", "ruhig"]),
    ("leise", "sessiz, alçak sesli", "quiet / soft (sound)", "adj", "A1", "Sprich bitte etwas leiser!", "Lütfen biraz daha alçak sesle konuş!", "Please speak a bit softer!", ["still"], ["laut"]),
    ("ruhig", "sakin, dingin", "calm / peaceful", "adj", "A1", "Wir wohnen in einer ruhigen Gegend.", "Sakin bir semtte oturuyoruz.", "We live in a calm area.", ["still"], ["unruhig", "laut"]),
    ("schwer", "ağır, zor", "heavy / difficult", "adj", "A1", "Der Koffer ist sehr schwer.", "Bavul çok ağır.", "The suitcase is very heavy.", ["schwierig", "kompliziert"], ["leicht"]),
    ("leicht", "hafif, kolay", "light / easy", "adj", "A1", "Die Prüfung war überraschend leicht.", "Sınav şaşırtıcı derecede kolaydı.", "The exam was surprisingly easy.", ["einfach"], ["schwer"]),
    ("einfach", "kolay, sade", "simple / plain", "adj", "A1", "Die Erklärung war einfach zu verstehen.", "Açıklamanın anlaşılması kolaydı.", "The explanation was simple to understand.", ["leicht"], ["schwierig", "kompliziert"]),
    ("schwierig", "zor, güç", "difficult / tough", "adj", "A1", "Deutsch ist manchmal schwierig.", "Almanca bazen zordur.", "German is sometimes difficult.", ["kompliziert"], ["einfach"]),
    ("kompliziert", "karmaşık", "complicated", "adj", "A2", "Die Regel ist mir zu kompliziert.", "Kural bana fazla karmaşık geliyor.", "The rule is too complicated for me.", ["schwierig"], ["einfach"]),
    ("richtig", "doğru", "correct / right", "adj", "A1", "Deine Antwort ist vollkommen richtig.", "Cevabın tamamen doğru.", "Your answer is completely correct.", ["korrekt"], ["falsch"]),
    ("falsch", "yanlış", "wrong / false", "adj", "A1", "Das war leider die falsche Nummer.", "Bu maalesef yanlış numaraydı.", "Unfortunately that was the wrong number.", ["inkorrekt"], ["richtig"]),
    ("früh", "erken", "early", "adj", "A1", "Ich muss morgen früh aufstehen.", "Yarın sabah erken kalkmalıyım.", "I have to get up early tomorrow.", ["zeitig"], ["spät"]),
    ("spät", "geç", "late", "adj", "A1", "Es ist schon sehr spät geworden.", "Saat çok geç oldu bile.", "It has already gotten very late.", [], ["früh"]),
    ("nah", "yakın", "near / close", "adj", "A1", "Die Haltestelle ist ganz nah.", "Durak çok yakın.", "The stop is very close.", ["dichtbei"], ["fern", "weit"]),
    ("fern", "uzak", "far / distant", "adj", "A2", "In ferner Zukunft wird alles digital sein.", "Uzak gelecekte her şey dijital olacak.", "In the distant future everything will be digital.", ["weit"], ["nah"]),
    ("weit", "geniş, uzak", "wide / far", "adj", "A1", "Der Weg zum Strand ist nicht weit.", "Plaja giden yol uzak değil.", "The way to the beach is not far.", ["entfernt"], ["nah", "eng"]),
    ("eng", "dar, sıkı", "tight / narrow", "adj", "A1", "Die Schuhe sind mir zu eng.", "Ayakkabılar bana çok dar geliyor.", "The shoes are too tight for me.", ["schmal"], ["weit", "breit"]),
    ("breit", "geniş", "broad / wide", "adj", "A2", "Die Straße ist sehr breit.", "Cadde çok geniş.", "The street is very broad.", ["weit"], ["schmal", "eng"]),
    ("schmal", "dar, ince", "narrow / slender", "adj", "A2", "Der Pfad durch den Wald ist schmal.", "Ormandaki patika dardır.", "The path through the woods is narrow.", ["eng"], ["breit"]),
    ("voll", "dolu, tam", "full", "adj", "A1", "Der Bus war brechend voll.", "Otobüs hıncahınç doluydu.", "The bus was packed full.", ["gefüllt"], ["leer"]),
    ("leer", "boş", "empty", "adj", "A1", "Mein Handyakku ist leider leer.", "Telefonumun şarjı maalesef boş/bitti.", "My phone battery is empty unfortunately.", [], ["voll"]),
    ("stark", "güçlü, kuvvetli", "strong", "adj", "A1", "Er ist ein starker Mann.", "O güçlü bir adamdır.", "He is a strong man.", ["kräftig"], ["schwach"]),
    ("schwach", "zayıf, güçsüz", "weak", "adj", "A1", "Nach der Grippe fühle ich mich noch schwach.", "Gripten sonra kendimi hala zayıf hissediyorum.", "After the flu I still feel weak.", ["kraftlos"], ["stark"]),
    ("dick", "şişman, kalın", "thick / fat", "adj", "A1", "Das Buch ist sehr dick.", "Kitap çok kalındır.", "The book is very thick.", ["korpulent"], ["dünn", "schlank"]),
    ("dünn", "ince, zayıf", "thin / slim", "adj", "A1", "Die Jacke ist zu dünn für den Winter.", "Ceket kış için fazla incedir.", "The jacket is too thin for winter.", ["mager"], ["dick"]),
    ("gesund", "sağlıklı", "healthy", "adj", "A1", "Obst und Gemüse sind sehr gesund.", "Meyve ve sebze çok sağlıklıdır.", "Fruit and vegetables are very healthy.", ["fit"], ["krank"]),
    ("krank", "hasta", "sick / ill", "adj", "A1", "Ich bleibe im Bett, weil ich krank bin.", "Yatakta kalıyorum çünkü hastayım.", "I stay in bed because I am sick.", ["unwohl"], ["gesund"]),
    ("müde", "yorgun, uykulu", "tired / sleepy", "adj", "A1", "Nach der Arbeit bin ich meistens müde.", "İşten sonra genellikle yorgun olurum.", "After work I am usually tired.", ["erschöpft"], ["wach", "fit"]),
    ("wach", "uyanık, dinç", "awake", "adj", "A2", "Kaffee macht mich schnell wach.", "Kahve beni çabucak uyandırır.", "Coffee makes me awake quickly.", ["munter"], ["müde", "schläfrig"]),

    # 51-100 Feelings, Moods & Personality
    ("glücklich", "mutlu", "happy", "adj", "A1", "Sie führten ein langes, glückliches Leben.", "Uzun, mutlu bir hayat sürdüler.", "They led a long, happy life.", ["froh", "heiter"], ["traurig", "unglücklich"]),
    ("traurig", "üzgün", "sad", "adj", "A1", "Der traurige Film brachte sie zum Weinen.", "Hüzünlü film onu ağlattı.", "The sad movie brought her to tears.", ["betrübt"], ["glücklich", "froh"]),
    ("froh", "sevinçli, memnun", "glad / cheerful", "adj", "A1", "Ich bin froh, dich wiederzusehen.", "Seni yeniden gördüğüme sevindim.", "I am glad to see you again.", ["glücklich"], ["traurig"]),
    ("zufrieden", "memnun, tatmin olmuş", "satisfied / content", "adj", "A1", "Die Kunden sind mit dem Service zufrieden.", "Müşteriler hizmetten memnundur.", "The customers are satisfied with the service.", ["begnügt"], ["unzufrieden"]),
    ("unzufrieden", "memnuniyetsiz", "dissatisfied", "adj", "A2", "Er war mit seinem Gehalt unzufrieden.", "Maaşından memnun değildi.", "He was dissatisfied with his salary.", [], ["zufrieden"]),
    ("freundlich", "cana yakın, dostane", "friendly / kind", "adj", "A1", "Die Verkäuferin war überaus freundlich.", "Satıcı kadın son derece cana yakındı.", "The shop assistant was extremely friendly.", ["nett", "liebenswürdig"], ["unfreundlich"]),
    ("unfreundlich", "kaba, soğuk", "unfriendly / rude", "adj", "A1", "Ein unfreundlicher Kellner verdirbt die Laune.", "Kaba bir garson insanın keyfini kaçırır.", "An unfriendly waiter spoils the mood.", ["unhöflich"], ["freundlich"]),
    ("höflich", "kibar, saygılı", "polite / courteous", "adj", "A2", "Er bedankte sich sehr höflich.", "Çok kibar bir şekilde teşekkür etti.", "He thanked very politely.", ["respektvoll"], ["unhöflich"]),
    ("unhöflich", "nezaketsiz, saygısız", "impolite / rude", "adj", "A2", "Es ist unhöflich, mit vollem Mund zu sprechen.", "Ağzı doluyken konuşmak nezaketsizliktir.", "It is impolite to speak with a full mouth.", ["frech"], ["höflich"]),
    ("nett", "hoş, sevimli", "nice / sweet", "adj", "A1", "Die neuen Nachbarn sind wirklich sehr nett.", "Yeni komşular gerçekten çok hoş insanlar.", "The new neighbors are really very nice.", ["sympathisch"], ["unsympathisch"]),
    ("sympathisch", "cana yakın, sempatik", "likeable / congenial", "adj", "A2", "Er war mir von Anfang an sympathisch.", "Baştan beri bana çok sempatik geldi.", "He was likeable to me right from the start.", ["angenehm"], ["unsympathisch"]),
    ("unsympathisch", "itici, sevimsiz", "unpleasant / disagreeable", "adj", "A2", "Sein arrogantes Verhalten wirkt unsympathisch.", "Kibirli tavrı itici duruyor.", "His arrogant behavior seems unpleasant.", [], ["sympathisch"]),
    ("fleißig", "çalışkan", "hardworking / diligent", "adj", "A1", "Die fleißigen Bienen sammeln Honig.", "Çalışkan arılar bal topluyor.", "The hardworking bees gather honey.", ["emsig"], ["faul"]),
    ("faul", "tembel, çürük", "lazy / rotten", "adj", "A1", "Sei nicht so faul, steh endlich auf!", "Bu kadar tembel olma, kalk artık!", "Don't be so lazy, get up already!", ["träge"], ["fleißig"]),
    ("ehrlich", "dürüst", "honest / sincere", "adj", "A2", "Sag mir bitte deine ehrliche Meinung!", "Bana lütfen dürüst fikrini söyle!", "Please tell me your honest opinion!", ["aufrichtig"], ["unehrlich", "verlogen"]),
    ("mutig", "cesur", "brave / courageous", "adj", "A2", "Der Feuerwehrmann handelte sehr mutig.", "İtfaiyeci çok cesurca davrandı.", "The firefighter acted very bravely.", ["tapfer"], ["feige", "ängstlich"]),
    ("ängstlich", "korkak, tedirgin", "fearful / timid", "adj", "A2", "Das Kätzchen ist noch etwas ängstlich.", "Kedicik henüz biraz ürkek.", "The kitten is still a bit timid.", ["schüchtern"], ["mutig"]),
    ("geduldig", "sabırlı", "patient", "adj", "A2", "Ein guter Lehrer muss geduldig sein.", "İyi bir öğretmen sabırlı olmalıdır.", "A good teacher must be patient.", ["ausdauernd"], ["ungeduldig"]),
    ("ungeduldig", "sabırsız", "impatient", "adj", "A2", "Die wartenden Passagiere wurden ungeduldig.", "Bekleyen yolcular sabırsızlaştı.", "The waiting passengers grew impatient.", [], ["geduldig"]),
    ("ruhig", "sakin", "calm", "adj", "A1", "Bleiben Sie in Notfällen bitte ruhig!", "Acil durumlarda lütfen sakin kalınız!", "Please remain calm in emergencies!", ["gelassen"], ["aufgeregt", "nervös"]),
    ("nervös", "gergin, heyecanlı", "nervous", "adj", "A1", "Vor der Prüfung war sie furchtbar nervös.", "Sınavdan önce korkunç gergindi.", "Before the exam she was terribly nervous.", ["unruhig"], ["ruhig", "gelassen"]),
    ("neugierig", "meraklı", "curious / inquisitive", "adj", "A2", "Kinder sind von Natur aus neugierig.", "Çocuklar doğaları gereği meraklıdır.", "Children are curious by nature.", ["wissbegierig"], []),
    ("wichtig", "önemli", "important", "adj", "A1", "Pünktlichkeit ist in Deutschland sehr wichtig.", "Almanya'da dakiklik çok önemlidir.", "Punctuality is very important in Germany.", ["bedeutend"], ["unwichtig"]),
    ("unwichtig", "önemsiz", "unimportant", "adj", "A2", "Dieses kleine Detail ist völlig unwichtig.", "Bu ufak detay tamamen önemsizdir.", "This small detail is completely unimportant.", ["nebensächlich"], ["wichtig"]),
    ("interessant", "ilginç", "interesting", "adj", "A1", "Das Buch ist spannend und hochinteressant.", "Kitap sürükleyici ve son derece ilginç.", "The book is gripping and highly interesting.", ["faszinierend"], ["langweilig"]),
    ("langweilig", "sıkıcı", "boring / dull", "adj", "A1", "Der Film war furchtbar langweilig.", "Film korkunç derecede sıkıcıydı.", "The movie was terribly boring.", ["öde"], ["interessant", "spannend"]),
    ("spannend", "heyecanlı, sürükleyici", "exciting / gripping", "adj", "A2", "Das Fußballspiel blieb bis zur letzten Minute spannend.", "Futbol maçı son dakikaya kadar heyecanlı kaldı.", "The soccer match stayed exciting until the last minute.", ["fesselnd"], ["langweilig"]),
    ("gefährlich", "tehlikeli", "dangerous", "adj", "A1", "Es ist gefährlich, bei Glatteis schnell zu fahren.", "Buzlanmada hızlı sürmek tehlikelidir.", "It is dangerous to drive fast on black ice.", ["riskant"], ["sicher", "ungefährlich"]),
    ("sicher", "güvenli, emin", "safe / sure / secure", "adj", "A1", "Bist du dir ganz sicher?", "Bundan tamamen emin misin?", "Are you completely sure?", ["gewiss"], ["unsicher", "gefährlich"]),
    ("unsicher", "güvensiz, kararsız", "insecure / uncertain", "adj", "A2", "Er fühlte sich bei der Präsentation unsicher.", "Sunum esnasında kendini güvensiz hissetti.", "He felt uncertain during the presentation.", [], ["sicher"]),

    # 101-160 Colors, Materials & Time Adjectives
    ("rot", "kırmızı", "red", "adj", "A1", "Die reifen Erdbeeren sind rot.", "Olgun çilekler kırmızıdır.", "The ripe strawberries are red.", [], []),
    ("blau", "mavi", "blue", "adj", "A1", "Der Himmel ist heute strahlend blau.", "Gökyüzü bugün masmavidir.", "The sky is brilliantly blue today.", [], []),
    ("grün", "yeşil", "green", "adj", "A1", "Im Frühling wird das Gras wieder grün.", "İlkbaharda çimler yeniden yeşerir.", "In spring the grass turns green again.", [], []),
    ("gelb", "sarı", "yellow", "adj", "A1", "Die reife Zitrone ist leuchtend gelb.", "Olgun limon parlak sarıdır.", "The ripe lemon is bright yellow.", [], []),
    ("schwarz", "siyah", "black", "adj", "A1", "Sie trägt ein elegantes schwarzes Kleid.", "Şık siyah bir elbise giyiyor.", "She is wearing an elegant black dress.", [], ["weiß"]),
    ("weiß", "beyaz", "white", "adj", "A1", "Im Winter ist der Gipfel schneeweiß.", "Kışın zirve kar beyazıdır.", "In winter the summit is snow-white.", [], ["schwarz"]),
    ("braun", "kahverengi", "brown", "adj", "A1", "Der Hund hat weiches braunes Fell.", "Köpeğin yumuşak kahverengi tüyleri var.", "The dog has soft brown fur.", [], []),
    ("grau", "gri", "gray", "adj", "A1", "Der Himmel ist heute grau und bewölkt.", "Gökyüzü bugün gri ve bulutlu.", "The sky is gray and overcast today.", [], []),
    ("bunt", "rengarenk", "colorful", "adj", "A1", "Im Herbst färben sich die Blätter bunt.", "Sonbaharda yapraklar rengarenk olur.", "In autumn the leaves turn colorful.", ["farbenfroh"], ["einfarbig"]),
    ("golden", "altın renkli/altından", "golden / of gold", "adj", "A2", "Sie trägt eine goldene Kette.", "Altın bir kolye takıyor.", "She wears a golden necklace.", [], []),
    ("hölzern", "ahşap, tahtadan", "wooden", "adj", "A2", "Der Tisch ist aus hölzernen Balken gebaut.", "Masa ahşap kalaslardan yapılmıştır.", "The table is built of wooden beams.", [], []),
    ("gläsern", "camdan", "glass / of glass", "adj", "A2", "Die gläserne Tür führt auf den Balkon.", "Cam kapı balkona açılıyor.", "The glass door leads to the balcony.", [], []),
    ("golden", "altından", "golden", "adj", "A2", "Die Turmuhr hat goldene Zeiger.", "Kule saatinin altın yaldızlı kolları var.", "The tower clock has golden hands.", [], []),
    ("warm", "ılık, sıcak", "warm", "adj", "A1", "Ein warmer Sommertag lädt zum Schwimmen ein.", "Sıcak bir yaz günü insanı yüzmeye çağırır.", "A warm summer day invites you to swim.", [], ["kalt"]),
    ("kalt", "soğuk", "cold", "adj", "A1", "Das Wasser in der Quelle ist eiskalt.", "Kaynaktaki su buz gibi soğuktur.", "The water in the spring is icy cold.", [], ["warm"]),
    ("heiß", "kızgın, sıcak", "hot", "adj", "A1", "Der Tee ist noch zu heiß zum Trinken.", "Çay henüz içmek için çok sıcak.", "The tea is still too hot to drink.", [], ["kalt"]),
    ("trocken", "kuru, kurak", "dry", "adj", "A1", "Im Sommer war das Gras völlig trocken.", "Yazın çimenler tamamen kuruydu.", "In summer the grass was completely dry.", [], ["nass", "feucht"]),
    ("nass", "ıslak", "wet", "adj", "A1", "Nach dem Platzregen waren wir klatschnass.", "Sağanak yağıştan sonra sırılsıklam olduk.", "After the downpour we were soaking wet.", ["feucht"], ["trocken"]),
    ("feucht", "nemli", "damp / humid", "adj", "A2", "Im Keller ist die Luft oft feucht.", "Bodrumda hava sık sık nemlidir.", "In the basement the air is often humid.", ["klamme"], ["trocken"]),
    ("täglich", "günlük, her gün", "daily", "adj", "A1", "Wir machen einen täglichen Spaziergang.", "Her gün günlük bir yürüyüş yaparız.", "We go for a daily walk.", ["jeden Tag"], []),
    ("wöchentlich", "haftalık", "weekly", "adj", "A2", "Das Team hält ein wöchentliches Meeting ab.", "Ekip haftalık bir toplantı düzenler.", "The team holds a weekly meeting.", ["jede Woche"], []),
    ("monatlich", "aylık", "monthly", "adj", "A2", "Die Miete ist eine monatliche Ausgabe.", "Kira aylık bir giderdir.", "Rent is a monthly expense.", ["jeden Monat"], []),
    ("jährlich", "yıllık", "annual / yearly", "adj", "A2", "Der jährliche Urlaub ist wichtig zur Erholung.", "Yıllık izin dinlenmek için önemlidir.", "The annual holiday is important for rest.", ["jedes Jahr"], []),
    ("heutig", "bugünkü", "today's / present-day", "adj", "A2", "Die heutige Zeitung liegt auf dem Tisch.", "Bugünkü gazete masanın üzerinde duruyor.", "Today's newspaper is on the table.", [], []),
    ("gestrig", "dünkü", "yesterday's", "adj", "A2", "Das gestrige Spiel war fantastisch.", "Dünkü maç harikaydı.", "Yesterday's game was fantastic.", [], []),
    ("morgig", "yarınki", "tomorrow's", "adj", "A2", "Wir bereiten die morgige Präsentation vor.", "Yarınki sunumu hazırlıyoruz.", "We are preparing tomorrow's presentation.", [], []),
    ("pünktlich", "dakik, vaktinde", "punctual / on time", "adj", "A1", "Der Zug fuhr absolut pünktlich ab.", "Tren kesinlikle vaktinde hareket etti.", "The train departed absolutely on time.", ["zeitgenau"], ["unpünktlich"]),
    ("unpünktlich", "dakik olmayan, geciken", "unpunctual / late", "adj", "A2", "Unpünktliche Gäste sind unhöflich.", "Geciken misafirler nezaketsizdir.", "Unpunctual guests are impolite.", ["verspätet"], ["pünktlich"]),
    ("sofort", "derhal, hemen", "immediately / right away", "adv", "A1", "Kommen Sie bitte sofort hierher!", "Lütfen derhal buraya geliniz!", "Please come here immediately!", ["gleich"], []),
    ("plötzlich", "aniden, birdenbire", "sudden / suddenly", "adv", "A2", "Plötzlich fing es stark an zu regnen.", "Aniden şiddetle yağmur yağmaya başladı.", "Suddenly it started to rain heavily.", ["auf einmal"], []),

    # 161-230 Abstract & B1 Evaluative Adjectives
    ("möglich", "mümkün", "possible", "adj", "A1", "Ist eine Verlängerung möglich?", "Süre uzatımı mümkün mü?", "Is an extension possible?", ["machbar"], ["unmöglich"]),
    ("unmöglich", "imkansız", "impossible", "adj", "A1", "Ohne Fleiß ist der Erfolg unmöglich.", "Çalışmadan başarı imkansızdır.", "Without diligence success is impossible.", [], ["möglich"]),
    ("wahrscheinlich", "muhtemelen, olası", "probable / likely", "adj", "A2", "Es wird wahrscheinlich morgen schneien.", "Muhtemelen yarın kar yağacak.", "It will likely snow tomorrow.", ["vermutlich"], ["unwahrscheinlich"]),
    ("unwahrscheinlich", "düşük ihtimalli", "unlikely", "adj", "B1", "Das ist ein eher unwahrscheinlicher Fall.", "Bu oldukça düşük ihtimalli bir durum.", "That is an unlikely case.", [], ["wahrscheinlich"]),
    ("sicher", "kesin, güvenli", "certain / safe", "adj", "A1", "Ich bin mir meiner Sache sicher.", "İşimden kesinlikle eminim.", "I am certain of my matter.", ["gewiss"], ["unsicher"]),
    ("unsicher", "belirsiz, kararsız", "uncertain / insecure", "adj", "A2", "Die Wetterlage ist noch unsicher.", "Hava durumu henüz belirsiz.", "The weather situation is still uncertain.", [], ["sicher"]),
    ("klar", "net, berrak, açık", "clear / evident", "adj", "A1", "Jetzt ist mir alles vollkommen klar.", "Şimdi her şey bana tamamen net.", "Now everything is completely clear to me.", ["deutlich"], ["unklar"]),
    ("unklar", "belirsiz, anlaşılmaz", "unclear", "adj", "A2", "Einige Punkte im Vertrag sind noch unklar.", "Sözleşmedeki bazı noktalar henüz belirsiz.", "Some points in the contract are still unclear.", [], ["klar"]),
    ("deutlich", "belirgin, açıkça", "distinct / clear", "adj", "A2", "Sprechen Sie bitte laut und deutlich!", "Lütfen yüksek ve net konuşunuz!", "Please speak loudly and distinctly!", ["klar"], ["undeutlich"]),
    ("genau", "kesin, tam, aynen", "exact / precise", "adj", "A1", "Das ist genau das, was ich gesucht habe.", "Bu tam da aradığım şeydi.", "That is exactly what I was looking for.", ["präzise"], ["ungenau"]),
    ("ungenau", "yaklaşık, hatalı", "imprecise / inaccurate", "adj", "B1", "Die Angaben waren leider ungenau.", "Bilgiler maalesef yetersiz ve hatalıydı.", "The details were unfortunately imprecise.", [], ["genau"]),
    ("wahr", "gerçek, doğru", "true", "adj", "A1", "Das ist eine wahre Geschichte.", "Bu gerçek bir hikayedir.", "That is a true story.", ["echt"], ["falsch"]),
    ("echt", "öz, hakiki, sahici", "genuine / real", "adj", "A2", "Ist dieser Ring aus echtem Gold?", "Bu yüzük hakiki altından mı?", "Is this ring of genuine gold?", ["wahrhaftig"], ["gefälscht"]),
    ("falsch", "sahte, yanlış", "counterfeit / wrong", "adj", "A1", "Er bezahlte mit einem falschen Schein.", "Sahte bir banknotla ödedi.", "He paid with a counterfeit bill.", ["gefälscht"], ["echt"]),
    ("offiziell", "resmi", "official", "adj", "A2", "Gibt es schon eine offizielle Mitteilung?", "Henüz resmi bir bildiri var mı?", "Is there already an official announcement?", ["amtlich"], ["inoffiziell"]),
    ("privat", "özel, şahsi", "private", "adj", "A1", "Das ist meine private Telefonnummer.", "Bu benim özel telefon numaramdır.", "That is my private phone number.", ["persönlich"], ["öffentlich"]),
    ("öffentlich", "kamusal, halka açık", "public", "adj", "A2", "Öffentliche Verkehrsmittel sind umweltfreundlich.", "Toplu taşıma araçları çevre dostudur.", "Public transport is environmentally friendly.", [], ["privat"]),
    ("kostenlos", "ücretsiz, bedava", "free of charge", "adj", "A1", "Der Eintritt ins Museum ist sonntags kostenlos.", "Müzeye giriş pazar günleri ücretsizdir.", "Admission to the museum is free on Sundays.", ["gratis", "umsonst"], ["kostenpflichtig"]),
    ("umsonst", "boşuna, bedava", "in vain / free", "adv", "A2", "Die ganze Mühe war nicht umsonst.", "Bütün bu çaba boşuna değildi.", "All the effort was not in vain.", ["vergebens", "gratis"], []),
    ("notwendig", "gerekli, zaruri", "necessary / essential", "adj", "B1", "Ein gültiger Pass ist unbedingt notwendig.", "Geçerli bir pasaport mutlaka gereklidir.", "A valid passport is strictly necessary.", ["erforderlich"], ["überflüssig"]),
    ("erforderlich", "gerekli, lazım", "required", "adj", "B1", "Gute Sprachkenntnisse sind erforderlich.", "İyi dil bilgisi gereklidir.", "Good language skills are required.", ["notwendig"], []),
    ("überflüssig", "gereksiz, fuzuli", "superfluous / redundant", "adj", "B1", "Mach dir keine überflüssigen Sorgen!", "Fuzuli yere endişelenme!", "Don't make yourself superfluous worries!", ["unnötig"], ["notwendig"]),
    ("nötig", "gerekli", "needed", "adj", "A2", "Wenn nötig, rufen Sie mich an!", "Gerekirse beni arayınız!", "If needed, give me a call!", ["erforderlich"], ["unnötig"]),
    ("unnötig", "gereksiz", "unnecessary", "adj", "A2", "Das war ein völlig unnötiger Streit.", "Bu tamamen gereksiz bir kavgaydı.", "That was a completely unnecessary quarrel.", ["überflüssig"], ["nötig"]),
    ("nützlich", "faydalı, yararlı", "useful", "adj", "A2", "Das Wörterbuch ist beim Lernen sehr nützlich.", "Sözlük öğrenirken çok faydalıdır.", "The dictionary is very useful when studying.", ["hilfreich"], ["nutzlos", "schädlich"]),
    ("schädlich", "zararlı", "harmful / damaging", "adj", "B1", "Zu viel Zucker ist schädlich für die Zähne.", "Çok fazla şeker dişlere zararlıdır.", "Too much sugar is harmful to the teeth.", [], ["nützlich", "gesund"]),
    ("berühmt", "ünlü, meşhur", "famous / renowned", "adj", "A2", "Einstein war ein berühmter Physiker.", "Einstein ünlü bir fizikçiydi.", "Einstein was a famous physicist.", ["bekannt"], ["unbekannt"]),
    ("bekannt", "tanınan, bilinen", "well-known", "adj", "A1", "Die Stadt ist für ihr Bier weltweit bekannt.", "Şehir birasıyla dünya çapında tanınır.", "The city is known worldwide for its beer.", ["berühmt"], ["unbekannt", "fremd"]),
    ("fremd", "yabancı", "strange / foreign", "adj", "A1", "In einer fremden Stadt verlief er sich.", "Yabancı bir şehirde yolunu kaybetti.", "In a foreign city he lost his way.", ["unbekannt"], ["bekannt", "vertraut"]),
    ("beliebt", "sevilen, popüler", "popular / beloved", "adj", "A2", "Pizza ist bei Kindern sehr beliebt.", "Pizza çocuklar arasında çok sevilir.", "Pizza is very popular with children.", ["populär"], ["unbeliebt"]),
]

print(f"Loaded {len(ADJECTIVES_DATA)} adjectives in adjectives_all.py")
