# scripts/vocab_sources/b2_advanced.py
"""
High-Yield Advanced German Vocabulary for CEFR Level B2.
Designed as a separate, specialized study deck for learners preparing to transition to B2.
Covers:
- Academic & Professional Verbs
- Formal & Abstract Nouns
- Evaluative Adjectives
- Advanced Nomen-Verb-Verbindungen & Discourse Markers
"""

B2_ADVANCED_DATA = [
    # B2 Verben (1-50)
    ("nachvollziehen (vollzieht nach, vollzog nach, hat nachvollzogen)", "anlamak, mantığını kavramak", "to comprehend / reconstruct logically", "verb", "B2", "Ich kann deine Entscheidung vollkommen nachvollziehen.", "Kararının mantığını tamamen anlayabiliyorum.", "I can completely comprehend your decision.", ["verstehen", "begreifen"], []),
    ("hinterfragen (hinterfragt, hinterfragte, hat hinterfragt)", "sorgulamak, eleştirel yaklaşmak", "to question / scrutinize", "verb", "B2", "Wissenschaftler müssen bestehende Thesen kritisch hinterfragen.", "Bilim insanları mevcut tezleri eleştirel şekilde sorgulamalıdır.", "Scientists must critically scrutinize existing theses.", ["bezweifeln"], ["hinnehmen"]),
    ("differenzieren (differenziert, differenzierte, hat differenziert)", "ayrım yapmak, farklılaştırmak", "to differentiate", "verb", "B2", "Man muss in dieser Diskussion genau differenzieren.", "Bu tartışmada tam olarak ayrım yapmak gerekir.", "One must differentiate precisely in this discussion.", ["unterscheiden"], ["pauschalisieren"]),
    ("gewährleisten (gewährleistet, gewährleistete, hat gewährleistet)", "garanti etmek, temin etmek", "to guarantee / ensure", "verb", "B2", "Der Staat muss die innere Sicherheit gewährleisten.", "Devlet iç güvenliği temin etmek zorundadır.", "The state must guarantee internal security.", ["garantieren", "sicherstellen"], []),
    ("bewältigen (bewältigt, bewältigte, hat bewältigt)", "üstesinden gelmek, başarmak", "to overcome / cope with / manage", "verb", "B2", "Gemeinsam können wir diese große Krise bewältigen.", "Bu büyük krizin üstesinden birlikte gelebiliriz.", "Together we can manage this major crisis.", ["meistern", "schaffen"], ["scheitern"]),
    ("beeinträchtigen (beeinträchtigt, beeinträchtigte, hat beeinträchtigt)", "olumsuz etkilemek, zedelemek", "to impair / adversely affect", "verb", "B2", "Lärm kann die Konzentration erheblich beeinträchtigen.", "Gürültü konsantrasyonu önemli ölçüde olumsuz etkileyebilir.", "Noise can significantly impair concentration.", ["schaden", "behindern"], ["fördern"]),
    ("erörtern (erörtert, erörterte, hat erörtert)", "enine boyuna tartışmak, müzakere etmek", "to discuss thoroughly / examine", "verb", "B2", "Wir müssen die verschiedenen Lösungsansätze detailliert erörtern.", "Farklı çözüm yaklaşımlarını ayrıntılı şekilde tartışmalıyız.", "We must thoroughly discuss the various solution approaches.", ["diskutieren", "behandeln"], []),
    ("auslösen (löst aus, löste aus, hat ausgelöst)", "tetiklemek, yol açmak", "to trigger / provoke", "verb", "B2", "Der neue Bericht löste eine hitzige Debatte aus.", "Yeni rapor hararetli bir tartışmayı tetikledi.", "The new report triggered a heated debate.", ["verursachen", "hervorrufen"], []),
    ("hervorgehen (geht hervor, ging hervor, ist hervorgegangen)", "ortaya çıkmak, -den anlaşılmak", "to emerge / result from", "verb", "B2", "Aus der aktuellen Studie geht hervor, dass viele pendeln.", "Güncel çalışmadan birçok kişinin işe gidip geldiği anlaşılıyor.", "From the current study it emerges that many commute.", ["folgen"], []),
    ("unterbinden (unterbindet, unterband, hat unterbunden)", "engellemek, önünü kesmek", "to prevent / stop / suppress", "verb", "B2", "Die Polizei muss illegale Handlungen konsequent unterbinden.", "Polis yasadışı eylemleri kararlılıkla engellemelidir.", "The police must consistently suppress illegal acts.", ["verhindern", "stoppen"], ["zulassen"]),
    ("plädieren (plädiert, plädierte, hat plädiert)", "savunmak, lehinde konuşmak (für)", "to plead / advocate for", "verb", "B2", "Der Minister plädiert für strengere Umweltgesetze.", "Bakan daha sıkı çevre yasaları lehinde görüş bildiriyor.", "The minister advocates for stricter environmental laws.", ["sich aussprechen für"], ["ablehnen"]),
    ("verankern (verankert, verankerte, hat verankert)", "sağlamlaştırmak, yasalaştırmak (in der Verfassung)", "to anchor / establish firmly", "verb", "B2", "Die Grundrechte sind fest im Grundgesetz verankert.", "Temel haklar anayasada sağlam bir şekilde yer almıştır.", "Basic rights are firmly anchored in the constitution.", ["festschreiben"], []),
    ("widerspiegeln (spiegelt wider, spiegelte wider, hat widergespiegelt)", "yansıtmak", "to reflect", "verb", "B2", "Die Umfrage spiegelt die Stimmung der Bevölkerung wider.", "Anket halkın ruh halini yansıtıyor.", "The survey reflects the mood of the population.", ["reflektieren"], []),
    ("beibehalten (behält bei, behielt bei, hat beibehalten)", "sürdürmek, muhafaza etmek", "to maintain / keep up", "verb", "B2", "Wir sollten diese bewährte Methode unbedingt beibehalten.", "Bu kanıtlanmış yöntemi kesinlikle sürdürmeliyiz.", "We should definitely maintain this proven method.", ["fortführen"], ["aufgeben", "ändern"]),
    ("herbeiführen (führt herbei, führte herbei, hat herbeigeführt)", "meydana getirmek, sebep olmak", "to bring about / induce", "verb", "B2", "Die Reform soll positive Veränderungen herbeiführen.", "Reformun olumlu değişiklikler meydana getirmesi amaçlanıyor.", "The reform is intended to bring about positive changes.", ["verursachen"], []),
    ("verhandeln (verhandelt, verhandelte, hat verhandelt)", "müzakere etmek, pazarlık yapmak", "to negotiate", "verb", "B2", "Die Gewerkschaften verhandeln über höhere Gehälter.", "Sendikalar daha yüksek maaşlar için müzakere yürütüyor.", "The trade unions are negotiating for higher salaries.", ["feilschen"], []),
    ("scheitern (scheitert, scheiterte, ist gescheitert)", "başarısızlığa uğramak, suya düşmek", "to fail / break down", "verb", "B2", "Die Verhandlungen sind leider im letzten Moment gescheitert.", "Müzakereler maalesef son anda başarısızlıkla sonuçlandı.", "The negotiations unfortunately failed at the last moment.", ["misslingen"], ["gelingen", "erfolgreich sein"]),
    ("fördern (fördert, förderte, hat gefördert)", "teşvik etmek, desteklemek", "to promote / foster / encourage", "verb", "B2", "Der Staat fördert innovative Start-up-Unternehmen.", "Devlet yenilikçi girişim şirketlerini teşvik ediyor.", "The state promotes innovative startup companies.", ["unterstützen"], ["hemmen", "behindern"]),
    ("einschränken (schränkt ein, schränkte ein, hat eingeschränkt)", "kısıtlamak, sınırlamak", "to restrict / limit / curtail", "verb", "B2", "Wir müssen unsere Ausgaben im kommenden Quartal einschränken.", "Gelecek çeyrekte harcamalarımızı kısıtlamak zorundayız.", "We must restrict our expenses in the upcoming quarter.", ["begrenzen", "reduzieren"], ["erweitern"]),
    ("beanspruchen (beansprucht, beanspruchte, hat beansprucht)", "talep etmek / zaman almak", "to claim / take up (time)", "verb", "B2", "Dieses komplexe Projekt beansprucht viel Zeit und Energie.", "Bu karmaşık proje çok fazla zaman ve enerji talep ediyor.", "This complex project takes up a lot of time and energy.", ["erfordern"], []),

    # B2 Nomen (51-95)
    ("die Verhandlungsgrundlage, -n", "müzakere temeli", "basis for negotiation", "noun", "B2", "Dieser Entwurf dient als solide Verhandlungsgrundlage.", "Bu taslak sağlam bir müzakere temeli olarak hizmet eder.", "This draft serves as a solid basis for negotiation.", ["die Ausgangsbasis"], []),
    ("das Phänomen, -e", "olgu, fenomen", "phenomenon", "noun", "B2", "Die globale Erwärmung ist ein weltweites Phänomen.", "Küresel ısınma dünya çapında bir olgudur.", "Global warming is a worldwide phenomenon.", ["die Erscheinung"], []),
    ("die Schlussfolgerung, -en", "çıkarım, vargı, netice", "conclusion / inference", "noun", "B2", "Welche logische Schlussfolgerung ziehen Sie aus den Daten?", "Verilerden hangi mantıksal çıkarımı yapıyorsunuz?", "What logical conclusion do you draw from the data?", ["das Fazit", "die Konsequenz"], []),
    ("die Herausforderung, -en", "zorluk, meydan okuma", "challenge", "noun", "B2", "Der Klimawandel ist die größte globale Herausforderung.", "İklim değişikliği en büyük küresel zorluktur.", "Climate change is the greatest global challenge.", ["die Bewährungsprobe"], []),
    ("die Rahmenbedingung, -en", "genel şartlar, çerçeve koşullar", "framework conditions / parameters", "noun", "B2", "Die wirtschaftlichen Rahmenbedingungen haben sich verbessert.", "Ekonomik çerçeve koşullar iyileşme gösterdi.", "The economic framework conditions have improved.", ["die Voraussetzungen"], []),
    ("die Maßnahme, -n", "önlem, tedbir", "measure / action", "noun", "B2", "Die Regierung ergreift strenge Maßnahmen gegen Inflation.", "Hükümet enflasyona karşı sıkı tedbirler alıyor.", "The government is taking strict measures against inflation.", ["der Schritt"], []),
    ("die Nachhaltigkeit, (nur Sg.)", "sürdürülebilirlik", "sustainability", "noun", "B2", "Nachhaltigkeit steht im Mittelpunkt unserer Firmenphilosophie.", "Sürdürülebilirlik şirket felsefemizin merkezinde yer alır.", "Sustainability is at the center of our corporate philosophy.", ["die Zukunftsfähigkeit"], []),
    ("die Auswirkung, -en", "etki, yankı, netice", "impact / repercussion", "noun", "B2", "Die Krise hatte schwere Auswirkungen auf den Arbeitsmarkt.", "Krizin iş piyasası üzerinde ağır etkileri oldu.", "The crisis had severe repercussions on the labor market.", ["der Effekt", "die Folge"], []),
    ("der Sachverhalt, -e", "olay, durum, vaka", "state of affairs / facts", "noun", "B2", "Der Anwalt schilderte den Sachverhalt sehr präzise.", "Avukat olayları son derece net bir biçimde aktardı.", "The lawyer described the facts of the case very precisely.", ["die Gegebenheit"], []),
    ("die Voraussetzung, -en", "ön koşul, şart", "prerequisite / condition", "noun", "B2", "Gute Deutschkenntnisse sind Voraussetzung für die Stelle.", "İyi Almanca bilgisi pozisyon için bir ön koşuldur.", "Good German skills are a prerequisite for the job.", ["die Bedingung"], []),
    ("die Erkenntnis, -se", "bilgi, kavrayış, bulgu", "insight / finding", "noun", "B2", "Neue wissenschaftliche Erkenntnisse verändern das Verständnis.", "Yeni bilimsel bulgular anlayışı değiştiriyor.", "New scientific insights are altering our understanding.", ["die Einsicht"], []),
    ("die Perspektive, -n", "bakış açısı, gelecek umudu", "perspective / outlook", "noun", "B2", "Der neue Job eröffnet ihr hervorragende Zukunftsperspektiven.", "Yeni iş ona harika gelecek perspektifleri sunuyor.", "The new job opens up excellent future perspectives for her.", ["der Blickwinkel", "die Aussicht"], []),
    ("die Vielfalt, (nur Sg.)", "çeşitlilik, zenginlik", "diversity / variety", "noun", "B2", "Kulturelle Vielfalt bereichert unsere Gesellschaft.", "Kültürel çeşitlilik toplumumuzu zenginleştirir.", "Cultural diversity enriches our society.", ["die Diversität", "die Abwechslung"], ["die Einförmigkeit"]),
    ("die Komplexität, (nur Sg.)", "karmaşıklık", "complexity", "noun", "B2", "Die Komplexität der modernen Welt verlangt Flexibilität.", "Modern dünyanın karmaşıklığı esneklik gerektirir.", "The complexity of the modern world demands flexibility.", ["die Vielschichtigkeit"], ["die Einfachheit"]),
    ("die Tendenz, -en", "eğilim, meyil", "tendency / trend", "noun", "B2", "Die Umfragen zeigen eine klare Tendenz nach oben.", "Anketler yukarıya doğru belirgin bir eğilim gösteriyor.", "The surveys show a clear upward trend.", ["der Trend", "die Neigung"], []),

    # B2 Adjektive (96-130)
    ("nachhaltig", "sürdürülebilir, kalıcı", "sustainable / lasting", "adj", "B2", "Wir brauchen nachhaltige Lösungen für den Verkehr.", "Ulaşım için sürdürülebilir çözümlere ihtiyacımız var.", "We need sustainable solutions for transportation.", ["dauerhaft"], ["kurzlebig"]),
    ("unabdingbar", "vazgeçilmez, olmazsa olmaz", "indispensable / essential", "adj", "B2", "Pünktlichkeit ist unabdingbar im Geschäftsleben.", "Dakiklik iş hayatında vazgeçilmezdir.", "Punctuality is indispensable in business life.", ["unverzichtbar"], ["verzichtbar"]),
    ("fundiert", "sağlam temelli, köklü", "sound / well-founded", "adj", "B2", "Er verfügt über ein fundiertes Fachwissen.", "O sağlam temelli bir uzmanlık bilgisine sahiptir.", "He possesses sound expert knowledge.", ["begründet"], ["oberflächlich"]),
    ("plausibel", "akla yatkın, mantıklı", "plausible / credible", "adj", "B2", "Ihre Erklärung klingt absolut plausibel.", "Açıklaması kulağa kesinlikle akla yatkın geliyor.", "Her explanation sounds absolutely plausible.", ["nachvollziehbar", "einleuchtend"], ["unplausibel"]),
    ("differenziert", "ayrıntılı, nüanslı", "differentiated / nuanced", "adj", "B2", "Man braucht eine differenzierte Betrachtungsweise.", "Nüanslı bir bakış açısına ihtiyaç vardır.", "One needs a differentiated perspective.", ["nuanciert"], ["pauschal"]),
    ("gravierend", "vahim, çok ciddi, ağır", "serious / severe / grave", "adj", "B2", "Der Vorfall hatte gravierende Folgen für den Betrieb.", "Olayın işletme için çok ciddi sonuçları oldu.", "The incident had severe consequences for the company.", ["schwerwiegend"], ["harmlos"]),
    ("relevant", "önemli, konuyla ilgili", "relevant / pertinent", "adj", "B2", "Bringen Sie bitte alle relevanten Dokumente mit!", "Lütfen konuyla ilgili tüm belgeleri yanınızda getiriniz!", "Please bring all relevant documents with you!", ["bedeutsam"], ["irrelevant"]),
    ("kontinuierlich", "sürekli, kesintisiz", "continuous / ongoing", "adj", "B2", "Er zeigt eine kontinuierliche Leistungssteigerung.", "Performansında sürekli bir artış gösteriyor.", "He shows continuous performance improvement.", ["fortlaufend", "stetig"], ["unterbrochen"]),
    ("signifikant", "belirgin, kayda değer", "significant", "adj", "B2", "Es gab einen signifikanten Anstieg der Bewerbungen.", "Başvurularda kayda değer bir artış oldu.", "There was a significant increase in applications.", ["deutlich", "spürbar"], ["unbedeutend"]),
    ("effizient", "verimli, etkili", "efficient", "adj", "B2", "Mit der neuen Software arbeiten wir viel effizienter.", "Yeni yazılımla çok daha verimli çalışıyoruz.", "With the new software we work much more efficiently.", ["wirkungsvoll"], ["ineffizient"]),
    ("prägnant", "özlü, veciz, net", "concise / succinct", "adj", "B2", "Fassen Sie die Kernbotschaft prägnant zusammen!", "Ana mesajı özlü bir şekilde özetleyiniz!", "Summarize the core message concisely!", ["treffend", "kurz"], ["langatmig"]),

    # B2 Nomen-Verb-Verbindungen (131-150)
    ("zur Sprache bringen", "gündeme getirmek, dile getirmek", "to bring up for discussion", "phrase", "B2", "Ich möchte ein heikles Thema zur Sprache bringen.", "Hassas bir konuyu gündeme getirmek istiyorum.", "I would like to bring up a delicate topic for discussion.", ["ansprechen"], ["verschweigen"]),
    ("zur Debatte stehen", "tartışılmakta olmak, söz konusu olmak", "to be debated / under discussion", "phrase", "B2", "Eine Kündigung steht derzeit überhaupt nicht zur Debatte.", "İşten çıkarılma şu anda kesinlikle söz konusu değildir.", "A termination is currently not at all under discussion.", ["diskutiert werden"], []),
    ("unter Beweis stellen", "kanıtlamak, ispat etmek", "to prove / demonstrate", "phrase", "B2", "Sie hat ihre Kompetenz mehrfach unter Beweis gestellt.", "Yetkinliğini defalarca kanıtlamıştır.", "She has demonstrated her competence multiple times.", ["beweisen"], []),
    ("in Gang setzen", "başlatmak, harekete geçirmek", "to set in motion / initiate", "phrase", "B2", "Die Initiative will eine gesellschaftliche Debatte in Gang setzen.", "Girişim toplumsal bir tartışmayı harekete geçirmek istiyor.", "The initiative aims to set a societal debate in motion.", ["initiieren"], ["stoppen"]),
    ("Maßnahmen ergreifen", "tedbir / önlem almak", "to take measures / actions", "phrase", "B2", "Wir müssen unverzüglich wirksame Maßnahmen ergreifen.", "Derhal etkili önlemler almak zorundayız.", "We must immediately take effective measures.", ["handeln"], []),
    ("Rückschlüsse ziehen aus (+ Dat)", "-den sonuçlar / çıkarımlar yapmak", "to draw conclusions from", "phrase", "B2", "Aus den Testergebnissen lassen sich klare Rückschlüsse ziehen.", "Test sonuçlarından net çıkarımlar yapılabilmektedir.", "Clear conclusions can be drawn from the test results.", ["folgern"], []),
    ("Aufschluss geben über (+ Akk)", "hakkında aydınlatıcı bilgi vermek", "to shed light on / provide clues about", "phrase", "B2", "Die Unterlagen geben genauen Aufschluss über die Kosten.", "Evraklar maliyetler hakkında ayrıntılı bilgi veriyor.", "The documents shed precise light on the costs.", ["aufklären"], []),
    ("in Erwägung ziehen", "düşünmek, değerlendirmeye almak", "to consider / contemplate", "phrase", "B2", "Wir ziehen einen Umzug ins Ausland ernsthaft in Erwägung.", "Yurt dışına taşınmayı ciddi şekilde değerlendirmeye alıyoruz.", "We are seriously contemplating moving abroad.", ["nachdenken über"], []),
    ("in Kauf nehmen", "göze almak, katlanmak", "to accept / put up with (risk/loss)", "phrase", "B2", "Für den Traumjob nahm er lange Pendelzeiten in Kauf.", "Hayalindeki iş için uzun yolculuk sürelerini göze aldı.", "For his dream job he accepted long commute times.", ["akzeptieren"], []),
    ("ins Auge fassen", "göz önünde bulundurmak, planlamak", "to envisage / consider / eye", "phrase", "B2", "Das Unternehmen fasst eine Expansion nach Asien ins Auge.", "Şirket Asya'ya açılmayı göz önünde bulunduruyor.", "The company is envisaging an expansion into Asia.", ["planen"], []),
    ("zum Ausdruck bringen", "ifade etmek, dile getirmek", "to express / voice", "phrase", "B2", "Er brachte seine tiefe Dankbarkeit zum Ausdruck.", "Derin minnettarlığını dile getirdi.", "He expressed his deep gratitude.", ["ausdrücken"], []),
    ("außer Zweifel stehen", "şüphe götürmez olmak", "to be beyond doubt", "phrase", "B2", "Seine hohe fachliche Kompetenz steht völlig außer Zweifel.", "Onun yüksek mesleki yetkinliği kesinlikle şüphe götürmez.", "His high professional competence is completely beyond doubt.", ["unstrittig sein"], []),
    ("in Abrede stellen", "inkar etmek, reddetmek", "to dispute / deny", "phrase", "B2", "Niemand kann seine großen Verdienste in Abrede stellen.", "Hiç kimse onun büyük hizmetlerini inkar edemez.", "Nobody can dispute his great merits.", ["bestreiten", "leugnen"], ["anerkennen"]),

    # Weitere B2 Verben (75-105)
    ("etablieren (etabliert, etablierte, hat etabliert)", "yerleştirmek, kurumsallaştırmak", "to establish / entrench", "verb", "B2", "Die Marke hat sich fest auf dem europäischen Markt etabliert.", "Marka Avrupa pazarında sağlam bir şekilde yer edindi.", "The brand has firmly established itself on the European market.", ["verankern"], []),
    ("implementieren (implementiert, implementierte, hat implementiert)", "uygulamaya koymak, entegre etmek", "to implement", "verb", "B2", "Wir müssen die neue Software schrittweise implementieren.", "Yeni yazılımı adım adım uygulamaya koymalıyız.", "We must implement the new software step by step.", ["einführen", "umsetzen"], []),
    ("konzipieren (konzipiert, konzipierte, hat konzipiert)", "tasarlamak, kurgulamak", "to conceive / design", "verb", "B2", "Das Trainingsprogramm wurde speziell für Berufstätige konzipiert.", "Eğitim programı özellikle çalışanlar için tasarlandı.", "The training program was designed especially for working professionals.", ["entwerfen"], []),
    ("revidieren (revidiert, revidierte, hat revidiert)", "gözden geçirmek, düzeltmek", "to revise / amend", "verb", "B2", "Nach neuen Erkenntnissen musste der Experte sein Urteil revidieren.", "Yeni bulguların ardından uzman yargısını revize etmek zorunda kaldı.", "Following new findings the expert had to revise his judgment.", ["korrigieren", "überprüfen"], []),
    ("legitimieren (legitimiert, legitimierte, hat legitimiert)", "meşrulaştırmak, yetkilendirmek", "to legitimize / authorize", "verb", "B2", "Demokratische Wahlen legitimieren die Gesetzgebung des Parlaments.", "Demokratik seçimler parlamentonun yasama yetkisini meşrulaştırır.", "Democratic elections legitimize parliament's legislation.", ["rechtfertigen"], []),
    ("bagatellisieren (bagatellisiert, bagatellisierte, hat bagatellisiert)", "önemsizleştirmek, hafife almak", "to downplay / trivialise", "verb", "B2", "Man darf die gesundheitlichen Risiken keinesfalls bagatellisieren.", "Sağlık riskleri hiçbir şekilde hafife alınmamalıdır.", "One must by no means downplay the health risks.", ["verharmlosen"], ["übertreiben"]),
    ("verharmlosen (verharmlost, verharmloste, hat verharmlost)", "tehlikesiz göstermek, basite indirgemek", "to downplay / make light of", "verb", "B2", "Der Sprecher versuchte, den folgenschweren Fehler zu verharmlosen.", "Sözcü, ağır sonuçları olan hatayı basite indirgemeye çalıştı.", "The spokesperson tried to make light of the momentous error.", ["bagatellisieren"], ["dramatisieren"]),
    ("abfedern (federt ab, federte ab, hat abgefedert)", "etkisini hafifletmek, amorti etmek", "to cushion / buffer", "verb", "B2", "Der Staat zahlt Zuschüsse, um die Inflation abzufedern.", "Devlet enflasyonu hafifletmek için sübvansiyonlar ödüyor.", "The state pays subsidies to cushion inflation.", ["dämpfen", "mildern"], []),
    ("reflektieren (reflektiert, reflektierte, hat reflektiert)", "derinlemesine düşünmek / yansıtmak", "to reflect on / ponder", "verb", "B2", "Es ist wichtig, das eigene Handeln im Alltag kritisch zu reflektieren.", "Günlük yaşamda kendi eylemlerini eleştirel şekilde gözden geçirmek önemlidir.", "It is important to critically reflect on one's own actions in daily life.", ["nachdenken über"], []),
    ("polarisieren (polarisiert, polarisierte, hat polarisiert)", "kutuplaştırmak", "to polarize", "verb", "B2", "Das umstrittene Thema polarisiert die Gesellschaft zusehends.", "Tartışmalı konu toplumu giderek daha fazla kutuplaştırıyor.", "The controversial topic is increasingly polarizing society.", ["spalten"], ["einigen"]),

    # B2 Abstrakte Nomen & Adjektive (106-130)
    ("die Diskrepanz, -en", "tutarsızlık, çelişki, uyuşmazlık", "discrepancy", "noun", "B2", "Es gibt eine deutliche Diskrepanz zwischen Worten und Taten.", "Sözler ile eylemler arasında belirgin bir tutarsızlık var.", "There is a distinct discrepancy between words and actions.", ["der Widerspruch", "die Kluft"], ["die Übereinstimmung"]),
    ("das Dilemma, die Dilemmata", "ikilem, çıkmaz", "dilemma", "noun", "B2", "Er stand vor einem moralischen Dilemma.", "Ahlaki bir ikilemin eşiğinde duruyordu.", "He stood before a moral dilemma.", ["die Zwickmühle"], []),
    ("das Defizit, -e", "açık, eksiklik (bütçe/bilgi)", "deficit / shortfall", "noun", "B2", "Der Staatshaushalt weist ein beachtliches Defizit auf.", "Devlet bütçesi dikkate değer bir açık sergiliyor.", "The state budget exhibits a considerable deficit.", ["der Mangel", "das Minus"], ["der Überschuss"]),
    ("der Paradigmenwechsel, -", "paradigma değişimi, köklü anlayış değişikliği", "paradigm shift", "noun", "B2", "Die Digitalisierung erfordert einen echten Paradigmenwechsel.", "Dijitalleşme gerçek bir paradigma değişimi gerektiriyor.", "Digitalization demands a genuine paradigm shift.", ["der Umdenkprozess"], []),
    ("die Redundanz, -en", "gereksiz tekrar, fazlalık", "redundancy", "noun", "B2", "Vermeiden Sie unnötige Redundanzen in Ihren Berichten!", "Raporlarınızda gereksiz tekrarlardan kaçınınız!", "Avoid unnecessary redundancies in your reports!", ["die Überflüssigkeit"], []),
    ("evident", "aşikar, apaçık, gün gibi ortada", "evident / obvious", "adj", "B2", "Die Vorteile dieser Methode sind wissenschaftlich evident.", "Bu yöntemin faydaları bilimsel olarak apaçıktır.", "The benefits of this method are scientifically evident.", ["offensichtlich", "augenfällig"], ["zweifelhaft"]),
    ("ambivalent", "çelişkili, ikircikli, çift duygulu", "ambivalent", "adj", "B2", "Sie hat eine sehr ambivalente Einstellung zur Kernkraft.", "Nükleer enerjiye karşı çok ikircikli bir tutumu var.", "She has a very ambivalent attitude towards nuclear power.", ["zwiespältig"], ["eindeutig"]),
    ("vehement", "şiddetli, hararetli", "vehement / fierce", "adj", "B2", "Sie verteidigte ihre Position mit vehementen Argumenten.", "Konumunu hararetli argümanlarla savundu.", "She defended her position with vehement arguments.", ["leidenschaftlich", "heftig"], ["zögerlich"]),
    ("adäquat", "uygun, yeterli, yerinde", "adequate / appropriate", "adj", "B2", "Wir müssen eine adäquate Antwort auf diese Krise finden.", "Bu krize uygun bir yanıt bulmak zorundayız.", "We must find an adequate response to this crisis.", ["angemessen", "passend"], ["inadäquat"]),
    ("obsolet", "modası geçmiş, geçerliliğini yitirmiş", "obsolete / outdated", "adj", "B2", "Durch die neue Technik sind alte Verfahren obsolet geworden.", "Yeni teknolojiyle birlikte eski yöntemler geçerliliğini yitirdi.", "Through the new technology old methods have become obsolete.", ["überholt", "veraltet"], ["aktuell"])
]

print(f"Loaded {len(B2_ADVANCED_DATA)} items into b2_advanced.py")

