# scripts/vocab_sources/c1_academic.py
"""
High-Yield Academic German Vocabulary for CEFR Level C1.
Designed for learners preparing for Goethe-Zertifikat C1, telc Deutsch C1 Hochschule,
and academic or professional university study in Germany.
Covers:
- Academic discourse & argumentative verbs
- Formal & abstract analytical nouns
- Precise scientific/academic adjectives
- Advanced connectors & discourse markers
"""

C1_ACADEMIC_DATA = [
    # C1 Verben
    ("abzielen (zielt ab, zielte ab, hat abgezielt) [auf + Akk]", "hedeflemek, amaçlamak", "to aim at / be targeted at", "verb", "C1", "Die neuen Maßnahmen zielen auf eine nachhaltige Reduktion der Emissionen ab.", "Yeni tedbirler emisyonların sürdürülebilir şekilde azaltılmasını hedefliyor.", "The new measures aim at a sustainable reduction in emissions.", ["ausgerichtet sein auf"], []),
    ("fungieren (fungiert, fungierte, hat fungiert) [als]", "görevini görmek, işlevi olmak", "to act / function / serve as", "verb", "C1", "Diese Definition fungiert als theoretische Grundlage für die gesamte Untersuchung.", "Bu tanım tüm araştırma için teorik temel işlevi görmektedir.", "This definition functions as a theoretical foundation for the entire investigation.", ["dienen als", "wirken als"], []),
    ("konstatieren (konstatiert, konstatierte, hat konstatiert)", "tespit etmek, saptamak", "to state / ascertain / note", "verb", "C1", "Die Autoren konstatieren eine zunehmende Diskrepanz zwischen Theorie und Praxis.", "Yazarlar teori ile pratik arasında giderek artan bir tutarsızlık tespit ediyorlar.", "The authors note an increasing discrepancy between theory and practice.", ["feststellen", "bemerken"], []),
    ("implizieren (impliziert, implizierte, hat impliziert)", "ima etmek, beraberinde getirmek", "to imply / entail", "verb", "C1", "Diese Annahme impliziert erhebliche methodische Konsequenzen.", "Bu varsayım önemli metodolojik sonuçlar ima etmektedir.", "This assumption implies significant methodological consequences.", ["beinhalten", "bedeuten"], ["ausschließen"]),
    ("postulieren (postuliert, postulierte, hat postuliert)", "ileri sürmek, varsaymak", "to postulate / posit", "verb", "C1", "Der Philosoph postuliert die Existenz universeller moralischer Werte.", "Filozof evrensel ahlaki değerlerin varlığını öne sürmektedir.", "The philosopher postulates the existence of universal moral values.", ["voraussetzen", "behaupten"], []),
    ("relativieren (relativiert, relativierte, hat relativiert)", "göreceli kılmak, etkisini azaltmak", "to put into perspective / relativize", "verb", "C1", "Neuere Forschungsergebnisse relativieren die bisherigen Erkenntnisse deutlich.", "Yeni araştırma sonuçları önceki bulguları belirgin biçimde göreceli kılmaktadır.", "Recent research findings significantly relativize previous insights.", ["abschwächen", "in Relation setzen"], ["verabsolutieren"]),
    ("verifizieren (verifiziert, verifizierte, hat verifiziert)", "doğrulamak, kanıtlamak", "to verify / substantiate", "verb", "C1", "Die Hypothese konnte durch empirische Experimente verifiziert werden.", "Hipotez ampirik deneylerle doğrulanabildi.", "The hypothesis could be verified through empirical experiments.", ["bestätigen", "belegen"], ["falsifizieren"]),
    ("falsifizieren (falsifiziert, falsifizierte, hat falsifiziert)", "yanlışlamak, çürütmek", "to falsify / disprove", "verb", "C1", "Wissenschaftliche Theorien müssen prinzipiell falsifizierbar sein.", "Bilimsel teoriler ilkesel olarak yanlışlanabilir olmalıdır.", "Scientific theories must in principle be falsifiable.", ["widerlegen"], ["verifizieren"]),
    ("prädestinieren (prädestiniert, prädestinierte, hat prädestiniert) [zu / für]", "özellikle uygun kılmak", "to predestine / qualify specially", "verb", "C1", "Ihre herausragenden Sprachkenntnisse prädestinieren sie für diese diplomatische Aufgabe.", "Üstün dil bilgisi onu bu diplomatik görev için biçilmiş kaftan yapıyor.", "Her outstanding language skills predestine her for this diplomatic task.", ["befähigen"], []),
    ("plausibilisieren (plausibilisiert, plausibilisierte, hat plausibilisiert)", "akla yatkın kılmak, gerekçelendirmek", "to substantiate / make plausible", "verb", "C1", "Der Autor versucht, seine These mit statistischem Material zu plausibilisieren.", "Yazar istatistiki verilerle tezini akla yatkın kılmaya çalışıyor.", "The author attempts to make his thesis plausible with statistical material.", ["begründen", "untermauern"], []),
    ("divergieren (divergiert, divergierte, hat divergiert)", "farklılaşmak, ıraksamamak", "to diverge / differ", "verb", "C1", "Die Meinungen der Experten divergieren in dieser strittigen Frage erheblich.", "Uzmanların görüşleri bu tartışmalı konuda belirgin şekilde farklılaşıyor.", "The opinions of the experts diverge considerably on this controversial issue.", ["voneinander abweichen"], ["konvergieren"]),
    ("konvergieren (konvergiert, konvergierte, hat konvergiert)", "yakınsamak, benzeşmek", "to converge", "verb", "C1", "Langfristig konvergieren die wirtschaftlichen Standards der Mitgliedstaaten.", "Uzun vadede üye devletlerin ekonomik standartları yakınsamaktadır.", "In the long term, the economic standards of member states converge.", ["sich annähern"], ["divergieren"]),
    ("akzentuieren (akzentuiert, akzentuierte, hat akzentuiert)", "vurgulamak, öne çıkarmak", "to accentuate / highlight", "verb", "C1", "Die Studie akzentuiert die Relevanz sozialer Netzwerke im Bildungsbereich.", "Çalışma eğitim alanında sosyal ağların önemini vurgulamaktadır.", "The study accentuates the relevance of social networks in education.", ["hervorheben", "betonen"], ["verschleiern"]),
    ("integrieren (integriert, integrierte, hat integriert)", "bütünleştirmek, entegre etmek", "to integrate", "verb", "C1", "Es gilt, qualitative und quantitative Methoden systematisch zu integrieren.", "Nitel ve nicel yöntemleri sistematik olarak bütünleştirmek gerekmektedir.", "It is essential to systematically integrate qualitative and quantitative methods.", ["einbinden", "zusammenführen"], ["isolieren"]),
    ("subsummieren (subsummiert, subsumierte, hat subsummiert) [unter + Akk]", "altına koymak, dahil etmek", "to subsume under / categorize", "verb", "C1", "Diese Einzelphänomene lassen sich unter dem Begriff der Globalisierung subsumieren.", "Bu münferit olgular küreselleşme kavramı altında toplanabilir.", "These individual phenomena can be subsumed under the concept of globalization.", ["unterordnen", "zusammenfassen"], []),

    # C1 Nomen
    ("die Diskrepanz, -en", "tutarsızlık, çelişki, uçurum", "discrepancy / divergence", "noun", "C1", "Zwischen Anspruch und Wirklichkeit besteht oft eine eklatante Diskrepanz.", "İddia ile gerçeklik arasında sıklıkla bariz bir tutarsızlık vardır.", "There is often a glaring discrepancy between aspiration and reality.", ["der Widerspruch", "die Kluft"], ["die Übereinstimmung"]),
    ("die Ambivalenz, -en", "ikirciklilik, çelişik duygu", "ambivalence", "noun", "C1", "Die Ambivalenz moderner Technologien stellt die Gesellschaft vor neue Fragen.", "Modern teknolojilerin ikircikli doğası toplumu yeni sorularla karşı karşıya bırakıyor.", "The ambivalence of modern technologies confronts society with new questions.", ["die Doppelwertigkeit", "die Zerrissenheit"], ["die Eindeutigkeit"]),
    ("das Paradigma, Paradigmen", "paradigma, temel model", "paradigm", "noun", "C1", "Die Quantenphysik leitete einen grundlegenden Paradigmenwechsel ein.", "Kuantum fiziği köklü bir paradigma değişimini başlattı.", "Quantum physics initiated a fundamental paradigm shift.", ["das Denkmuster", "das Leitbild"], []),
    ("die Kausalität, -en", "nedensellik, illiyet bağı", "causality / cause-and-effect relationship", "noun", "C1", "Zwischen Korrelation und Kausalität muss strikt unterschieden werden.", "Korelasyon ile nedensellik arasında kesin bir ayrım yapılmalıdır.", "A strict distinction must be made between correlation and causality.", ["der Ursachenzusammenhang"], []),
    ("die Kohärenz, (nur Sg.)", "tutarlılık, mantıksal uyum", "coherence / consistency", "noun", "C1", "Dem vorgelegten Text mangelt es an argumentativer Kohärenz.", "Sunulan metin argümantatif tutarlılıktan yoksundur.", "The presented text lacks argumentative coherence.", ["der Sinnzusammenhang", "die Stimmigkeit"], ["die Inkohärenz"]),
    ("die Prävalenz, -en", "yaygınlık, sıklık", "prevalence", "noun", "C1", "Die Prävalenz chronischer Krankheiten nimmt in alternden Gesellschaften zu.", "Yaşlanan toplumlarda kronik hastalıkların yaygınlığı artmaktadır.", "The prevalence of chronic diseases is increasing in aging societies.", ["die Häufigkeit", "die Verbreitung"], []),
    ("die Validität, (nur Sg.)", "geçerlilik (bilimsel)", "validity", "noun", "C1", "Die Validität der Testergebnisse wurde von unabhängigen Gutachtern bestätigt.", "Test sonuçlarının geçerliliği bağımsız bilirkişilerce teyit edildi.", "The validity of the test results was confirmed by independent reviewers.", ["die Gültigkeit"], ["die Ungültigkeit"]),
    ("die Reliabilität, (nur Sg.)", "güvenilirlik (ölçüm)", "reliability", "noun", "C1", "Eine hohe Reliabilität der Messung ist Grundvoraussetzung für die Studie.", "Ölçümün yüksek güvenilirliği çalışma için temel ön koşuldur.", "High measurement reliability is an essential prerequisite for the study.", ["die Zuverlässigkeit"], []),
    ("die Redundanz, -en", "gereksiz tekrar, fazlalık", "redundancy", "noun", "C1", "Durch das Eliminieren von Redundanzen wird der Text wesentlich prägnanter.", "Gereksiz tekrarların ayıklanmasıyla metin belirgin şekilde daha özlü hale gelir.", "Eliminating redundancies makes the text significantly more concise.", ["die Weitschweifigkeit", "der Überfluss"], ["die Prägnanz"]),
    ("die Affinität, -en [zu]", "yatkınlık, yakın ilgi", "affinity / propensity", "noun", "C1", "Studierende der Naturwissenschaften weisen oft eine hohe Affinität zur Mathematik auf.", "Doğa bilimleri öğrencileri genellikle matematiğe yüksek yatkınlık gösterir.", "Natural science students often exhibit a high affinity for mathematics.", ["die Neigung", "die Vorliebe"], ["die Abneigung"]),
    ("das Postulat, -e", "varsayım, ilke, önkoşul", "postulate / core demand", "noun", "C1", "Gleichberechtigung ist ein unumstößliches Postulat moderner Demokratien.", "Fırsat eşitliği modern demokrasilerin sarsılmaz bir ilkesidir.", "Equal rights is an incontrovertible postulate of modern democracies.", ["die Grundforderung", "die Maxime"], []),
    ("die Heterogenität, -en", "farklılık, çok seslilik, türdeş olmama", "heterogeneity / diversity", "noun", "C1", "Die kulturelle Heterogenität der Studierenden bereichert das Universitätsleben.", "Öğrencilerin kültürel çeşitliliği üniversite yaşamını zenginleştiriyor.", "The cultural heterogeneity of students enriches university life.", ["die Verschiedenartigkeit"], ["die Homogenität"]),
    ("die Homogenität, (nur Sg.)", "türdeşlik, homojenlik", "homogeneity", "noun", "C1", "Die soziale Homogenität der Testgruppe limitiert die Aussagekraft der Studie.", "Test grubunun sosyal homojenliği çalışmanın çıkarım gücünü sınırlamaktadır.", "The social homogeneity of the test group limits the study's generalizability.", ["die Einheitlichkeit"], ["die Heterogenität"]),
    ("die Quintessenz, -en", "öz, ana fikir, en önemli nokta", "quintessence / bottom line", "noun", "C1", "Die Quintessenz des Vortrags war, dass Innovation ohne Wagnis unmöglich ist.", "Konuşmanın özü inovasyonun cesaret olmadan imkansız olduğu yönündeydi.", "The quintessence of the lecture was that innovation is impossible without taking risks.", ["der Kern", "die Kernaussage"], []),
    ("die Konstellation, -en", "koşulların bir araya gelişi, durum", "constellation / situation", "noun", "C1", "In der gegenwärtigen geopolitischen Konstellation ist Besonnenheit gefragt.", "Mevcut jeopolitik tabloda sağduyu gerekmektedir.", "In the current geopolitical constellation, prudence is called for.", ["die Konstellation", "die Lage"], []),

    # C1 Adjektive
    ("evident", "açık, belirgin, su götürmez", "evident / obvious / self-evident", "adj", "C1", "Der kausale Zusammenhang zwischen Rauchen und Lungenkrebs ist wissenschaftlich evident.", "Sigara içmek ile akciğer kanseri arasındaki nedensellik bağı bilimsel olarak apaçıktır.", "The causal link between smoking and lung cancer is scientifically evident.", ["offenkundig", "augenfällig"], ["fraglich", "dubios"]),
    ("inhärent", "doğasında olan, içkin", "inherent / intrinsic", "adj", "C1", "Jeder technischen Neuerung sind gewisse Risiken inhärent.", "Her teknik yeniliğin doğasında belirli riskler içkindir.", "Certain risks are inherent in every technological innovation.", ["innewohnend", "immanent"], ["extrinsisch"]),
    ("prägnant", "özlü, kısa ve net", "concise / succinct / pithy", "adj", "C1", "Die Autorin formulierte ihre Thesen außergewöhnlich prägnant.", "Yazar tezlerini olağanüstü derecede özlü ve net şekilde ifade etti.", "The author formulated her theses with extraordinary conciseness.", ["treffend", "kurz und bündig"], ["weitschweifig"]),
    ("ambivalent", "çelişkili, ikircikli", "ambivalent", "adj", "C1", "Die Bevölkerung hat eine ambivalente Haltung zur Kernenergie.", "Halk nükleer enerjiye karşı ikircikli bir tutuma sahiptir.", "The population holds an ambivalent attitude toward nuclear energy.", ["zwiespältig", "doppelbödig"], ["eindeutig"]),
    ("rudimentär", "ilkel, başlangıç düzeyinde, yarım", "rudimentary / vestigial", "adj", "C1", "Seine Kenntnisse auf diesem Spezialgebiet sind leider nur rudimentär.", "Onun bu uzmanlık alanındaki bilgisi maalesef sadece başlangıç düzeyindedir.", "His knowledge in this specialized field is unfortunately merely rudimentary.", ["unzureichend", "ansatzweise"], ["umfassend", "ausgereift"]),
    ("singulär", "eşsiz, münferit, tekil", "singular / unique / isolated", "adj", "C1", "Hierbei handelt es sich keineswegs um ein singuläres Ereignis.", "Burada kesinlikle münferit bir olay söz konusu değildir.", "This is by no means a singular event.", ["einmalig", "isoliert"], ["alltäglich", "regelmßig"]),
    ("fundiert", "sağlam temelli, köklü", "sound / well-founded / grounded", "adj", "C1", "Ihre Kritik basiert auf einer fundierten wissenschaftlichen Analyse.", "Eleştirisi sağlam temelli bir bilimsel analize dayanmaktadır.", "Her critique is based on a sound scientific analysis.", ["solide", "stichhaltig"], ["oberflächlich", "haltlos"]),
    ("strikt", "sıkı, katı, kesin", "strict / rigorous", "adj", "C1", "Wir müssen die ethischen Richtlinien strikt einhalten.", "Etik yönergelerine sıkı bir şekilde uymak zorundayız.", "We must strictly adhere to the ethical guidelines.", ["streng", "kompromisslos"], ["lax", "nachgiebig"]),
    ("sukzessive", "kademeli olarak, yavaş yavaş", "successive / gradual", "adj", "C1", "Die Umstellung auf erneuerbare Energien erfolgt sukzessive.", "Yenilenebilir enerjiye geçiş kademeli olarak gerçekleşmektedir.", "The transition to renewable energy takes place gradually.", ["schrittweise", "allmählich"], ["abrupt", "plötzlich"]),
    ("adäquat", "uygun, yeterli, yerinde", "adequate / appropriate", "adj", "C1", "Für dieses komplexe Problem gibt es keine einfache, adäquate Lösung.", "Bu karmaşık problem için basit ve uygun bir çözüm bulunmamaktadır.", "There is no simple, adequate solution for this complex problem.", ["angemessen", "passend"], ["inadäquat", "unangemessen"]),

    # C1 Konnektoren & Formulierungen
    ("in Anbetracht (+ Gen)", "göz önüne alındığında, nazara alınarak", "in view of / considering", "prep", "C1", "In Anbetracht der aktuellen Wirtschaftslage sind Kürzungen unausweichlich.", "Mevcut ekonomik durum göz önüne alındığında kesintiler kaçınılmazdır.", "In view of the current economic situation, cutbacks are unavoidable.", ["angesichts"], []),
    ("kraft (+ Gen)", "yetkisiyle, gereğince, gücüyle", "by virtue of / on the strength of", "prep", "C1", "Kraft seines Amtes ordnete der Präsident eine Untersuchung an.", "Başkan makamının yetkisiyle bir soruşturma başlattı.", "By virtue of his office, the president ordered an investigation.", ["aufgrund", "kraft"], []),
    ("zwecks (+ Gen)", "amacıyla, maksadıyla", "for the purpose of / in order to", "prep", "C1", "Zwecks Optimierung des Workflows wurden neue Richtlinien erlassen.", "İş akışının optimizasyonu amacıyla yeni yönergeler yürürlüğe kondu.", "For the purpose of workflow optimization, new guidelines were enacted.", ["zur Erreichung von"], []),
    ("vorbehaltlich (+ Gen)", "saklı kalmak kaydıyla", "subject to / provided that", "prep", "C1", "Die Vereinbarung gilt vorbehaltlich der Zustimmung des Aufsichtsrats.", "Anlaşma denetleme kurulunun onayı saklı kalmak kaydıyla geçerlidir.", "The agreement is valid subject to the approval of the supervisory board.", ["unter dem Vorbehalt"], []),
    ("ungeachtet (+ Gen)", "bakılmaksızın, -e rağmen", "regardless of / notwithstanding", "prep", "C1", "Ungeachtet der widrigen Witterungsbedingungen wurde das Experiment fortgesetzt.", "Olumsuz hava koşullarına bakılmaksızın deney sürdürüldü.", "Notwithstanding the adverse weather conditions, the experiment was continued.", ["trotz"], []),
    ("anhand (+ Gen)", "vasıtasıyla, -e dayanarak, yardımıyla", "by means of / on the basis of", "prep", "C1", "Anhand der erhobenen Kennzahlen lässt sich ein klarer Trend ablesen.", "Toplanan göstergeler yardımıyla net bir eğilim okunabilmektedir.", "On the basis of the compiled key figures, a clear trend can be discerned.", ["mithilfe", "mittels"], []),
    ("gleichermaßen", "aynı derecede, eşit biçimde", "equally / in equal measure", "adv", "C1", "Diese Herausforderung betrifft Politik und Wirtschaft gleichermaßen.", "Bu zorluk siyaseti ve ekonomiyi eşit derecede ilgilendirmektedir.", "This challenge concerns both politics and the economy in equal measure.", ["in gleichem Maße"], []),
    ("zugleich", "aynı anda, aynı zamanda", "at the same time / simultaneously", "adv", "C1", "Das Projekt birgt erhebliche Risiken, eröffnet aber zugleich enorme Chancen.", "Proje önemli riskler barındırıyor, ancak aynı zamanda muazzam fırsatlar açıyor.", "The project involves significant risks, but at the same time opens up enormous opportunities.", ["gleichzeitig"], []),
    ("einerseits ... andererseits", "bir yandan ... öte yandan", "on the one hand ... on the other hand", "conj", "C1", "Einerseits ist die Neuerung teuer, andererseits spart sie langfristig Zeit.", "Yenilik bir yandan pahalı, öte yandan uzun vadede zaman kazandırıyor.", "On the one hand the innovation is expensive, on the other hand it saves time in the long run.", ["auf der einen Seite ..."], []),
    ("nichtsdestotrotz", "buna rağmen, yine de", "nevertheless / nonetheless", "adv", "C1", "Die Kritik war berechtigt, nichtsdestotrotz wurde der Vorschlag angenommen.", "Eleştiri haklıydı, buna rağmen öneri kabul edildi.", "The criticism was justified, nonetheless the proposal was adopted.", ["trotzdem", "dennoch"], [])
]
