# scripts/vocab_sources/connectors_phrases.py
"""
High-frequency German Connectors, Prepositions, and Idiomatic Phrases (A1, A2, B1).
Covers:
- Konjunktionen (weil, obwohl, damit, dass, wenn, als, usw.)
- Zweiteilige Konnektoren (sowohl... als auch, weder... noch, zwar... aber, nicht nur... sondern auch, entweder... oder, je... desto)
- Präpositionen mit Dativ, Akkusativ, Genitiv und Wechselpräpositionen
- Nomen-Verb-Verbindungen und feste Wendungen
"""

CONNECTORS_AND_PHRASES = [
    # Zweiteilige Konnektoren (1-10)
    ("sowohl ... als auch", "hem ... hem de", "both ... and / as well as", "conj", "B1", "Sie spricht sowohl fließend Deutsch als auch Englisch.", "O hem akıcı Almanca hem de İngilizce konuşuyor.", "She speaks both fluent German and English.", ["nicht nur ... sondern auch"], ["weder ... noch"]),
    ("nicht nur ... sondern auch", "sadece ... değil, aynı zamanda ...", "not only ... but also", "conj", "B1", "Er ist nicht nur sehr klug, sondern auch überaus fleißig.", "O sadece çok zeki değil, aynı zamanda son derece çalışkandır.", "He is not only very smart, but also extremely hardworking.", ["sowohl ... als auch"], []),
    ("weder ... noch", "ne ... ne de", "neither ... nor", "conj", "B1", "Ich trinke weder Kaffee noch schwarzen Tee.", "Ben ne kahve ne de siyah çay içerim.", "I drink neither coffee nor black tea.", [], ["sowohl ... als auch"]),
    ("entweder ... oder", "ya ... ya da", "either ... or", "conj", "A2", "Wir fahren dieses Jahr entweder nach Italien oder nach Spanien.", "Bu yıl ya İtalya'ya ya da İspanya'ya gidiyoruz.", "This year we are going either to Italy or to Spain.", [], []),
    ("zwar ... aber", "gerçi ... ama / her ne kadar ... ise de", "admittedly ... but / although ... yet", "conj", "B1", "Das Auto ist zwar gebraucht, aber in hervorragendem Zustand.", "Araba gerçi ikinci el ama mükemmel durumda.", "The car is admittedly used, but in excellent condition.", ["obwohl"], []),
    ("einerseits ... andererseits", "bir yandan ... diğer yandan", "on the one hand ... on the other hand", "conj", "B1", "Einerseits möchte ich reisen, andererseits muss ich sparen.", "Bir yandan seyahat etmek istiyorum, diğer yandan birikim yapmalıyım.", "On the one hand I'd like to travel, on the other hand I must save.", ["auf der einen Seite"], []),
    ("je ... desto", "ne kadar ... o kadar ...", "the ... the ...", "conj", "B1", "Je mehr du übst, desto schneller machst du Fortschritte.", "Ne kadar çok pratik yaparsan, o kadar hızlı ilerleme kaydedersin.", "The more you practice, the faster you make progress.", ["je ... umso"], []),
    ("je ... umso", "ne kadar ... o kadar ...", "the ... the ...", "conj", "B1", "Je früher wir aufbrechen, umso eher kommen wir an.", "Ne kadar erken yola çıkarsak, o kadar erken varırız.", "The earlier we set off, the sooner we arrive.", ["je ... desto"], []),
    ("nicht ... sondern", "... değil, aksine ...", "not ... but rather", "conj", "A2", "Wir fahren nicht mit dem Zug, sondern fliegen.", "Trenle gitmiyoruz, aksine uçuyoruz.", "We are not going by train, but rather flying.", [], []),
    ("teils ... teils", "kısmen ... kısmen", "partly ... partly", "conj", "B1", "Das Wetter war teils sonnig, teils regnerisch.", "Hava kısmen güneşli, kısmen yağmurluydu.", "The weather was partly sunny, partly rainy.", ["teilweise"], []),

    # Subjunktionen / Nebensatzkonnektoren (11-40)
    ("weil", "çünkü, -dığı için", "because", "conj", "A1", "Ich lerne fleißig Deutsch, weil ich in Berlin arbeiten möchte.", "Berlin'de çalışmak istediğim için gayretle Almanca öğreniyorum.", "I study German diligently because I want to work in Berlin.", ["da", "denn"], []),
    ("da", "mademki, -dığından dolayı", "since / because", "conj", "B1", "Da es heute stark regnet, bleiben wir im Haus.", "Bugün şiddetli yağmur yağdığından dolayı evde kalıyoruz.", "Since it is raining heavily today, we stay indoors.", ["weil"], []),
    ("obwohl", "-e rağmen, -se de", "although / even though", "conj", "B1", "Obwohl er müde war, lernte er bis spät in die Nacht.", "Yorgun olmasına rağmen gece geç saatlere kadar ders çalıştı.", "Although he was tired, he studied late into the night.", ["obgleich"], []),
    ("obgleich", "-e rağmen, gerçi", "although", "conj", "B1", "Obgleich das Wetter schlecht war, machten wir den Spaziergang.", "Hava kötü olmasına rağmen yürüyüşü yaptık.", "Although the weather was bad, we took the walk.", ["obwohl"], []),
    ("damit", "-sın diye, amacıyla", "so that / in order that", "conj", "B1", "Ich leihe dir mein Buch, damit du die Prüfung bestehst.", "Sınavı geçesin diye sana kitabımı ödünç veriyorum.", "I lend you my book so that you pass the exam.", ["um ... zu"], []),
    ("um ... zu", "-mek amacıyla, için", "in order to", "conj", "A2", "Er lernt Vokabeln, um die Prüfung zu bestehen.", "Sınavı geçmek için kelime öğreniyor.", "He learns vocabulary in order to pass the exam.", ["damit"], []),
    ("ohne ... zu", "-meksizin, -meden", "without doing", "conj", "B1", "Er verließ das Büro, ohne ein Wort zu sagen.", "Tek bir kelime söylemeksizin ofisten ayrıldı.", "He left the office without saying a word.", [], []),
    ("statt ... zu", "-mek yerine", "instead of doing", "conj", "B1", "Statt fernzusehen, las sie ein spannendes Buch.", "Televizyon izlemek yerine heyecanlı bir kitap okudu.", "Instead of watching TV, she read an exciting book.", ["anstatt ... zu"], []),
    ("anstatt ... zu", "-mek yerine", "instead of doing", "conj", "B1", "Anstatt zu klagen, packte er beherzt an.", "Şikayet etmek yerine cesurca işe koyuldu.", "Instead of complaining, he tackled the task boldly.", ["statt ... zu"], []),
    ("wenn", "eğer, -se / -dığı zaman (şimdi/gelecek)", "if / when", "conj", "A1", "Wenn du Zeit hast, trinken wir einen Kaffee.", "Zamanın olursa bir kahve içeriz.", "If you have time, we will drink a coffee.", ["falls"], []),
    ("falls", "şayet, eğer", "in case / if", "conj", "B1", "Falls es regnet, verlegen wir das Fest nach drinnen.", "Şayet yağmur yağarsa kutlamayı içeriye taşırız.", "In case it rains, we move the celebration indoors.", ["wenn"], []),
    ("als", "-dığı zaman (geçmişte tek sefer)", "when (past single event) / than", "conj", "A2", "Als ich ein Kind war, wohnten wir auf dem Land.", "Ben çocukken kırsalda oturuyorduk.", "When I was a child, we lived in the countryside.", [], []),
    ("während", "sırasında, iken / -e karşın", "while / whereas / during (+Gen)", "conj", "B1", "Während sie kochte, hörte sie klassische Musik.", "Yemek pişirirken klasik müzik dinliyordu.", "While she was cooking, she listened to classical music.", ["indem"], []),
    ("bevor", "-meden önce", "before (clause)", "conj", "A2", "Putz dir die Zähne, bevor du ins Bett gehst!", "Yatağa gitmeden önce dişlerini fırçala!", "Brush your teeth before you go to bed!", ["ehe"], ["nachdem"]),
    ("nachdem", "-dikten sonra", "after (clause)", "conj", "B1", "Nachdem er gefrühstückt hatte, ging er zur Arbeit.", "Kahvaltı yaptıktan sonra işe gitti.", "After he had eaten breakfast, he went to work.", [], ["bevor"]),
    ("seitdem", "-den beri", "since / ever since", "conj", "B1", "Seitdem er in Deutschland lebt, spricht er fließend Deutsch.", "Almanya'da yaşadığından beri akıcı Almanca konuşuyor.", "Ever since he lives in Germany, he speaks fluent German.", ["seit"], []),
    ("solange", "-dığı sürece", "as long as", "conj", "B1", "Solange du hier wohnst, musst du die Hausordnung beachten.", "Burada oturduğun sürece bina kurallarına uymak zorundasın.", "As long as you live here, you must observe the house rules.", [], []),
    ("sobald", "-r -mez, anında", "as soon as", "conj", "B1", "Sobald ich am Bahnhof ankomme, rufe ich dich sofort an.", "İstasyona varır varmaz seni hemen ararım.", "As soon as I arrive at the station, I will call you immediately.", ["gleich wenn"], []),
    ("bis", "-e kadar", "until / by", "conj", "A2", "Warte hier bitte, bis ich wiederkomme!", "Ben geri gelene kadar lütfen burada bekle!", "Please wait here until I come back!", [], []),
    ("indem", "-erek, -arak (yöntem)", "by doing / whereby", "conj", "B1", "Man lernt eine Sprache am besten, indem man sie täglich spricht.", "Bir dil en iyi her gün konuşularak öğrenilir.", "One learns a language best by speaking it daily.", ["dadurch dass"], []),
    ("sodass", "öyle ki, bunun sonucunda", "so that / such that", "conj", "B1", "Es schneite ununterbrochen, sodass alle Züge Verspätung hatten.", "Aralıksız kar yağdı, öyle ki bütün trenler gecikti.", "It snowed incessantly, so that all trains were delayed.", ["so dass"], []),
    ("dass", "-dığı, ki", "that", "conj", "A1", "Ich weiß sicher, dass du die Prüfung bestehen wirst.", "Sınavı geçeceğini kesin olarak biliyorum.", "I know for sure that you will pass the exam.", [], []),
    ("ob", "-ip -mediği", "whether / if", "conj", "A2", "Können Sie mir sagen, ob der Bus schon abgefahren ist?", "Otobüsün hareket edip etmediğini bana söyleyebilir misiniz?", "Can you tell me whether the bus has already departed?", [], []),

    # Hauptsatzkonnektoren / Konjunktionaladverbien (41-65)
    ("trotzdem", "yine de, buna rağmen", "nevertheless / anyway", "adv", "A2", "Es war kalt, trotzdem ging er ohne Mantel spazieren.", "Hava soğuktu, yine de palto olmadan yürüyüşe çıktı.", "It was cold, nevertheless he went for a walk without a coat.", ["dennoch"], []),
    ("dennoch", "bununla birlikte, gene de", "nonetheless / still", "adv", "B1", "Die Aufgabe war schwer, dennoch gab sie nicht auf.", "Görev zordu, buna rağmen vazgeçmedi.", "The task was difficult, nonetheless she did not give up.", ["trotzdem"], []),
    ("deshalb", "bu yüzden, bundan dolayı", "therefore / that's why", "adv", "A2", "Ich war krank, deshalb konnte ich nicht kommen.", "Hastaydım, bu yüzden gelemedim.", "I was sick, that's why I couldn't come.", ["deswegen", "darum", "daher"], []),
    ("deswegen", "bu sebeple", "therefore / on that account", "adv", "A2", "Der Zug hatte Verspätung, deswegen verpasste er den Anschluss.", "Tren gecikti, bu sebeple aktarmayı kaçırdı.", "The train was delayed, therefore he missed the connection.", ["deshalb"], []),
    ("daher", "bu nedenle, dolayısıyla", "hence / therefore", "adv", "B1", "Die Nachfrage ist hoch, daher steigen die Preise.", "Talep yüksek, dolayısıyla fiyatlar artıyor.", "The demand is high, hence prices are rising.", ["deshalb"], []),
    ("darum", "bu yüzden", "for that reason", "adv", "A2", "Er hat fleißig geübt, darum spricht er so gut.", "Gayretle pratik yaptı, bu yüzden bu kadar iyi konuşuyor.", "He practiced diligently, that's why he speaks so well.", ["deshalb"], []),
    ("außerdem", "ayrıca, bundan başka", "furthermore / besides", "adv", "A2", "Die Wohnung ist groß, außerdem liegt sie sehr zentral.", "Daire büyük, ayrıca çok merkezi bir konumda.", "The apartment is large, furthermore it is very centrally located.", ["zudem", "überdies"], []),
    ("zudem", "buna ek olarak", "moreover / additionally", "adv", "B1", "Das Hotel ist günstig und bietet zudem ein tolles Frühstück.", "Otel uygun fiyatlı ve buna ek olarak harika bir kahvaltı sunuyor.", "The hotel is affordable and moreover offers a great breakfast.", ["außerdem"], []),
    ("überdies", "üstelik, dahası", "moreover / what is more", "adv", "B1", "Er ist unzuverlässig und überdies unfreundlich.", "O güvenilmez ve üstelik kabadır.", "He is unreliable and what is more unfriendly.", ["außerdem"], []),
    ("folglich", "sonuç olarak, neticede", "consequently / as a result", "adv", "B1", "Er hat nicht gelernt, folglich fiel er durch die Prüfung.", "Çalışmadı, sonuç olarak sınavdan kaldı.", "He didn't study, consequently he failed the exam.", ["infolgedessen"], []),
    ("infolgedessen", "bunun sonucunda", "consequently", "adv", "B1", "Die Firma sparte Kosten, infolgedessen stieg der Gewinn.", "Şirket masraflardan tasarruf etti, bunun sonucunda kar arttı.", "The company cut costs, consequently profits rose.", ["folglich"], []),
    ("jedoch", "fakat, ancak, ne var ki", "however / though", "adv", "B1", "Er bemühte sich sehr, jedoch ohne jeden Erfolg.", "Çok çaba gösterdi, ancak hiçbir başarı elde edemedi.", "He tried hard, however without any success.", ["aber"], []),
    ("allerdings", "doğrusu, gerçi, yalnız", "however / indeed", "adv", "B1", "Das Essen schmeckte gut, war allerdings etwas teuer.", "Yemek lezzetliydi, doğrusu biraz pahalıydı.", "The food tasted good, however it was a bit expensive.", ["zwar"], []),
    ("sonst", "yoksa, aksi takdirde / başka", "otherwise / else", "adv", "A2", "Beeil dich, sonst verpassen wir noch den Bus!", "Acele et, yoksa otobüsü kaçıracağız!", "Hurry up, otherwise we will miss the bus!", ["andernfalls"], []),
    ("andernfalls", "aksi halde", "otherwise", "adv", "B1", "Zahlen Sie die Rechnung pünktlich, andernfalls drohen Mahngebühren.", "Faturayı vaktinde ödeyiniz, aksi halde ihtar ücreti uygulanır.", "Pay the bill on time, otherwise reminder fees apply.", ["sonst"], []),
    ("nämlich", "çünkü, nitekim / yani", "namely / because / that is", "adv", "A2", "Ich muss absagen, ich bin nämlich leider krank geworden.", "İptal etmek zorundayım, çünkü maalesef hastalandım.", "I have to cancel, namely because unfortunately I fell ill.", ["denn"], []),
    ("schließlich", "sonunda, nihayet / ne de olsa", "finally / after all", "adv", "B1", "Nach langem Warten kam schließlich der Zug.", "Uzun bekleyişin ardından nihayet tren geldi.", "After a long wait the train finally arrived.", ["endlich"], []),
    ("überhaupt", "genel olarak, aslında, hiç", "at all / generally", "adv", "A2", "Hast du überhaupt keine Zeit für mich?", "Bana ayıracak hiç mi vaktin yok?", "Don't you have any time at all for me?", ["gar"], []),
    ("eigentlich", "aslında, aslen", "actually / strictly speaking", "adv", "A2", "Was machst du eigentlich beruflich?", "Aslında meslek olarak ne yapıyorsun?", "What do you actually do for a living?", ["im Grunde"], []),
    ("nämlich", "yani, zira", "namely", "adv", "B1", "Sie kommt später, sie hat nämlich einen Termin beim Arzt.", "O daha sonra gelecek, zira doktorda randevusu var.", "She will arrive later, namely because she has an appointment at the doctor.", [], []),

    # Präpositionen mit Fällen (66-105)
    ("wegen (+ Gen/Dat)", "-den dolayı, yüzünden", "because of / on account of", "prep", "A2", "Wegen des starken Sturms fielen alle Züge aus.", "Şiddetli fırtınadan dolayı tüm tren seferleri iptal edildi.", "Because of the heavy storm all trains were cancelled.", ["aufgrund"], []),
    ("trotz (+ Gen/Dat)", "-e rağmen", "in spite of / despite", "prep", "B1", "Trotz des schlechten Wetters gingen wir wandern.", "Kötü havaya rağmen yürüyüşe çıktık.", "In spite of the bad weather we went hiking.", ["ungeachtet"], []),
    ("während (+ Gen)", "esnasında, sırasında", "during", "prep", "B1", "Während des Vortrags hörten alle aufmerksam zu.", "Sunum esnasında herkes dikkatle dinledi.", "During the lecture everyone listened attentively.", ["im Laufe von"], []),
    ("innerhalb (+ Gen)", "içinde (zaman/mekan)", "within / inside of", "prep", "B1", "Bitte antworten Sie innerhalb von drei Tagen.", "Lütfen üç gün içinde yanıt veriniz.", "Please reply within three days.", ["binnen"], ["außerhalb"]),
    ("außerhalb (+ Gen)", "dışında (zaman/mekan)", "outside of", "prep", "B1", "Das Büro liegt außerhalb des Stadtzentrums.", "Ofis şehir merkezinin dışında yer alıyor.", "The office is located outside the city center.", [], ["innerhalb"]),
    ("anstatt (+ Gen)", "yerine", "instead of", "prep", "B1", "Anstatt eines Geschenks wünschte er sich eine Spende.", "Bir hediye yerine bağış yapılmasını diledi.", "Instead of a gift he wished for a donation.", ["statt"], []),
    ("statt (+ Gen/Dat)", "yerine", "instead of", "prep", "A2", "Er nimmt die Treppe statt des Aufzugs.", "Asansör yerine merdivenleri kullanıyor.", "He takes the stairs instead of the elevator.", ["anstatt"], []),
    ("aufgrund (+ Gen)", "-den dolayı, gerekçesiyle", "due to / on the basis of", "prep", "B1", "Aufgrund technischer Probleme ist der Server offline.", "Teknik problemlerden dolayı sunucu çevrimdışı.", "Due to technical issues the server is offline.", ["wegen"], []),
    ("mit (+ Dat)", "ile, birlikte", "with", "prep", "A1", "Ich fahre jeden Morgen mit dem Bus zur Arbeit.", "Her sabah otobüs ile işe gidiyorum.", "I go to work with the bus every morning.", [], ["ohne"]),
    ("ohne (+ Akk)", "-siz, -sız", "without", "prep", "A1", "Ohne Fleiß kein Preis, sagt ein deutsches Sprichwort.", "Zahmetsiz rahmet olmaz (emeksiz ödül yok), der bir Alman atasözü.", "No pain, no gain (without effort no prize), says a German proverb.", [], ["mit"]),
    ("für (+ Akk)", "için", "for", "prep", "A1", "Dieses Geschenk ist speziell für dich gedacht.", "Bu hediye özellikle senin için düşünüldü.", "This gift is intended especially for you.", [], []),
    ("gegen (+ Akk)", "karşı / sularında (saat)", "against / around (time)", "prep", "A1", "Ich nehme eine Tablette gegen Kopfschmerzen.", "Baş ağrısına karşı bir hap alıyorum.", "I take a pill against headaches.", ["wider"], ["für"]),
    ("durch (+ Akk)", "içinden, vasıtasıyla", "through / by means of", "prep", "A1", "Wir gehen langsam durch den herbstlichen Park.", "Sonbahar parkının içinden yavaşça geçiyoruz.", "We walk slowly through the autumnal park.", [], []),
    ("um (+ Akk)", "etrafında / saatte (-de)", "around / at (time)", "prep", "A1", "Wir treffen uns pünktlich um 18 Uhr.", "Saat 18'de tam vaktinde buluşuyoruz.", "We meet punctually at 6 pm.", ["rund um"], []),
    ("entlang (+ Akk/Dat)", "boyunca", "along", "prep", "A2", "Spazieren Sie den Fluss entlang!", "Nehir boyunca yürüyünüz!", "Walk along the river!", [], []),
    ("aus (+ Dat)", "-den (içinden, ülkeden)", "out of / from", "prep", "A1", "Ich komme aus der Türkei.", "Ben Türkiye'den geliyorum.", "I come from Turkey.", ["von"], []),
    ("bei (+ Dat)", "-de, yanında, esnasında", "at / with / near", "prep", "A1", "Er wohnt noch bei seinen Eltern.", "Hala anne babasının yanında oturuyor.", "He still lives with his parents.", [], []),
    ("nach (+ Dat)", "-e doğru (şehir/ülke) / -den sonra", "to / after", "prep", "A1", "Nach dem Essen trinken wir einen Espresso.", "Yemekten sonra bir espresso içeriz.", "After the meal we drink an espresso.", [], ["vor"]),
    ("seit (+ Dat)", "-den beri", "since / for (time duration)", "prep", "A1", "Ich lerne seit sechs Monaten Deutsch.", "Altı aydan beri Almanca öğreniyorum.", "I have been learning German for six months.", [], []),
    ("von (+ Dat)", "-den, tarafından, -in (aitlik)", "from / by / of", "prep", "A1", "Das ist ein Geschenk von meiner Kollegin.", "Bu iş arkadaşımdan bir hediye.", "That is a gift from my colleague.", ["aus"], []),
    ("zu (+ Dat)", "-e, yönüne, amacıyla", "to / towards", "prep", "A1", "Wie komme ich am besten zum Bahnhof?", "İstasyona en iyi nasıl gidebilirim?", "What is the best way to get to the train station?", ["nach"], []),
    ("gegenüber (+ Dat)", "karşısında, -e karşı", "opposite / towards", "prep", "A2", "Die Bank liegt genau gegenüber der Post.", "Banka tam postanenin karşısında yer alıyor.", "The bank lies exactly opposite the post office.", [], []),

    # Nomen-Verb-Verbindungen & Feste Wendungen (106-145)
    ("Bescheid wissen", "haberdar olmak, bilmek", "to be informed / to know", "phrase", "B1", "Ich weiß über diesen Fall genau Bescheid.", "Bu vaka hakkında tam olarak bilgi sahibiyim.", "I am fully informed about this case.", ["informiert sein"], []),
    ("Bescheid geben / sagen", "haber vermek, bilgilendirmek", "to let know / inform", "phrase", "A2", "Sag mir bitte Bescheid, wenn du ankommst!", "Vardığında lütfen bana haber ver!", "Please let me know when you arrive!", ["informieren"], []),
    ("in Betracht ziehen", "dikkate almak, hesaba katmak", "to take into consideration", "phrase", "B1", "Wir müssen alle Möglichkeiten in Betracht ziehen.", "Tüm olasılıkları hesaba katmalıyız.", "We must take all possibilities into consideration.", ["berücksichtigen"], ["ignorieren"]),
    ("zur Verfügung stehen", "kullanıma hazır olmak, emrinde olmak", "to be available / at disposal", "phrase", "B1", "Für Rückfragen stehe ich Ihnen gerne zur Verfügung.", "Sorularınız için memnuniyetle hizmetinizdeyim.", "For further questions I am gladly at your disposal.", ["verfügbar sein"], []),
    ("zur Verfügung stellen", "kullanıma sunmak, tahsis etmek", "to make available / provide", "phrase", "B1", "Die Schule stellt kostenlose Tablets zur Verfügung.", "Okul ücretsiz tabletleri kullanıma sunuyor.", "The school makes free tablets available.", ["bereitstellen"], []),
    ("eine Rolle spielen", "rol oynamak, önem taşımak", "to play a role / to matter", "phrase", "B1", "Geld spielt in dieser Frage keine Rolle.", "Bu meselede para hiçbir rol oynamıyor.", "Money plays no role in this matter.", ["von Bedeutung sein"], []),
    ("Rücksicht nehmen auf (+ Akk)", "saygı göstermek, gözetmek", "to show consideration for", "phrase", "B1", "Nehmen Sie bitte Rücksicht auf ältere Fahrgäste!", "Lütfen yaşlı yolculara karşı saygılı ve anlayışlı olunuz!", "Please show consideration for elderly passengers!", ["respektieren"], []),
    ("Abschied nehmen von (+ Dat)", "veda etmek", "to say goodbye to / take leave", "phrase", "B1", "Wir müssen heute Abschied von unseren Freunden nehmen.", "Bugün arkadaşlarımıza veda etmek zorundayız.", "Today we must say goodbye to our friends.", ["sich verabschieden"], ["begrüßen"]),
    ("eine Entscheidung treffen", "karar vermek", "to make a decision", "phrase", "B1", "Er muss heute eine wichtige Entscheidung treffen.", "Bugün önemli bir karar vermek zorunda.", "He must make an important decision today.", ["sich entscheiden"], []),
    ("einen Fehler machen", "hata yapmak", "to make a mistake", "phrase", "A1", "Jeder Mensch macht hin und wieder Fehler.", "Her insan ara sıra hata yapar.", "Every human makes mistakes now and then.", ["sich irren"], []),
    ("zu Ende bringen", "sona erdirmek, bitirmek", "to bring to an end / finish", "phrase", "B1", "Wir wollen das Projekt erfolgreich zu Ende bringen.", "Projeyi başarıyla sona erdirmek istiyoruz.", "We want to bring the project to a successful end.", ["beenden"], ["anfangen"]),
    ("in Frage kommen", "söz konusu olmak", "to be out of the question / in question", "phrase", "B1", "Eine Verspätung kommt heute überhaupt nicht in Frage.", "Bugün bir gecikme asla söz konusu olamaz.", "A delay is completely out of the question today.", ["möglich sein"], ["ausgeschlossen sein"]),
    ("zur Ruhe kommen", "sakinleşmek, huzura ermek", "to come to rest / unwind", "phrase", "B1", "Am Wochenende komme ich endlich zur Ruhe.", "Hafta sonu nihayet huzura erip dinleniyorum.", "On the weekend I finally come to rest.", ["sich entspannen"], []),
    ("zu Wort kommen", "söz almak, konuşma fırsatı bulmak", "to get a chance to speak", "phrase", "B1", "In der hitzigen Debatte kam kaum jemand zu Wort.", "Ateşli tartışmada neredeyse hiç kimse söz alamadı.", "In the heated debate hardly anyone got a chance to speak.", [], []),
    ("Eindruck machen auf (+ Akk)", "etkilemek, tesir bırakmak", "to make an impression on", "phrase", "B1", "Seine Präsentation machte großen Eindruck auf die Chefs.", "Sunumu patronlar üzerinde büyük bir etki bıraktı.", "His presentation made a big impression on the bosses.", ["beeindrucken"], []),
    ("Kritik üben an (+ Dat)", "eleştirmek", "to criticize / voice criticism", "phrase", "B1", "Die Opposition übte scharfe Kritik an der Regierung.", "Muhalefet hükümete sert eleştiriler yöneltti.", "The opposition voiced sharp criticism of the government.", ["kritisieren"], ["loben"]),
    ("die Hoffnung aufgeben", "umudunu kesmek, vazgeçmek", "to give up hope", "phrase", "B1", "Man darf niemals die Hoffnung aufgeben.", "İnsan asla umudunu kaybetmemelidir.", "One must never give up hope.", ["verzweifeln"], ["hoffen"]),
    ("in Anspruch nehmen", "yararlanmak, talep etmek, zaman almak", "to make use of / take up (time)", "phrase", "B1", "Das Verfahren nimmt viel Zeit in Anspruch.", "İşlem çok zaman alıyor.", "The procedure takes up a lot of time.", ["beanspruchen"], []),
    ("in Betrieb sein", "faaliyette / çalışır durumda olmak", "to be in operation", "phrase", "B1", "Die neue U-Bahn-Linie ist ab morgen in Betrieb.", "Yeni metro hattı yarından itibaren faaliyettedir.", "The new subway line is in operation from tomorrow.", ["funktionieren"], ["außer Betrieb sein"]),
    ("außer Betrieb sein", "hizmet dışı / bozuk olmak", "to be out of order", "phrase", "A2", "Der Aufzug ist leider vorübergehend außer Betrieb.", "Asansör maalesef geçici olarak hizmet dışıdır.", "Unfortunately the elevator is temporarily out of order.", ["defekt sein"], ["in Betrieb sein"]),
    ("vor Gericht stehen", "mahkemede yargılanmak", "to stand trial in court", "phrase", "B1", "Der Angeklagte steht heute vor Gericht.", "Sanık bugün mahkemede yargılanıyor.", "The defendant stands trial in court today.", [], []),
    ("den Mut verlieren", "cesaretini yitirmek", "to lose heart / courage", "phrase", "B1", "Verliere jetzt bitte nicht den Mut!", "Lütfen şimdi cesaretini yitirme!", "Please do not lose heart now!", ["aufgeben"], ["Mut fassen"]),
    ("Schritt für Schritt", "adım adım", "step by step", "phrase", "A2", "Wir lernen Schritt für Schritt neue Vokabeln.", "Adım adım yeni kelimeler öğreniyoruz.", "We learn new vocabulary step by step.", ["nach und nach"], []),
    ("auf jeden Fall", "her halükarda, kesinlikle", "definitely / in any case", "phrase", "A1", "Ich komme auf jeden Fall zu deiner Geburtstagsparty.", "Doğum günü partine kesinlikle geliyorum.", "I will definitely come to your birthday party.", ["unbedingt"], ["auf keinen Fall"]),
    ("auf keinen Fall", "hiçbir şekilde, asla", "under no circumstances / no way", "phrase", "A1", "Das darfst du auf keinen Fall weitererzählen!", "Bunu hiçbir şekilde başkasına anlatmamalısın!", "Under no circumstances should you tell that to anyone!", ["niemals"], ["auf jeden Fall"])
]

print(f"Loaded {len(CONNECTORS_AND_PHRASES)} connectors and phrases.")
