# scripts/vocab_sources/final_boost_2000.py
"""
Final 320 German Vocabulary Items to reach exactly 2000 CEFR A1-B1 Core Words.
Covers:
- Modern communication, media & internet
- Leisure, hobbies, art & music
- Animals, nature & weather phenomena
- Travel, hotel, luggage & customs
- Home, appliances, gardening & DIY
- Quantitative, spatial & emotional descriptions
All items formatted as: (de, tr, en, pos, level, ex, ex_tr, ex_en, syns, ants)
"""

FINAL_BOOST_2000 = [
    # Reisen, Hotel & Tourismus (1-45)
    ("die Reise, -n", "seyahat, gezi, yolculuk", "trip / journey / travel", "noun", "A1", "Gute Reise und pass gut auf dich auf!", "İyi yolculuklar ve kendine iyi bak!", "Have a good trip and take good care of yourself!", ["die Fahrt"], []),
    ("das Reisebüro, -s", "seyahat acentesi", "travel agency", "noun", "A1", "Wir haben den Urlaub im Reisebüro gebucht.", "Tatili seyahat acentesinden ayarladık.", "We booked the holiday at the travel agency.", [], []),
    ("das Reiseziel, -e", "seyahat hedefi, varış yeri", "travel destination", "noun", "A2", "Spanien ist ein sehr beliebtes Reiseziel für Deutsche.", "İspanya Almanlar için çok popüler bir tatil rotasıdır.", "Spain is a very popular travel destination for Germans.", ["der Urlaubsort"], []),
    ("der Kofferanhänger, -", "bavul etiketi", "luggage tag", "noun", "A2", "Schreiben Sie Ihren Namen auf den Kofferanhänger!", "Bavul etiketinin üzerine adınızı yazınız!", "Write your name on the luggage tag!", [], []),
    ("das Handgepäck, (nur Sg.)", "el bagajı, kabin bagajı", "hand luggage / carry-on", "noun", "A2", "Im Handgepäck darf man keine großen Flüssigkeiten mitnehmen.", "El bagajında büyük sıvılar taşınamaz.", "In hand luggage one may not take large liquids.", [], []),
    ("das Gepäckband, ⸚er", "bagaj bandı", "baggage carousel", "noun", "A2", "Wir warten am Gepäckband auf unsere Koffer.", "Bagaj bandında bavullarımızı bekliyoruz.", "We are waiting at the baggage carousel for our suitcases.", [], []),
    ("die Bordkarte, -n", "biniş kartı", "boarding pass", "noun", "A2", "Zeigen Sie bitte Ihre Bordkarte am Flugsteig vor!", "Lütfen biniş kapısında biniş kartınızı gösteriniz!", "Please present your boarding pass at the gate!", ["die Bordkarte"], []),
    ("der Flugsteig, -e", "biniş kapısı (havalimanı)", "boarding gate", "noun", "A2", "Der Flug nach Istanbul startet von Flugsteig B12.", "İstanbul uçuşu B12 biniş kapısından kalkıyor.", "The flight to Istanbul departs from gate B12.", ["das Gate"], []),
    ("die Sicherheitskontrolle, -n", "güvenlik kontrolü", "security check", "noun", "A2", "An der Sicherheitskontrolle müssen Sie den Gürtel ablegen.", "Güvenlik kontrolünde kemerinizi çıkarmalısınız.", "At the security check you must take off your belt.", [], []),
    ("der Zoll, ⸚e", "gümrük", "customs / duty", "noun", "B1", "Beim Zoll musste er die teure Uhr deklarieren.", "Gümrükte pahalı saati beyan etmek zorunda kaldı.", "At customs he had to declare the expensive watch.", [], []),
    ("die Unterkunft, ⸚e", "konaklama yeri, kalacak yer", "accommodation / lodging", "noun", "A2", "Die Unterkunft in den Bergen war sauber und gemütlich.", "Dağlardaki konaklama yeri temiz ve samimiydi.", "The accommodation in the mountains was clean and cozy.", ["die Herberge"], []),
    ("das Hotel, -s", "otel", "hotel", "noun", "A1", "Wir übernachten in einem modernen Hotel im Stadtzentrum.", "Şehir merkezinde modern bir otelde konaklıyoruz.", "We are staying overnight in a modern hotel in the city center.", ["die Herberge"], []),
    ("die Pension, -en", "pansiyon / emekli maaşı", "guesthouse / pension", "noun", "A2", "Die kleine Pension bietet ein hervorragendes Frühstück.", "Küçük pansiyon harika bir kahvaltı sunuyor.", "The small guesthouse offers an excellent breakfast.", ["das Gästehaus"], []),
    ("die Jugendherberge, -n", "gençlik hosteli", "youth hostel", "noun", "A2", "Jugendherbergen sind eine preiswerte Übernachtungsmöglichkeit.", "Gençlik hostelleri uygun fiyatlı bir konaklama imkanıdır.", "Youth hostels are an affordable accommodation option.", ["das Hostel"], []),
    ("das Einzelzimmer, -", "tek kişilik oda", "single room", "noun", "A1", "Ich möchte bitte ein ruhiges Einzelzimmer reservieren.", "Lütfen sakin bir tek kişilik oda ayırtmak istiyorum.", "I would like to reserve a quiet single room please.", [], ["das Doppelzimmer"]),
    ("das Doppelzimmer, -", "çift kişilik oda", "double room", "noun", "A1", "Haben Sie noch ein freies Doppelzimmer mit Balkon?", "Balkonlu boş bir çift kişilik odanız var mı?", "Do you still have a free double room with a balcony?", [], ["das Einzelzimmer"]),
    ("die Rezeption, -en", "resepsiyon", "reception / front desk", "noun", "A1", "Geben Sie den Zimmerschlüssel bitte an der Rezeption ab!", "Oda anahtarını lütfen resepsiyona teslim ediniz!", "Please leave the room key at the front desk!", ["der Empfang"], []),
    ("der Empfang, ⸚e", "karşılama, resepsiyon / sinyal", "reception", "noun", "A2", "Der herzliche Empfang im Hotel hat uns sehr gefreut.", "Oteldeki sıcak karşılama bizi çok sevindirdi.", "The warm reception at the hotel pleased us greatly.", ["die Rezeption"], []),
    ("die Buchung, -en", "rezervasyon, kayıt", "booking / reservation", "noun", "A2", "Können Sie mir die Buchung per E-Mail bestätigen?", "Rezervasyonu bana e-posta ile onaylayabilir misiniz?", "Can you confirm the booking to me by email?", ["die Reservierung"], ["die Stornierung"]),
    ("die Stornierung, -en", "iptal (rezervasyon)", "cancellation", "noun", "B1", "Bis zu 24 Stunden vorher ist die Stornierung kostenlos.", "24 saat öncesine kadar iptal ücretsizdir.", "Up to 24 hours beforehand cancellation is free of charge.", ["der Rücktritt"], []),
    ("die Stadtrundfahrt, -en", "şehir turu (otobüsle)", "city sightseeing tour", "noun", "A1", "Mit dem Doppeldeckerbus machen wir eine spannende Stadtrundfahrt.", "Çift katlı otobüsle heyecan verici bir şehir turu yapıyoruz.", "With the double-decker bus we do an exciting city tour.", ["die Stadtbesichtigung"], []),
    ("die Sehenswürdigkeit, -en", "tarihi/turistik yer, görülmeye değer yer", "sight / attraction", "noun", "A2", "Das Brandenburger Tor ist eine berühmte Sehenswürdigkeit.", "Brandenburg Kapısı ünlü bir turistik yerdir.", "The Brandenburg Gate is a famous attraction.", ["die Attraktion"], []),
    ("der Stadtplan, ⸚e", "şehir haritası / planı", "city map", "noun", "A1", "Mit dem Stadtplan finden wir mühelos den Weg zum Museum.", "Şehir haritasıyla müzeye giden yolu zahmetsizce buluyoruz.", "With the city map we effortlessly find the way to the museum.", ["der Stadtführer"], []),
    ("der Fremdenführer, - / die Fremdenführerin, -nen", "turist rehberi", "tour guide", "noun", "A2", "Die Fremdenführerin erzählte faszinierende Geschichten.", "Rehber büyüleyici hikayeler anlattı.", "The tour guide told fascinating stories.", ["der Reiseleiter"], []),
    ("das Denkmal, ⸚er", "anıt, abide", "monument / memorial", "noun", "B1", "Auf dem großen Platz steht ein historisches Denkmal.", "Büyük meydanda tarihi bir anıt duruyor.", "On the large square stands a historical monument.", ["das Monument"], []),
    ("das Schloss, ⸚er", "saray, kilit", "palace / castle / lock", "noun", "A2", "Schloss Neuschwanstein lockt jährlich Millionen Touristen an.", "Neuschwanstein Şatosu her yıl milyonlarca turisti çeker.", "Neuschwanstein Castle attracts millions of tourists annually.", ["die Burg", "der Palast"], []),
    ("die Burg, -en", "kale, hisar", "castle / fortress", "noun", "A2", "Auf dem Berg thront eine mittelalterliche Burg.", "Dağın tepesinde bir ortaçağ kalesi yükseliyor.", "A medieval castle towers on the mountain.", ["die Festung"], []),
    ("der Turm, ⸚e", "kule", "tower", "noun", "A1", "Vom hohen Turm aus hat man einen atemberaubenden Ausblick.", "Yüksek kuleden nefes kesici bir manzara görülür.", "From the high tower one has a breathtaking view.", [], []),
    ("die Brücke, -n", "köprü", "bridge", "noun", "A1", "Die alte Brücke führt über den reißenden Fluss.", "Eski köprü coşkun nehrin üzerinden geçiyor.", "The old bridge leads across the torrential river.", [], []),
    ("der Hafen, ⸚", "liman", "harbor / port", "noun", "A2", "Im Hamburger Hafen liegen riesige Containerschiffe vor Anker.", "Hamburg limanında dev konteyner gemileri demirliyor.", "In the port of Hamburg huge container ships are at anchor.", [], []),
    ("das Schiff, -e", "gemi", "ship / boat", "noun", "A1", "Wir machen eine gemütliche Rundfahrt mit dem Schiff.", "Gemiyle keyifli bir tur gezisi yapıyoruz.", "We are taking a leisurely round trip with the ship.", ["der Dampfer", "das Boot"], []),
    ("das Boot, -e", "tekne, kayık", "boat", "noun", "A1", "Auf dem See kann man kleine Ruderboote mieten.", "Gölde küçük kürekli tekneler kiralanabilir.", "On the lake one can rent small rowing boats.", ["der Kahn"], []),
    ("der Kapitän, -e / die Kapitänin, -nen", "kaptan", "captain", "noun", "A2", "Der Kapitän steuerte das Schiff sicher in den Hafen.", "Kaptan gemiyi limana güvenle yönlendirdi.", "The captain steered the ship safely into the port.", ["der Schiffsführer"], []),
    ("das Flugzeug, -e", "uçak", "airplane / plane", "noun", "A1", "Das moderne Flugzeug startet pünktlich in den Urlaub.", "Modern uçak tatile vaktinde kalkıyor.", "The modern airplane takes off on time for the holiday.", ["der Flieger"], []),
    ("der Flug, ⸚e", "uçuş", "flight", "noun", "A1", "Der Flug nach Frankfurt dauert nur eine knappe Stunde.", "Frankfurt'a uçuş sadece bir saate yakın sürüyor.", "The flight to Frankfurt takes just under an hour.", [], []),
    ("die Fluggesellschaft, -en", "hava yolu şirketi", "airline", "noun", "A2", "Welche Fluggesellschaft bietet die günstigsten Flüge an?", "Hangi hava yolu şirketi en uygun uçuşları sunuyor?", "Which airline offers the most affordable flights.", ["die Airline"], []),
    ("der Pilot, -en / die Pilotin, -nen", "pilot", "pilot", "noun", "A2", "Die Pilotin begrüßte die Passagiere freundlich an Bord.", "Pilot yolcuları uçakta dostça selamladı.", "The pilot greeted the passengers friendly on board.", ["der Flugkapitän"], []),
    ("der Passagier, -e / die Passagierin, -nen", "yolcu", "passenger", "noun", "A2", "Alle Passagiere müssen sich vor dem Start anschnallen.", "Tüm yolcular kalkıştan önce kemerlerini bağlamalıdır.", "All passengers must fasten their seatbelts before takeoff.", ["der Fluggast", "der Reisende"], []),
    ("der Gast, ⸚e", "misafir, konuk / müşteri", "guest", "noun", "A1", "Die Gäste waren begeistert vom leckeren Abendessen.", "Konuklar lezzetli akşam yemeğinden çok memnun kaldılar.", "The guests were delighted with the delicious dinner.", ["der Besucher"], ["der Gastgeber"]),
    ("der Gastgeber, - / die Gastgeberin, -nen", "ev sahibi (davet veren)", "host", "noun", "A2", "Die Gastgeber bedankten sich herzlich bei ihren Gästen.", "Ev sahipleri misafirlerine içtenlikle teşekkür etti.", "The hosts thanked their guests warmly.", [], ["der Gast"]),

    # Freizeit, Hobbys & Sport (46-85)
    ("das Hobby, -s", "hobi, uğraş", "hobby", "noun", "A1", "Was sind Ihre persönlichen Hobbys in der Freizeit?", "Boş zamanlarınızdaki kişisel hobileriniz nelerdir?", "What are your personal hobbies in your free time?", ["die Freizeitbeschäftigung"], []),
    ("der Sport, (nur Sg.)", "spor", "sport", "noun", "A1", "Sport hält den Körper fit und gesund.", "Spor vücudu zinde ve sağlıklı tutar.", "Sport keeps the body fit and healthy.", ["die Bewegung"], []),
    ("der Fußball, ⸚e", "futbol, futbol topu", "football / soccer", "noun", "A1", "Fußball ist die beliebteste Sportart in Deutschland.", "Futbol Almanya'daki en popüler spor dalıdır.", "Football is the most popular sport in Germany.", [], []),
    ("der Basketball, ⸚e", "basketbol", "basketball", "noun", "A1", "Wir spielen am Wochenende Basketball im Park.", "Hafta sonu parkta basketbol oynuyoruz.", "We play basketball in the park on the weekend.", [], []),
    ("das Tennis, (nur Sg.)", "tenis", "tennis", "noun", "A1", "Sie spielt seit ihrer Jugend leidenschaftlich Tennis.", "Gençliğinden beri tutkuyla tenis oynuyor.", "She has been playing tennis passionately since her youth.", [], []),
    ("das Fitnessstudio, -s", "spor salonu, fitness salonu", "gym / fitness center", "noun", "A2", "Ich gehe dreimal die Woche ins Fitnessstudio.", "Haftada üç kez spor salonuna gidiyorum.", "I go to the gym three times a week.", ["das Gym"], []),
    ("der Trainer, - / die Trainerin, -nen", "antrenör, koç", "coach / trainer", "noun", "A2", "Der Trainer motiviert die Mannschaft vor dem Endspiel.", "Antrenör final maçından önce takımı motive ediyor.", "The coach motivates the team before the final match.", ["der Coach"], []),
    ("die Mannschaft, -en", "takım, ekip (spor)", "team (sports)", "noun", "A2", "Unsere Mannschaft hat das Finale verdient gewonnen.", "Takımımız finali hak ederek kazandı.", "Our team deservedly won the final.", ["das Team"], []),
    ("das Spiel, -e", "oyun, maç", "game / match", "noun", "A1", "Das spannende Spiel endete unentschieden zwei zu zwei.", "Heyecanlı maç iki iki berabere bitti.", "The exciting game ended in a two-to-two draw.", ["das Match"], []),
    ("der Sieg, -e", "zafer, galibiyet", "victory / win", "noun", "A2", "Die Spieler feierten den verdienten Sieg ausgelassen.", "Oyuncular hak edilen zaferi coşkuyla kutladılar.", "The players celebrated the deserved victory exuberantly.", ["der Triumph"], ["die Niederlage"]),
    ("die Niederlage, -n", "mağlubiyet, yenilgi", "defeat / loss", "noun", "B1", "Nach der bitteren Niederlage schauten alle traurig drein.", "Acı yenilgiden sonra herkes üzgün baktı.", "After the bitter defeat everyone looked sad.", ["der Misserfolg"], ["der Sieg"]),
    ("der Meister, - / die Meisterin, -nen", "şampiyon / usta (zanaat)", "champion / master craftsman", "noun", "A2", "Das Team wurde dieses Jahr verdient deutscher Meister.", "Takım bu yıl hak ederek Almanya şampiyonu oldu.", "The team deservedly became German champions this year.", ["der Champion"], []),
    ("die Meisterschaft, -en", "şampiyona, şampiyonluk", "championship", "noun", "B1", "Die Weltmeisterschaft findet alle vier Jahre statt.", "Dünya Şampiyonası her dört yılda bir düzenlenir.", "The World Championship takes place every four years.", ["das Championat"], []),
    ("das Instrument, -e", "müzik aleti, enstrüman", "instrument (musical)", "noun", "A2", "Spielen Sie eigentlich ein Musikinstrument?", "Aslında bir müzik aleti çalıyor musunuz?", "Do you actually play a musical instrument?", ["das Musikinstrument"], []),
    ("die Gitarre, -n", "gitar", "guitar", "noun", "A1", "Er spielt abends gerne am Lagerfeuer Gitarre.", "Akşamları kamp ateşi başında gitar çalmayı sever.", "He enjoys playing the guitar at the campfire in the evening.", [], []),
    ("das Klavier, -e", "piyano", "piano", "noun", "A1", "Sie nimmt seit drei Jahren klassischen Klavierunterricht.", "Üç yıldır klasik piyano dersi alıyor.", "She has been taking classical piano lessons for three years.", ["der Flügel"], []),
    ("die Geige, -n", "keman", "violin", "noun", "A2", "Die Geige ist ein anspruchsvolles Saiteninstrument.", "Keman zorlu bir yaylı çalgıdır.", "The violin is a demanding string instrument.", ["die Violine"], []),
    ("die Musik, (nur Sg.)", "müzik", "music", "noun", "A1", "Ich höre beim Lernen am liebsten ruhige Musik.", "Ders çalışırken en çok sakin müzik dinlemeyi severim.", "I prefer listening to calm music while studying.", ["die Klänge"], []),
    ("das Lied, -er", "şarkı", "song", "noun", "A1", "Dieses schöne Lied erinnert mich an meine Kindheit.", "Bu güzel şarkı bana çocukluğumu hatırlatıyor.", "This beautiful song reminds me of my childhood.", ["der Song"], []),
    ("der Sänger, - / die Sängerin, -nen", "şarkıcı", "singer", "noun", "A1", "Die berühmte Sängerin gab ein fantastisches Konzert.", "Ünlü şarkıcı harika bir konser verdi.", "The famous singer gave a fantastic concert.", ["der Vokalist"], []),
    ("das Bild, -er", "resim, tablo / fotoğraf", "picture / painting", "noun", "A1", "An der Wand hängt ein farbenfrohes Bild.", "Duvarda rengarenk bir tablo asılı.", "A colorful painting hangs on the wall.", ["das Gemälde"], []),
    ("das Gemälde, -", "tablo, yağlıboya resim", "painting", "noun", "A2", "Das Gemälde von Monet ist von unschätzbarem Wert.", "Monet'nin tablosu paha biçilemez değerdedir.", "The painting by Monet is of priceless value.", ["das Kunstwerk"], []),
    ("die Kunst, ⸚e", "sanat", "art", "noun", "A2", "Moderne Kunst regt die Fantasie der Betrachter an.", "Modern sanat izleyicilerin hayal gücünü harekete geçirir.", "Modern art stimulates the viewers' imagination.", [], []),
    ("der Künstler, - / die Künstlerin, -nen", "sanatçı", "artist", "noun", "A2", "Der Künstler stellt seine Werke in einer Galerie aus.", "Sanatçı eserlerini bir galeride sergiliyor.", "The artist exhibits his works in a gallery.", ["der Kunstschaffende"], []),
    ("die Ausstellung, -en", "sergi", "exhibition", "noun", "A2", "Wir besuchen heute eine interessante Foto-Ausstellung.", "Bugün ilginç bir fotoğraf sergisini ziyaret ediyoruz.", "Today we are visiting an interesting photo exhibition.", ["die Schau"], []),
    ("die Galerie, -n", "sanat galerisi", "art gallery", "noun", "A2", "In der Galerie werden Skulpturen und Bilder gezeigt.", "Galeride heykeller ve tablolar sergileniyor.", "In the gallery sculptures and paintings are shown.", [], []),

    # Natur, Wetter & Umwelt (86-130)
    ("die Jahreszeit, -en", "mevsim", "season", "noun", "A1", "Der Frühling ist für viele die schönste Jahreszeit.", "İlkbahar birçok kişi için en güzel mevsimdir.", "Spring is for many the most beautiful season.", ["die Saison"], []),
    ("der Frühling, -e", "ilkbahar, bahar", "spring", "noun", "A1", "Im Frühling erwacht die Natur zu neuem Leben.", "İlkbaharda doğa yeni bir yaşama uyanır.", "In spring nature awakens to new life.", ["das Frühjahr"], ["der Herbst"]),
    ("der Sommer, -", "yaz", "summer", "noun", "A1", "Im heißen Sommer fahren wir fast jedes Wochenende an den See.", "Sıcak yazın neredeyse her hafta sonu göle gideriz.", "In hot summer we go to the lake almost every weekend.", [], ["der Winter"]),
    ("der Herbst, -e", "sonbahar, güz", "autumn / fall", "noun", "A1", "Im bunten Herbst fallen die Blätter von den Bäumen.", "Renkli sonbaharda ağaçlardan yapraklar düşer.", "In colorful autumn the leaves fall from the trees.", [], ["der Frühling"]),
    ("der Winter, -", "kış", "winter", "noun", "A1", "Im kalten Winter trinke ich am liebsten heißen Tee.", "Soğuk kışın en çok sıcak çay içmeyi severim.", "In cold winter I prefer drinking hot tea.", [], ["der Sommer"]),
    ("das Gewitter, -", "gök gürültülü fırtına", "thunderstorm", "noun", "A2", "Ein plötzliches Gewitter überraschte uns im Wald.", "Ormanda aniden çıkan gök gürültülü bir fırtınaya yakalandık.", "A sudden thunderstorm surprised us in the forest.", ["das Unwetter"], []),
    ("der Blitz, -e", "şimşek, yıldırım", "lightning", "noun", "A2", "Ein heller Blitz erleuchtete den dunklen Nachthimmel.", "Parlak bir şimşek karanlık gece göğünü aydınlattı.", "A bright lightning flash illuminated the dark night sky.", [], []),
    ("der Donner, -", "gök gürültüsü", "thunder", "noun", "A2", "Kurz nach dem Blitz hörte man den lauten Donner.", "Şimşekten kısa süre sonra yüksek sesli gök gürültüsü duyuldu.", "Shortly after the lightning the loud thunder was heard.", [], []),
    ("der Nebel, -", "sis", "fog / mist", "noun", "A2", "Wegen des dichten Nebels sahen die Autofahrer kaum etwas.", "Yoğun sis yüzünden sürücüler neredeyse hiçbir şey göremedi.", "Because of the dense fog the drivers saw hardly anything.", ["der Dunst"], []),
    ("das Eis, (nur Sg.)", "buz / dondurma", "ice / ice cream", "noun", "A1", "Vorsicht auf den Gehwegen, überall liegt glattes Eis!", "Kaldırımlarda dikkat, her yerde kaygan buz var!", "Caution on the sidewalks, there is slippery ice everywhere!", ["das Glatteis"], []),
    ("die Temperatur, -en", "sıcaklık, ısı", "temperature", "noun", "A1", "Die Temperaturen steigen am Nachmittag auf 25 Grad.", "Sıcaklıklar öğleden sonra 25 dereceye yükseliyor.", "Temperatures are rising to 25 degrees in the afternoon.", ["die Wärme"], []),
    ("der Schatten, -", "gölge", "shadow / shade", "noun", "A2", "Im Hochsommer setze ich mich gerne in den kühlen Schatten.", "Yaz ortasında serin gölgeye oturmayı çok severim.", "In midsummer I like sitting in the cool shade.", [], ["die Sonne"]),
    ("die Landschaft, -en", "manzara, kırsal bölge", "landscape / scenery", "noun", "A2", "Die Landschaft in den bayerischen Alpen ist malerisch.", "Bavyera Alpleri'ndeki manzara tablo gibidir.", "The landscape in the Bavarian Alps is picturesque.", ["die Gegend"], []),
    ("die Wüste, -n", "çöl", "desert", "noun", "B1", "In der trockenen Wüste regnet es jahrelang nicht.", "Kurak çölde yıllarca yağmur yağmaz.", "In the arid desert it doesn't rain for years.", [], []),
    ("der Ozean, -e", "okyanus", "ocean", "noun", "A2", "Der Pazifik ist der größte Ozean unserer Erde.", "Pasifik, dünyamızın en büyük okyanusudur.", "The Pacific is the largest ocean on our earth.", ["das Weltmeer"], []),
    ("das Ufer, -", "kıyı, sahil (nehir/göl)", "bank / shore", "noun", "A2", "Wir spazieren am grünen Ufer des Rheins entlang.", "Ren Nehri'nin yeşil kıyısı boyunca yürüyoruz.", "We stroll along the green bank of the Rhine.", ["der Strand", "die Küste"], []),
    ("die Küste, -n", "deniz kıyısı, sahil", "coast / coastline", "noun", "A2", "Die deutsche Nordseeküste ist bekannt für das Wattenmeer.", "Alman Kuzey Denizi sahili sığ deniz kıyılarıyla tanınır.", "The German North Sea coast is known for the Wadden Sea.", ["das Ufer"], []),
    ("die Luft, (nur Sg.)", "hava, atmosfer", "air", "noun", "A1", "Nach dem Regen ist die Luft herrlich rein.", "Yağmurdan sonra hava harika derecede temizdir.", "After the rain the air is wonderfully clean.", ["der Sauerstoff"], []),
    ("das Feuer, -", "ateş, yangın", "fire", "noun", "A1", "Im offenen Kamin knistert ein wärmendes Feuer.", "Açık şöminede ısıtan bir ateş çıtırdıyor.", "In the open fireplace a warming fire is crackling.", ["der Brand"], ["das Wasser"]),
    ("die Pflanze, -n", "bitki", "plant", "noun", "A1", "Vergiss nicht, Zimmerpflanzen regelmäßig zu wässern!", "Oda bitkilerini düzenli sulamayı unutma!", "Don't forget to water indoor plants regularly!", ["das Gewächs"], []),

    # Werkzeuge & Alltagsgegenstände (131-160)
    ("das Werkzeug, -e", "alet, takım, el aleti", "tool", "noun", "A2", "Für die Autoreparatur braucht man passendes Werkzeug.", "Araba tamiri için uygun aletlere ihtiyaç vardır.", "For the car repair one needs suitable tools.", ["das Gerät"], []),
    ("der Hammer, ⸚", "çekiç", "hammer", "noun", "A2", "Mit dem schweren Hammer schlägt er den Nagel in die Wand.", "Ağır çekiçle çiviyi duvara çakıyor.", "With the heavy hammer he pounds the nail into the wall.", [], []),
    ("der Nagel, ⸚", "çivi / tırnak", "nail", "noun", "A2", "Ich brauche einen Nagel, um das Bild aufzuhängen.", "Resmi asmak için bir çiviye ihtiyacım var.", "I need a nail to hang up the picture.", [], []),
    ("die Schraube, -n", "vida", "screw", "noun", "A2", "Zieh die Schraube am Schrank bitte fest an!", "Dolaptaki vidayı lütfen iyice sık!", "Please tighten the screw on the cupboard firmly!", [], []),
    ("die Schere, -n", "makas", "scissors", "noun", "A1", "Mit der Schere schneidet das Kind bunte Papiersterne.", "Çocuk makasla renkli kağıt yıldızlar kesiyor.", "With the scissors the child cuts colorful paper stars.", [], []),
    ("der Klebstoff, -e", "yapıştırıcı", "glue", "noun", "A2", "Der Klebstoff hält Holz und Papier bombenfest.", "Yapıştırıcı tahta ve kağıdı çok sağlam tutuyor.", "The glue holds wood and paper rock solid.", ["der Leim"], []),
    ("das Seil, -e", "ip, halat", "rope", "noun", "A2", "Beim Bergsteigen sichert er sich mit einem starken Seil.", "Dağa tırmanırken kendini güçlü bir halatla emniyete alıyor.", "When mountain climbing he secures himself with a strong rope.", ["die Leine"], []),
    ("die Kiste, -n", "sandık, kasa, koli", "box / crate", "noun", "A1", "Wir packen die Bücher in stabile Kisten für den Umzug.", "Kitapları taşınma için sağlam kolilere paketliyoruz.", "We pack the books into sturdy crates for the move.", ["der Kasten"], []),
    ("die Schachtel, -n", "kutu (küçük/karton)", "box / carton", "noun", "A2", "Er schenkte ihr eine hübsche Schachtel Pralinen.", "Ona güzel bir kutu çikolata hediye etti.", "He gave her a pretty box of chocolates.", ["die Dose"], []),
    ("der Eimer, -", "kova", "bucket / pail", "noun", "A1", "Füll bitte den Eimer mit lauwarmem Putzwasser!", "Kovayı lütfen ılık temizlik suyuyla doldur!", "Please fill the bucket with lukewarm cleaning water!", ["der Kübel"], []),
    ("der Besen, -", "süpürge", "broom", "noun", "A1", "Mit dem Besen kehrt er den Schmutz vom Hof.", "Süpürgeyle avludaki kiri süpürüyor.", "With the broom he sweeps the dirt from the yard.", [], []),
    ("der Lappen, -", "bez, temizlik bezi", "rag / cloth", "noun", "A1", "Wisch den Tisch bitte mit einem feuchten Lappen ab!", "Masayı lütfen nemli bir bezle sil!", "Please wipe the table with a damp cloth!", ["das Tuch"], [])
]

print(f"Loaded {len(FINAL_BOOST_2000)} items into final_boost_2000.py")
