# scripts/vocab_sources/nouns_part2.py
"""
Part 2 of Nouns: ~350 nouns covering:
Essen & Trinken, Einkaufen, Geld & Finanzen, Kleidung & Mode, Verkehr & Reisen, Natur & Wetter.
Format: (de, tr, en, pos, level, ex, ex_tr, ex_en, syns, ants)
"""

NOUNS_P2 = [
    # --- Essen & Trinken (Food & Beverages) ---
    ("das Essen (Sg.)", "yemek, yiyecek", "food / meal", "noun", "A1", "Das Essen schmeckt hervorragend.", "Yemek olağanüstü lezzetli.", "The food tastes outstanding.", ["die Speise", "das Gericht"], []),
    ("das Gericht, -e", "yemek (öğün/tabak), mahkeme", "dish / court", "noun", "A2", "Welches Gericht empfehlen Sie?", "Hangi yemeği tavsiye edersiniz?", "Which dish do you recommend?", ["die Speise"], []),
    ("die Mahlzeit, -en", "öğün", "meal", "noun", "A2", "Drei Mahlzeiten am Tag sind gesund.", "Günde üç öğün sağlıklıdır.", "Three meals a day are healthy.", [], []),
    ("das Frühstück, -e", "kahvaltı", "breakfast", "noun", "A1", "Zum Frühstück esse ich Müsli.", "Kahvaltıda müsli yerim.", "For breakfast I eat muesli.", [], []),
    ("das Mittagessen, -", "öğle yemeği", "lunch", "noun", "A1", "Um 12 Uhr gibt es Mittagessen.", "Saat 12'de öğle yemeği var.", "At 12 o'clock there is lunch.", [], []),
    ("das Abendessen, -", "akşam yemeği", "dinner / supper", "noun", "A1", "Wir essen Brot zum Abendessen.", "Akşam yemeğinde ekmek yeriz.", "We eat bread for dinner.", ["das Abendbrot"], []),
    ("das Brot, -e", "ekmek", "bread", "noun", "A1", "Ich kaufe frisches Vollkornbrot.", "Taze tam buğday ekmeği alıyorum.", "I buy fresh whole grain bread.", [], []),
    ("das Brötchen, -", "küçük ekmek, sandviç ekmeği", "bread roll", "noun", "A1", "Morgens hole ich frische Brötchen.", "Sabahları taze sandviç ekmekleri alırım.", "In the morning I fetch fresh rolls.", ["die Semmel"], []),
    ("die Butter (Sg.)", "tereyağı", "butter", "noun", "A1", "Streich bitte Butter aufs Brot!", "Ekmeğe lütfen tereyağı sür!", "Please spread butter on the bread!", [], []),
    ("der Käse, -", "peynir", "cheese", "noun", "A1", "Ich mag alten Gouda-Käse.", "Eski Gouda peynirini severim.", "I like mature Gouda cheese.", [], []),
    ("die Wurst, -¨e", "sosis, sucuk", "sausage", "noun", "A1", "Die Wurst ist würzig.", "Sosis baharatlıdır.", "The sausage is spicy.", [], []),
    ("das Fleisch (Sg.)", "et", "meat", "noun", "A1", "Ich esse selten rotes Fleisch.", "Nadiren kırmızı et yerim.", "I rarely eat red meat.", [], ["das Gemüse"]),
    ("das Rindfleisch (Sg.)", "sığır eti", "beef", "noun", "A2", "Das Rindfleisch ist zart gebraten.", "Sığır eti yumuşacık kızartılmış.", "The beef is tenderly roasted.", [], []),
    ("das Hähnchen, -", "tavuk eti", "chicken", "noun", "A1", "Wir bestellen gebratenes Hähnchen.", "Kızarmış tavuk sipariş ediyoruz.", "We order roast chicken.", ["das Huhn"], []),
    ("der Fisch, -e", "balık", "fish", "noun", "A1", "Am Freitag gibt es frischen Fisch.", "Cuma günü taze balık var.", "On Friday there is fresh fish.", [], []),
    ("das Ei, -er", "yumurta", "egg", "noun", "A1", "Ich koche mir zwei weiche Eier.", "Kendime iki rafadan yumurta pişiriyorum.", "I boil myself two soft eggs.", [], []),
    ("das Gemüse, -", "sebze", "vegetables", "noun", "A1", "Frisches Gemüse ist reich an Vitaminen.", "Taze sebze vitamin açısından zengindir.", "Fresh vegetables are rich in vitamins.", [], ["das Obst"]),
    ("die Kartoffel, -n", "patates", "potato", "noun", "A1", "In Deutschland isst man viele Kartoffeln.", "Almanya'da çok patates yenir.", "In Germany people eat a lot of potatoes.", ["der Erdapfel"], []),
    ("die Tomate, -n", "domates", "tomato", "noun", "A1", "Die Tomaten im Salat sind süß.", "Salatadaki domatesler tatlı.", "The tomatoes in the salad are sweet.", [], []),
    ("die Gurke, -n", "salatalık", "cucumber", "noun", "A1", "Gurken enthalten viel Wasser.", "Salatalık çok su içerir.", "Cucumbers contain a lot of water.", [], []),
    ("die Zwiebel, -n", "soğan", "onion", "noun", "A1", "Ich schneide Zwiebeln für die Soße.", "Sos için soğan doğruyorum.", "I chop onions for the sauce.", [], []),
    ("der Knoblauch (Sg.)", "sarımsak", "garlic", "noun", "A2", "Knoblauch gibt dem Gericht Aroma.", "Sarımsak yemeğe aroma verir.", "Garlic gives the dish aroma.", [], []),
    ("der Salat, -e", "salata, marul", "salad / lettuce", "noun", "A1", "Wir essen einen gemischten Salat.", "Karışık salata yiyoruz.", "We are eating a mixed salad.", [], []),
    ("der Reis (Sg.)", "pirinç, pilav", "rice", "noun", "A1", "Als Beilage gibt es Reis.", "Garnitür olarak pilav var.", "As a side dish there is rice.", [], []),
    ("die Nudeln (Pl.)", "makarna", "pasta / noodles", "noun", "A1", "Kinder essen am liebsten Nudeln mit Soße.", "Çocuklar en çok soslu makarna yemeyi sever.", "Children prefer eating noodles with sauce.", ["die Pasta"], []),
    ("die Suppe, -n", "çorba", "soup", "noun", "A1", "Im Winter wärmt eine heiße Gemüsesuppe.", "Kışın sıcak bir sebze çorbası iç ısıtır.", "In winter a hot vegetable soup warms you up.", [], []),
    ("das Obst (Sg.)", "meyve", "fruit", "noun", "A1", "Obst liefert wichtige Vitamine.", "Meyve önemli vitaminler sağlar.", "Fruit provides important vitamins.", ["die Früchte"], ["das Gemüse"]),
    ("der Apfel, -¨", "elma", "apple", "noun", "A1", "Ein Apfel am Tag hält gesund.", "Günde bir elma insanı sağlıklı tutar.", "An apple a day keeps you healthy.", [], []),
    ("die Banane, -n", "muz", "banana", "noun", "A1", "Affen fressen gerne Bananen.", "Maymunlar muz yemeyi sever.", "Monkeys like eating bananas.", [], []),
    ("die Orange, -n", "portakal", "orange", "noun", "A1", "Frische Orangen schmecken saftig.", "Taze portakallar sulu suludur.", "Fresh oranges taste juicy.", ["die Apfelsine"], []),
    ("die Zitrone, -n", "limon", "lemon", "noun", "A1", "Tee mit frischer Zitrone schmeckt erfrischend.", "Taze limonlu çay ferahlatıcıdır.", "Tea with fresh lemon tastes refreshing.", [], []),
    ("die Erdbeere, -n", "çilek", "strawberry", "noun", "A1", "Im Juni gibt es süße Erdbeeren.", "Haziranda tatlı çilekler olur.", "In June there are sweet strawberries.", [], []),
    ("die Kirsche, -n", "kiraz", "cherry", "noun", "A2", "Die Kirschen am Baum sind reif.", "Ağaçtaki kirazlar olgunlaştı.", "The cherries on the tree are ripe.", [], []),
    ("die Traube, -n", "üzüm", "grape", "noun", "A2", "Blaue Trauben schmecken süß.", "Siyah üzümler çok tatlıdır.", "Blue grapes taste sweet.", ["die Weintraube"], []),
    ("die Nuss, -¨e", "fındık, ceviz, kuruyemiş", "nut", "noun", "A2", "Nüsse sind gesund für das Gehirn.", "Kuruyemişler beyin için sağlıklıdır.", "Nuts are healthy for the brain.", [], []),
    ("der Kuchen, -", "pasta, kek", "cake", "noun", "A1", "Zum Kaffee essen wir Kuchen.", "Kahvenin yanında pasta yiyoruz.", "With coffee we eat cake.", ["die Torte"], []),
    ("die Torte, -n", "yaş pasta", "tart / cake", "noun", "A1", "Die Geburtstagstorte hatte Kerzen.", "Doğum günü pastasında mumlar vardı.", "The birthday cake had candles.", ["der Kuchen"], []),
    ("die Schokolade, -n", "çikolata", "chocolate", "noun", "A1", "Dunkle Schokolade ist mein Favorit.", "Bitter çikolata benim favorimdir.", "Dark chocolate is my favorite.", [], []),
    ("das Eis (Sg.)", "dondurma, buz", "ice cream / ice", "noun", "A1", "Im Sommer essen die Kinder Eis.", "Yazın çocuklar dondurma yer.", "In the summer children eat ice cream.", [], []),
    ("der Zucker (Sg.)", "şeker", "sugar", "noun", "A1", "Ich trinke Kaffee ohne Zucker.", "Kahveyi şekersiz içerim.", "I drink coffee without sugar.", [], ["das Salz"]),
    ("das Salz (Sg.)", "tuz", "salt", "noun", "A1", "Reich mir bitte das Salz!", "Tuzu bana uzat lütfen!", "Pass me the salt, please!", [], ["der Zucker"]),
    ("der Pfeffer (Sg.)", "karabiber", "pepper", "noun", "A1", "Die Suppe braucht noch etwas Pfeffer.", "Çorbaya biraz daha karabiber lazım.", "The soup still needs some pepper.", [], []),
    ("das Öl, -e", "yağ (sıvı)", "oil", "noun", "A1", "Wir kochen am liebsten mit Olivenöl.", "En çok zeytinyağıyla yemek pişirmeyi severiz.", "We prefer cooking with olive oil.", [], []),
    ("der Essig, -e", "sirke", "vinegar", "noun", "A2", "Essig und Öl gehören in jedes Dressing.", "Sirke ve yağ her salata sosunda bulunur.", "Vinegar and oil belong in every dressing.", [], []),
    ("das Wasser (Sg.)", "su", "water", "noun", "A1", "Trinken Sie bitte viel stilles Wasser.", "Lütfen bol bol durgun su içiniz.", "Please drink plenty of still water.", [], []),
    ("der Tee, -s", "çay", "tea", "noun", "A1", "Ein heißer Pfefferminztee tut gut.", "Sıcak bir nane çayı iyi gelir.", "A hot peppermint tea does you good.", [], []),
    ("der Kaffee, -s", "kahve", "coffee", "noun", "A1", "Morgens brauche ich eine Tasse Kaffee.", "Sabahları bir fincan kahveye ihtiyacım olur.", "In the morning I need a cup of coffee.", [], []),
    ("die Milch (Sg.)", "süt", "milk", "noun", "A1", "Kinder trinken morgens warme Milch.", "Çocuklar sabahları ılık süt içer.", "Children drink warm milk in the morning.", [], []),
    ("der Saft, -¨e", "meyve suyu", "juice", "noun", "A1", "Möchtest du ein Glas Apfelsaft?", "Bir bardak elma suyu ister misin?", "Would you like a glass of apple juice?", [], []),
    ("das Bier, -e", "bira", "beer", "noun", "A1", "In Bayern trinkt man gerne Bier.", "Bavyera'da bira içmeyi çok severler.", "In Bavaria people like drinking beer.", [], []),
    ("der Wein, -e", "şarap", "wine", "noun", "A1", "Zum Fisch passt ein trockener Weißwein.", "Balığın yanına sek beyaz şarap uyar.", "A dry white wine goes well with fish.", [], []),
    ("das Restaurant, -s", "restoran", "restaurant", "noun", "A1", "Wir gehen heute ins Restaurant essen.", "Bugün restoranda yemek yiyeceğiz.", "We are going to eat at a restaurant today.", ["das Gasthaus"], []),
    ("die Speisekarte, -n", "menü kartı", "menu", "noun", "A1", "Bringen Sie uns bitte die Speisekarte.", "Bize lütfen menüyü getirin.", "Please bring us the menu.", ["das Menü"], []),
    ("die Rechnung, -en", "fatura, hesap", "bill / invoice", "noun", "A1", "Herr Ober, die Rechnung bitte!", "Garson bey, hesap lütfen!", "Waiter, the bill please!", [], []),
    ("das Trinkgeld, -er", "bahşiş", "tip (money)", "noun", "A2", "Wir haben dem Kellner gutes Trinkgeld gegeben.", "Garsona iyi bahşiş verdik.", "We gave the waiter a good tip.", [], []),
    ("der Kellner, -", "garson (erkek)", "waiter", "noun", "A1", "Der Kellner bringt das Essen schnell.", "Garson yemeği çabucak getiriyor.", "The waiter brings the food quickly.", ["die Bedienung"], []),
    ("die Kellnerin, -nen", "garson (kadın)", "waitress", "noun", "A1", "Die Kellnerin lächelt freundlich.", "Garson kadın güler yüzle gülümsüyor.", "The waitress smiles friendly.", [], []),

    # --- Einkaufen & Finanzen (Shopping & Finance) ---
    ("der Supermarkt, -¨e", "süpermarket", "supermarket", "noun", "A1", "Der Supermarkt schließt um 20 Uhr.", "Süpermarket saat 20'de kapanıyor.", "The supermarket closes at 8 pm.", [], []),
    ("das Geschäft, -e", "dükkan, mağaza, iş", "shop / store / business", "noun", "A1", "In der Fußgängerzone gibt es viele Geschäfte.", "Yaya bölgesinde pek çok mağaza var.", "In the pedestrian zone there are many shops.", ["der Laden"], []),
    ("der Laden, -¨", "dükkan, mağaza", "store / shop", "noun", "A1", "Der Bäckerladen an der Ecke hat leckere Brötchen.", "Köşedeki fırın dükkanında lezzetli sandviç ekmekleri var.", "The bakery store on the corner has tasty rolls.", ["das Geschäft"], []),
    ("das Kaufhaus, -¨er", "büyük mağaza, AVM", "department store", "noun", "A1", "Wir kaufen im Kaufhaus Kleidung ein.", "Büyük mağazadan kıyafet alışverişi yapıyoruz.", "We buy clothes in the department store.", ["das Warenhaus"], []),
    ("der Markt, -¨e", "pazar", "market", "noun", "A1", "Samstags gehen wir auf den Wochenmarkt.", "Cumartesileri haftalık semt pazarına gideriz.", "On Saturdays we go to the weekly market.", [], []),
    ("die Bäckerei, -en", "fırın", "bakery", "noun", "A1", "Die Bäckerei duftet nach frischem Brot.", "Fırın mis gibi taze ekmek kokuyor.", "The bakery smells of fresh bread.", [], []),
    ("die Metzgerei, -en", "kasap", "butcher shop", "noun", "A1", "In der Metzgerei kaufe ich Schinken.", "Kasaptan jambon alıyorum.", "In the butcher shop I buy ham.", ["die Fleischerei"], []),
    ("die Kasse, -n", "kasa (ödeme yeri)", "checkout / cash register", "noun", "A1", "Zahlen Sie bitte an der Kasse.", "Lütfen kasada ödeyiniz.", "Please pay at the cash register.", [], []),
    ("die Schlange, -n", "sıra, kuyruk, yılan", "queue / line / snake", "noun", "A2", "An der Kasse gab es eine lange Schlange.", "Kasada uzun bir kuyruk vardı.", "At the checkout there was a long queue.", [], []),
    ("der Einkaufswagen, -", "alışveriş arabası", "shopping cart / trolley", "noun", "A1", "Nehmen Sie einen Einkaufswagen mit.", "Yanınıza bir alışveriş arabası alınız.", "Take a shopping trolley along.", [], []),
    ("die Tasche, -n", "çanta, cep", "bag / pocket", "noun", "A1", "Meine Tasche ist voll mit Einkäufen.", "Çantam alışverişlerle dolu.", "My bag is full of groceries.", [], []),
    ("die Tüte, -n", "poşet", "plastic/paper bag", "noun", "A1", "Brauchen Sie eine Tüte für die Einkäufe?", "Alışverişler için poşet ister misiniz?", "Do you need a bag for the purchases?", ["der Beutel"], []),
    ("der Preis, -e", "fiyat, ödül", "price / prize", "noun", "A1", "Der Preis ist sehr günstig.", "Fiyat çok uygun.", "The price is very reasonable.", [], []),
    ("das Angebot, -e", "teklif, indirimli ürün", "offer / special deal", "noun", "A1", "Kaffee ist diese Woche im Angebot.", "Kahve bu hafta indirimli teklifte.", "Coffee is on special offer this week.", ["das Schnäppchen"], []),
    ("der Rabatt, -e", "indirim", "discount", "noun", "A2", "Auf Winterjacken gibt es 30% Rabatt.", "Kışlık ceketlerde %30 indirim var.", "There is a 30% discount on winter jackets.", ["der Preisnachlass"], []),
    ("der Gutschein, -e", "hediye çeki, kupon", "voucher / coupon", "noun", "A2", "Ich habe einen Gutschein über 50 Euro bekommen.", "Bana 50 Euro tutarında hediye çeki hediye edildi.", "I received a 50 euro voucher.", [], []),
    ("die Quittung, -en", "makbuz, fiş", "receipt", "noun", "A2", "Bewahren Sie die Quittung für den Umtausch auf.", "Değişim için makbuzu saklayınız.", "Keep the receipt for an exchange.", ["der Beleg", "der Kassenbon"], []),
    ("das Geld (Sg.)", "para", "money", "noun", "A1", "Ich habe kein Bargeld dabei.", "Yanımda hiç nakit para yok.", "I have no cash with me.", [], []),
    ("das Bargeld (Sg.)", "nakit para", "cash", "noun", "A1", "Hier kann man nur mit Bargeld zahlen.", "Burada sadece nakit para ile ödenebilir.", "Here one can only pay with cash.", [], ["die Karte"]),
    ("die Münze, -n", "madeni para", "coin", "noun", "A2", "Ich habe ein paar Münzen für den Automaten.", "Otomat için birkaç madeni param var.", "I have a few coins for the vending machine.", ["das Kleingeld"], ["der Geldschein"]),
    ("der Schein, -e", "banknot, belge", "banknote / bill / certificate", "noun", "A2", "Haben Sie einen Zehn-Euro-Schein?", "On euroluk bir banknotunuz var mı?", "Do you have a ten-euro bill?", ["die Banknote"], ["die Münze"]),
    ("das Konto, Konten", "banka hesabı", "bank account", "noun", "A1", "Ich möchte ein Girokonto eröffnen.", "Bir vadesiz hesap açmak istiyorum.", "I would like to open a checking account.", [], []),
    ("die Bank, -en", "banka", "bank", "noun", "A1", "Die Bank hat bis 16 Uhr geöffnet.", "Banka saat 16'ya kadar açık.", "The bank is open until 4 pm.", [], []),
    ("der Geldautomat, -en", "bankamatik, ATM", "ATM / cash machine", "noun", "A1", "Am Geldautomaten hebe ich Geld ab.", "Bankamatikten para çekiyorum.", "I withdraw money at the ATM.", [], []),
    ("die Kreditkarte, -n", "kredi kartı", "credit card", "noun", "A1", "Kann ich mit Kreditkarte zahlen?", "Kredi kartıyla ödeyebilir miyim?", "Can I pay by credit card?", [], []),
    ("die Schulden (Pl.)", "borçlar", "debts", "noun", "B1", "Er hat alle Schulden pünktlich bezahlt.", "Tüm borçlarını vaktinde ödedi.", "He paid all debts on time.", [], []),
    ("der Kredit, -e", "kredi", "loan / credit", "noun", "B1", "Die Familie nahm einen Kredit für das Haus auf.", "Aile ev için bir kredi çekti.", "The family took out a loan for the house.", ["das Darlehen"], []),
    ("die Zinsen (Pl.)", "faizler", "interest (finance)", "noun", "B1", "Die Zinsen für den Kredit sind niedrig.", "Kredinin faizleri düşüktür.", "The interest rates on the loan are low.", [], []),

    # --- Kleidung & Mode (Clothing & Fashion) ---
    ("die Kleidung (Sg.)", "kıyafet, giysi", "clothes / clothing", "noun", "A1", "Zieh bequeme Kleidung an!", "Rahat kıyafetler giy!", "Put on comfortable clothing!", ["die Klamotten"], []),
    ("die Jacke, -n", "ceket", "jacket", "noun", "A1", "Nimm deine warme Jacke mit.", "Sıcak ceketini yanına al.", "Take your warm jacket with you.", [], []),
    ("der Mantel, -¨", "palto, kaban", "coat", "noun", "A1", "Im Winter trage ich einen dicken Mantel.", "Kışın kalın bir palto giyerim.", "In winter I wear a thick coat.", [], []),
    ("die Hose, -n", "pantolon", "trousers / pants", "noun", "A1", "Die schwarze Hose passt mir gut.", "Siyah pantolon bana tam oturuyor.", "The black trousers fit me well.", [], []),
    ("die Jeans, -", "kot pantolon", "jeans", "noun", "A1", "Er trägt am liebsten blaue Jeans.", "En çok mavi kot pantolon giymeyi sever.", "He prefers wearing blue jeans.", [], []),
    ("das Hemd, -en", "gömlek (erkek)", "shirt", "noun", "A1", "Zum Anzug gehört ein weißes Hemd.", "Takım elbisenin yanına beyaz bir gömlek gider.", "A white shirt belongs with the suit.", [], ["die Bluse"]),
    ("die Bluse, -n", "bluz (kadın)", "blouse", "noun", "A1", "Sie trägt eine elegante Seidenbluse.", "Şık bir ipek bluz giyiyor.", "She is wearing an elegant silk blouse.", [], ["das Hemd"]),
    ("das T-Shirt, -s", "tişört", "T-shirt", "noun", "A1", "Im Sommer trage ich bunte T-Shirts.", "Yazın renkli tişörtler giyerim.", "In summer I wear colorful T-shirts.", [], []),
    ("der Pullover, -", "kazak", "sweater / pullover", "noun", "A1", "Der Pullover aus Wolle wärmt gut.", "Yün kazak iyi ısıtır.", "The woolen pullover warms well.", ["der Pulli"], []),
    ("das Kleid, -er", "elbise (kadın)", "dress", "noun", "A1", "Das rote Kleid steht ihr fabelhaft.", "Kırmızı elbise ona harika yakışıyor.", "The red dress suits her wonderfully.", [], []),
    ("der Rock, -¨e", "etek", "skirt", "noun", "A1", "Sie trägt einen langen Sommerrock.", "Uzun bir yazlık etek giyiyor.", "She is wearing a long summer skirt.", [], []),
    ("der Anzug, -¨e", "takım elbise", "suit", "noun", "A2", "Zur Hochzeit trug er einen dunklen Anzug.", "Düğüne koyu renkli bir takım elbise giydi.", "For the wedding he wore a dark suit.", [], []),
    ("die Krawatte, -n", "kravat", "tie / necktie", "noun", "A2", "Er bindet seine Krawatte sorgfältig.", "Kravatını özenle bağlıyor.", "He ties his necktie carefully.", ["der Schlips"], []),
    ("die Schuhe (Pl.)", "ayakkabılar", "shoes", "noun", "A1", "Zieh die Schuhe vor der Tür aus!", "Kapının önünde ayakkabıları çıkar!", "Take off your shoes outside the door!", [], []),
    ("der Stiefel, -", "çizme, bot", "boot", "noun", "A2", "Bei Schnee brauche ich warme Stiefel.", "Karda sıcak botlara ihtiyacım var.", "In snow I need warm boots.", [], []),
    ("die Socke, -n", "çorap", "sock", "noun", "A1", "Wollsocken halten die Füße warm.", "Yün çoraplar ayakları sıcak tutar.", "Woolen socks keep feet warm.", ["der Strumpf"], []),
    ("der Hut, -¨e", "şapka (fötr)", "hat", "noun", "A1", "Er zog höflich seinen Hut.", "Kibarca şapkasını çıkardı.", "He politely took off his hat.", [], []),
    ("die Mütze, -n", "bere", "beanie / cap", "noun", "A1", "Zieh eine warme Mütze auf!", "Sıcak bir bere tak!", "Put on a warm beanie!", [], []),
    ("der Schal, -s", "atkı, şal", "scarf", "noun", "A1", "Ein dicker Schal schützt vor Kälte.", "Kalın bir atkı soğuktan korur.", "A thick scarf protects against the cold.", [], []),
    ("die Handschuhe (Pl.)", "eldivenler", "gloves", "noun", "A1", "Vergiss im Winter die Handschuhe nicht!", "Kışın eldivenleri unutma!", "Don't forget the gloves in winter!", [], []),
    ("der Gürtel, -", "kemer", "belt", "noun", "A2", "Die Hose ist zu weit ohne Gürtel.", "Pantolon kemersiz çok bol geliyor.", "The trousers are too wide without a belt.", [], []),
    ("der Regenschirm, -e", "şemsiye", "umbrella", "noun", "A1", "Nimm einen Regenschirm mit, es regnet.", "Yanına bir şemsiye al, yağmur yağıyor.", "Take an umbrella along, it is raining.", [], []),
    ("die Brille, -n", "gözlük", "glasses / spectacles", "noun", "A1", "Ohne Brille kann ich nicht lesen.", "Gözlüksüz okuyamıyorum.", "Without glasses I cannot read.", [], []),
    ("die Sonnenbrille, -n", "güneş gözlüğü", "sunglasses", "noun", "A1", "Am Strand trage ich eine Sonnenbrille.", "Kumsalda güneş gözlüğü takarım.", "At the beach I wear sunglasses.", [], []),
    ("die Uhr, -en", "saat (kol/duvar)", "watch / clock", "noun", "A1", "Meine Uhr geht ganz genau.", "Kol saatim tam tamına doğru işliyor.", "My watch runs very accurately.", [], []),
    ("der Schmuck (Sg.)", "takı, ziynet", "jewelry", "noun", "A2", "Sie liebt echten Schmuck aus Silber.", "Gümüşten hakiki takıları çok sever.", "She loves real silver jewelry.", [], []),
    ("der Ring, -e", "yüzük, halka", "ring", "noun", "A2", "Der goldene Ehering glänzt.", "Altın alyans parlıyor.", "The golden wedding ring shines.", [], []),

    # --- Verkehr & Reisen (Traffic & Travel) ---
    ("der Verkehr (Sg.)", "trafik, ulaşım", "traffic / transport", "noun", "A1", "Im Berufsverkehr gibt es viele Staus.", "İş çıkışı trafiğinde çok sıkışıklık olur.", "In rush-hour traffic there are many jams.", [], []),
    ("der Stau, -s", "trafik sıkışıklığı", "traffic jam", "noun", "A1", "Wir standen eine Stunde im Stau.", "Trafik sıkışıklığında bir saat bekledik.", "We stood in a traffic jam for an hour.", [], []),
    ("die Straße, -n", "cadde, sokak", "street / road", "noun", "A1", "Die Straße ist für Autos gesperrt.", "Cadde arabalara kapatılmıştır.", "The street is blocked for cars.", [], []),
    ("die Autobahn, -en", "otoban, otoyol", "highway / motorway", "noun", "A1", "Auf der Autobahn gibt es keine Ampeln.", "Otoyolda trafik ışığı bulunmaz.", "On the motorway there are no traffic lights.", [], []),
    ("die Kreuzung, -en", "dörtyol, kavşak", "intersection / junction", "noun", "A2", "Biegen Sie an der nächsten Kreuzung ab.", "Sonraki kavşaktan dönünüz.", "Turn at the next intersection.", [], []),
    ("die Ampel, -n", "trafik ışığı", "traffic light", "noun", "A1", "Bei Rot an der Ampel muss man anhalten.", "Trafik ışığında kırmızı yandığında durulmalıdır.", "At red at the traffic light one must stop.", [], []),
    ("der Gehweg, -e", "yaya kaldırımı", "sidewalk / pavement", "noun", "A2", "Fußgänger gehen auf dem Gehweg.", "Yayalar kaldırımda yürür.", "Pedestrians walk on the pavement.", ["das Trottoir"], []),
    ("der Fußgänger, -", "yaya", "pedestrian", "noun", "A2", "Autofahrer müssen auf Fußgänger achten.", "Sürücüler yayalara dikkat etmelidir.", "Drivers must watch out for pedestrians.", [], []),
    ("der Zebrastreifen, -", "yaya geçidi", "crosswalk / zebra crossing", "noun", "A2", "Am Zebrastreifen haben Fußgänger Vorrang.", "Yaya geçidinde geçiş üstünlüğü yayalarındır.", "At the zebra crossing pedestrians have priority.", ["der Fußgängerüberweg"], []),
    ("das Auto, -s", "otomobil, araba", "car / automobile", "noun", "A1", "Er fährt ein modernes Elektroauto.", "Modern bir elektrikli otomobil kullanıyor.", "He drives a modern electric car.", ["der Wagen", "der PKW"], []),
    ("der Bus, -se", "otobüs", "bus", "noun", "A1", "Der Bus kommt alle zehn Minuten.", "Otobüs on dakikada bir geliyor.", "The bus comes every ten minutes.", [], []),
    ("die Haltestelle, -n", "durak (otobüs/tramvay)", "bus/tram stop", "noun", "A1", "Wir warten an der Bushaltestelle.", "Otobüs durağında bekliyoruz.", "We are waiting at the bus stop.", [], []),
    ("die Bahn, -en", "tren, demiryolu", "railway / train", "noun", "A1", "Ich fahre lieber mit der Bahn als mit dem Auto.", "Arabayla gitmektense trenle gitmeyi tercih ederim.", "I prefer traveling by train to driving.", ["der Zug"], []),
    ("der Zug, -¨e", "tren", "train", "noun", "A1", "Der Zug hat zwanzig Minuten Verspätung.", "Trenin yirmi dakika gecikmesi var.", "The train is twenty minutes late.", ["die Bahn"], []),
    ("der Bahnhof, -¨e", "tren garı, istasyon", "train station", "noun", "A1", "Der Zug fährt vom Hauptbahnhof ab.", "Tren merkez gardan hareket ediyor.", "The train departs from the main station.", [], []),
    ("das Gleis, -e", "peron, demiryolu hattı", "platform track / platform", "noun", "A1", "Der Zug nach München fährt von Gleis 4.", "Münih treni 4. perondan kalkıyor.", "The train to Munich departs from track 4.", ["der Bahnsteig"], []),
    ("der Bahnsteig, -e", "peron (yolcu platformu)", "platform", "noun", "A1", "Bitte treten Sie von der Bahnsteigkante zurück!", "Lütfen peron kenarından geriye çekiliniz!", "Please stand back from the platform edge!", ["das Gleis"], []),
    ("die U-Bahn, -en", "metro (yeraltı)", "underground / subway", "noun", "A1", "Die U-Bahn fährt im dichten Takt.", "Metro sık aralıklarla çalışıyor.", "The subway runs at frequent intervals.", [], []),
    ("die S-Bahn, -en", "banliyö treni", "suburban train / commuter train", "noun", "A1", "Mit der S-Bahn ist man schnell im Umland.", "Banliyö treniyle çevre şehirlere hızla ulaşılır.", "With the suburban train one quickly reaches the surrounding area.", [], []),
    ("die Straßenbahn, -en", "tramvay", "tram / streetcar", "noun", "A1", "In Dresden fährt eine moderne Straßenbahn.", "Dresden'de modern bir tramvay çalışıyor.", "In Dresden a modern tram runs.", ["die Tram"], []),
    ("das Fahrrad, -¨er", "bisiklet", "bicycle / bike", "noun", "A1", "Ich fahre im Sommer mit dem Fahrrad zur Arbeit.", "Yazın işe bisikletle giderim.", "In summer I cycle to work.", ["das Rad"], []),
    ("der Radweg, -e", "bisiklet yolu", "bike lane / cycle path", "noun", "A2", "Radfahrer sollten den Radweg benutzen.", "Bisikletliler bisiklet yolunu kullanmalıdır.", "Cyclists should use the cycle path.", [], []),
    ("das Flugzeug, -e", "uçak", "airplane / plane", "noun", "A1", "Das Flugzeug startet in wenigen Minuten.", "Uçak birkaç dakika içinde havalanıyor.", "The airplane takes off in a few minutes.", ["der Flieger"], []),
    ("der Flughafen, -¨", "havalimanı", "airport", "noun", "A1", "Wir sind zwei Stunden vor Abflug am Flughafen.", "Uçuştan iki saat önce havalimanındayız.", "We are at the airport two hours before departure.", [], []),
    ("der Flug, -¨e", "uçuş", "flight", "noun", "A1", "Unser Flug wurde leider annulliert.", "Uçuşumuz maalesef iptal edildi.", "Our flight was unfortunately cancelled.", [], []),
    ("das Ticket, -s", "bilet", "ticket", "noun", "A1", "Haben Sie Ihr Ticket dabei?", "Biletiniz yanınızda mı?", "Do you have your ticket with you?", ["die Fahrkarte"], []),
    ("die Fahrkarte, -n", "yolculuk bileti", "fare ticket", "noun", "A1", "Kaufen Sie die Fahrkarte am Automaten.", "Bileti otomattan satın alınız.", "Buy the fare ticket at the machine.", ["das Ticket"], []),
    ("der Fahrplan, -¨e", "sefer tarifesi", "timetable / schedule", "noun", "A1", "Laut Fahrplan kommt der Bus um 14:15 Uhr.", "Tarifeye göre otobüs 14:15'te geliyor.", "According to the schedule the bus arrives at 2:15 pm.", [], []),
    ("die Verspätung, -en", "gecikme, rötar", "delay", "noun", "A1", "Wegen einer Baustelle hat der Zug Verspätung.", "Yol çalışması nedeniyle tren gecikmeli.", "Due to construction the train has a delay.", [], ["die Pünktlichkeit"]),
    ("die Panne, -n", "arıza", "breakdown", "noun", "A2", "Wir hatten eine Reifenpanne auf der Autobahn.", "Otoyolda lastik arızası yaşadık.", "We had a tire puncture on the highway.", ["der Defekt"], []),
]

print(f"Loaded {len(NOUNS_P2)} nouns in nouns_part2.py")
