# scripts/vocab_sources/nouns_part3.py
"""
Part 3 of Nouns: ~350 nouns covering:
Beruf & Arbeit, Büro & Technik, Bildung & Schule, Medien & Kommunikation, Behörden, Recht & Gesellschaft, Freizeit & Natur.
Format: (de, tr, en, pos, level, ex, ex_tr, ex_en, syns, ants)
"""

NOUNS_P3 = [
    # --- Beruf & Arbeitsplatz (Work, Office & Career) ---
    ("der Beruf, -e", "meslek", "profession / occupation", "noun", "A1", "Was sind Sie von Beruf?", "Mesleğiniz nedir?", "What is your profession?", ["die Tätigkeit", "der Job"], []),
    ("die Arbeit, -en", "iş, çalışma", "work / job", "noun", "A1", "Ich fahre um sieben Uhr zur Arbeit.", "Saat yedide işe gidiyorum.", "I drive to work at seven.", ["der Job"], ["die Freizeit"]),
    ("der Arbeitsplatz, -¨e", "iş yeri", "workplace", "noun", "A2", "Mein Arbeitsplatz ist modern ausgestattet.", "İş yerim modern donatılmıştır.", "My workplace is equipped modernly.", [], []),
    ("die Stelle, -n", "iş pozisyonu, yer", "job post / position", "noun", "A2", "Ich habe mich um eine neue Stelle beworben.", "Yeni bir iş pozisyonuna başvurdum.", "I applied for a new job position.", ["der Posten"], []),
    ("die Bewerbung, -en", "iş başvurusu", "job application", "noun", "A2", "Ich habe meine Bewerbung per E-Mail verschickt.", "İş başvurumu e-posta ile gönderdim.", "I sent my job application by email.", [], []),
    ("der Lebenslauf, -¨e", "özgeçmiş, CV", "curriculum vitae / resume", "noun", "A2", "Dem Anschreiben liegt mein Lebenslauf bei.", "Ön yazıya özgeçmişim eklidir.", "My CV is enclosed with the cover letter.", ["das CV"], []),
    ("das Zeugnis, -se", "diploma, karne, bonservis", "certificate / report card / reference", "noun", "A2", "Legen Sie bitte alle Zeugnisse bei.", "Lütfen tüm bonservisleri ekleyiniz.", "Please attach all certificates.", ["das Zertifikat"], []),
    ("das Vorstellungsgespräch, -e", "iş mülakatı", "job interview", "noun", "B1", "Morgen habe ich ein wichtiges Vorstellungsgespräch.", "Yarın önemli bir iş mülakatım var.", "Tomorrow I have an important job interview.", ["das Bewerbungsgespräch"], []),
    ("der Arbeitsvertrag, -¨e", "iş sözleşmesi", "employment contract", "noun", "A2", "Der Arbeitsvertrag ist unbefristet.", "İş sözleşmesi süresizdir.", "The employment contract is permanent.", [], []),
    ("das Gehalt, -¨er", "maaş (aylık)", "salary", "noun", "A2", "Das Gehalt wird am Monatsende überwiesen.", "Maaş ay sonunda havale edilir.", "The salary is transferred at the end of the month.", ["der Lohn"], []),
    ("der Lohn, -¨e", "ücret (saatlik/haftalık)", "wage / pay", "noun", "A2", "Der Mindestlohn ist gesetzlich geregelt.", "Asgari ücret yasa ile düzenlenmiştir.", "The minimum wage is regulated by law.", ["das Gehalt"], []),
    ("die Überstunde, -n", "fazla mesai", "overtime", "noun", "A2", "Diese Woche habe ich fünf Überstunden gemacht.", "Bu hafta beş saat fazla mesai yaptım.", "This week I worked five hours overtime.", [], []),
    ("der Feierabend, -e", "mesai bitimi, paydos", "quitting time / end of work", "noun", "A1", "Schönen Feierabend allerseits!", "Herkese iyi paydoslar!", "Have a good evening after work, everyone!", [], []),
    ("der Urlaub, -e", "izin, tatil", "vacation / leave", "noun", "A1", "Ich nehme im August zwei Wochen Urlaub.", "Ağustosta iki hafta izin alıyorum.", "I am taking two weeks vacation in August.", ["die Ferien"], []),
    ("der Kollege, -n", "iş arkadaşı (erkek)", "colleague (male)", "noun", "A1", "Mein Kollege hilft mir gerne.", "İş arkadaşım bana seve seve yardım eder.", "My colleague likes helping me.", ["der Mitarbeiter"], []),
    ("die Kollegin, -nen", "iş arkadaşı (kadın)", "colleague (female)", "noun", "A1", "Meine Kollegin spricht fünf Sprachen.", "İş arkadaşım kadın beş dil konuşuyor.", "My female colleague speaks five languages.", [], []),
    ("der Chef, -s", "patron, müdür (erkek)", "boss / manager (male)", "noun", "A1", "Der Chef leitet die Besprechung.", "Müdür toplantıyı yönetiyor.", "The boss is leading the meeting.", ["der Vorgesetzte", "der Leiter"], []),
    ("die Chefin, -nen", "patron, müdür (kadın)", "boss / manager (female)", "noun", "A1", "Die Chefin lobte unser Team.", "Müdüre hanım ekibimizi övdü.", "The female boss praised our team.", ["die Leiterin"], []),
    ("die Kündigung, -en", "işten çıkarma, fesih", "termination / notice", "noun", "A2", "Er reichte seine Kündigung ein.", "İstifasını sundu.", "He handed in his notice.", [], []),
    ("das Büro, -s", "ofis, büro", "office", "noun", "A1", "Unser Büro liegt im Stadtzentrum.", "Ofisimiz şehir merkezinde yer alıyor.", "Our office is located in the city center.", [], []),
    ("die Firma, Firmen", "şirket, firma", "company / firm", "noun", "A1", "Die Firma produziert Autoteile.", "Firma araba parçaları üretiyor.", "The company produces auto parts.", ["das Unternehmen", "der Betrieb"], []),
    ("das Unternehmen, -", "işletme, girişim", "enterprise / company", "noun", "B1", "Das Familienunternehmen besteht seit 100 Jahren.", "Aile işletmesi 100 yıldır varlığını sürdürüyor.", "The family enterprise has existed for 100 years.", ["die Firma"], []),
    ("die Abteilung, -en", "departman, bölüm", "department", "noun", "A2", "Sie arbeitet in der Personalabteilung.", "İnsan kaynakları departmanında çalışıyor.", "She works in the HR department.", [], []),
    ("die Besprechung, -en", "toplantı", "meeting / briefing", "noun", "A2", "Die Besprechung beginnt um 10 Uhr.", "Toplantı saat 10'da başlıyor.", "The meeting begins at 10 am.", ["das Meeting", "die Konferenz"], []),
    ("die Konferenz, -en", "konferans", "conference", "noun", "B1", "Fachleute aus aller Welt nahmen an der Konferenz teil.", "Dünyanın her yerinden uzmanlar konferansa katıldı.", "Experts from all over the world took part in the conference.", [], []),
    ("der Feiertag, -e", "resmi tatil günü", "public holiday", "noun", "A1", "Morgen ist ein Feiertag, die Läden sind geschlossen.", "Yarın resmi tatil, dükkanlar kapalı.", "Tomorrow is a public holiday, the shops are closed.", [], []),
    ("der Feierabend (Sg.)", "paydos vakti", "closing time / evening off", "noun", "A1", "Um 17 Uhr mache ich Feierabend.", "Saat 17'de paydos yapıyorum.", "At 5 pm I finish work for the day.", [], []),
    ("die Gewerkschaft, -en", "sendika", "trade union", "noun", "B1", "Die Gewerkschaft fordert faire Löhne.", "Sendika adil ücretler talep ediyor.", "The trade union demands fair wages.", [], []),
    ("der Streik, -s", "grev", "strike", "noun", "B1", "Wegen des Streiks fahren heute keine Züge.", "Grev nedeniyle bugün tren çalışmıyor.", "Due to the strike no trains are running today.", [], []),

    # --- Büro, Technik & Computer (Office, Tech & IT) ---
    ("der Computer, -", "bilgisayar", "computer", "noun", "A1", "Ich arbeite den ganzen Tag am Computer.", "Bütün gün bilgisayar başında çalışıyorum.", "I work at the computer all day.", ["der Rechner", "der PC"], []),
    ("der Laptop, -s", "dizüstü bilgisayar", "laptop", "noun", "A1", "Der Laptop ist leicht und handlich.", "Dizüstü bilgisayar hafif ve kullanışlıdır.", "The laptop is lightweight and handy.", ["das Notebook"], []),
    ("die Tastatur, -en", "klavye", "keyboard", "noun", "A2", "Auf der Tastatur fehlen ein paar Tasten.", "Klavyede birkaç tuş eksik.", "A few keys are missing on the keyboard.", [], []),
    ("die Maus, -¨e", "fare (bilgisayar)", "mouse (computer)", "noun", "A1", "Klicken Sie mit der Maus auf den Link.", "Fareyle bağlantıya tıklayınız.", "Click on the link with the mouse.", [], []),
    ("der Bildschirm, -e", "ekran, monitör", "screen / monitor", "noun", "A1", "Der Bildschirm hat eine hohe Auflösung.", "Ekran yüksek çözünürlüklüdür.", "The screen has a high resolution.", ["der Monitor"], []),
    ("der Drucker, -", "yazıcı", "printer", "noun", "A1", "Im Drucker ist das Papier alle.", "Yazıcıda kağıt bitti.", "The printer is out of paper.", [], []),
    ("das Papier, -e", "kağıt", "paper", "noun", "A1", "Geben Sie mir bitte ein Blatt Papier.", "Bana lütfen bir yaprak kağıt veriniz.", "Please give me a sheet of paper.", [], []),
    ("der Stift, -e", "kalem", "pen", "noun", "A1", "Haben Sie einen Stift für mich?", "Benim için bir kaleminiz var mı?", "Do you have a pen for me?", [], []),
    ("der Kugelschreiber, -", "tükenmez kalem", "ballpoint pen", "noun", "A1", "Unterschreiben Sie bitte mit Kugelschreiber.", "Lütfen tükenmez kalemle imzalayınız.", "Please sign with a ballpoint pen.", ["der Kuli"], []),
    ("das Formular, -e", "form (belge)", "form (document)", "noun", "A1", "Füllen Sie dieses Formular bitte aus.", "Bu formu lütfen doldurunuz.", "Please fill out this form.", [], []),
    ("der Ordner, -", "klasör", "folder / binder", "noun", "A2", "Alle Rechnungen sind im roten Ordner abgeheftet.", "Bütün faturalar kırmızı klasöre takılmıştır.", "All invoices are filed in the red folder.", [], []),
    ("der Schreibtisch, -e", "çalışma masası", "desk", "noun", "A1", "Mein Schreibtisch steht am Fenster.", "Çalışma masam pencerenin yanında duruyor.", "My desk is by the window.", [], []),
    ("das Internet (Sg.)", "internet", "internet", "noun", "A1", "Ich suche Informationen im Internet.", "İnternette bilgi arıyorum.", "I search for information on the internet.", [], []),
    ("das WLAN (Sg.)", "kablosuz internet, wi-fi", "Wi-Fi", "noun", "A1", "Wie lautet das Passwort für das WLAN?", "Wi-Fi'nin şifresi nedir?", "What is the Wi-Fi password?", [], []),
    ("das Passwort, -¨er", "şifre, parola", "password", "noun", "A1", "Wählen Sie ein sicheres Passwort!", "Güvenli bir şifre seçiniz!", "Choose a secure password!", ["das Kennwort"], []),
    ("die E-Mail, -s", "e-posta", "email", "noun", "A1", "Ich habe Ihnen eine E-Mail geschickt.", "Size bir e-posta gönderdim.", "I sent you an email.", [], []),
    ("die Nachricht, -en", "mesaj, haber", "message / news item", "noun", "A1", "Hinterlassen Sie bitte eine Nachricht nach dem Ton.", "Lütfen sinyal sesinden sonra mesaj bırakınız.", "Please leave a message after the tone.", ["die Mitteilung"], []),
    ("das Handy, -s", "cep telefonu", "mobile phone / cell phone", "noun", "A1", "Mein Handy hat keinen Empfang.", "Cep telefonum çekmiyor.", "My mobile phone has no signal.", ["das Mobiltelefon", "das Smartphone"], []),
    ("die Datei, -en", "bilgisayar dosyası", "file (computer)", "noun", "A2", "Speichern Sie die Datei auf dem Desktop.", "Dosyayı masaüstüne kaydediniz.", "Save the file on the desktop.", [], []),
    ("das Dokument, -e", "belge, doküman", "document", "noun", "A2", "Drucken Sie das Dokument bitte zweimal aus.", "Belgenin çıktısını lütfen iki kez alınız.", "Please print out the document twice.", ["die Unterlage"], []),
    ("die Unterlagen (Pl.)", "evraklar, belgeler", "documents / paperwork", "noun", "A2", "Bringen Sie alle wichtigen Unterlagen mit.", "Tüm önemli evrakları yanınızda getiriniz.", "Bring all important paperwork along.", ["die Dokumente"], []),

    # --- Bildung, Schule & Wissen (Education, School & Knowledge) ---
    ("die Schule, -n", "okul", "school", "noun", "A1", "Die Kinder gehen gerne in die Schule.", "Çocuklar okula severek gidiyor.", "The children like going to school.", [], []),
    ("der Schüler, -", "öğrenci (okul, erkek)", "school pupil (male)", "noun", "A1", "Der Schüler lernt für die Klassenarbeit.", "Öğrenci sınav için ders çalışıyor.", "The pupil is studying for the test.", [], ["der Lehrer"]),
    ("die Schülerin, -nen", "öğrenci (okul, kadın)", "school pupil (female)", "noun", "A1", "Die Schülerin meldet sich im Unterricht.", "Kız öğrenci derste parmak kaldırıyor.", "The female pupil raises her hand in class.", [], []),
    ("der Lehrer, -", "öğretmen (erkek)", "teacher (male)", "noun", "A1", "Der Lehrer erklärt die Aufgabe geduldig.", "Öğretmen ödevi sabırla açıklıyor.", "The teacher explains the exercise patiently.", [], ["der Schüler"]),
    ("die Lehrerin, -nen", "öğretmen (kadın)", "teacher (female)", "noun", "A1", "Unsere Deutschlehrerin ist sehr nett.", "Almanca öğretmenimiz kadın çok kibar.", "Our female German teacher is very nice.", [], []),
    ("der Unterricht (Sg.)", "ders, öğretim", "class / lessons / tuition", "noun", "A1", "Der Unterricht beginnt um 8:30 Uhr.", "Ders saat 8:30'da başlıyor.", "The lesson starts at 8:30 am.", ["die Stunde"], []),
    ("die Pause, -n", "teneffüs, mola", "break / recess", "noun", "A1", "In der Pause essen die Kinder ihr Pausenbrot.", "Teneffüste çocuklar beslenmelerini yiyor.", "In the break the children eat their snack.", ["die Unterbrechung"], []),
    ("die Hausaufgabe, -n", "ev ödevi", "homework", "noun", "A1", "Vergiss deine Hausaufgaben nicht!", "Ev ödevlerini unutma!", "Don't forget your homework!", [], []),
    ("die Klasse, -n", "sınıf (öğrenci grubu)", "class / grade", "noun", "A1", "In meiner Klasse sind 20 Schüler.", "Sınıfımda 20 öğrenci var.", "In my class there are 20 pupils.", [], []),
    ("das Klassenzimmer, -", "derslik, sınıf odası", "classroom", "noun", "A1", "Das Klassenzimmer ist groß und hell.", "Derslik büyük ve aydınlık.", "The classroom is large and bright.", [], []),
    ("die Tafel, -n", "yazı tahtası, tablet çikolata", "blackboard / chalkboard / bar of chocolate", "noun", "A1", "Der Lehrer schreibt an die Tafel.", "Öğretmen tahtaya yazıyor.", "The teacher writes on the board.", [], []),
    ("die Universität, -en", "üniversite", "university", "noun", "A1", "Er studiert an der Universität zu Köln.", "Köln Üniversitesi'nde okuyor.", "He studies at the University of Cologne.", ["die Uni", "die Hochschule"], []),
    ("der Student, -en", "üniversite öğrencisi (erkek)", "college student (male)", "noun", "A1", "Die Studenten demonstrieren für günstigere Mieten.", "Üniversite öğrencileri daha uygun kiralar için gösteri yapıyor.", "The students demonstrate for cheaper rents.", [], []),
    ("die Studentin, -nen", "üniversite öğrencisi (kadın)", "college student (female)", "noun", "A1", "Sie ist eine fleißige Studentin.", "O çalışkan bir üniversite öğrencisidir.", "She is a diligent student.", [], []),
    ("das Studium, Studien", "yükseköğrenim, lisans eğitimi", "university studies / degree", "noun", "A2", "Nach dem Studium möchte er im Ausland arbeiten.", "Eğitimden sonra yurtdışında çalışmak istiyor.", "After his studies he wants to work abroad.", [], []),
    ("die Prüfung, -en", "sınav", "exam / examination", "noun", "A1", "Ich wünsche dir viel Erfolg bei der Prüfung!", "Sınavda sana bol başarılar dilerim!", "I wish you much success in the exam!", ["der Test", "das Examen"], []),
    ("das Examen, -", "mezuniyet sınavı", "final exam / state exam", "noun", "B1", "Sie hat ihr medizinisches Examen bestanden.", "Tıp fakültesi bitirme sınavını verdi.", "She passed her medical state exam.", ["die Abschlussprüfung"], []),
    ("der Test, -s", "test, küçük sınav", "test / quiz", "noun", "A1", "Wir schreiben morgen einen Grammatiktest.", "Yarın bir gramer testi yazacağız.", "Tomorrow we write a grammar test.", ["die Prüfung"], []),
    ("die Note, -n", "not (sınav), nota (müzik)", "grade / mark / musical note", "noun", "A1", "Er hat eine Eins in Deutsch bekommen.", "Almancadan bir (en iyi not) aldı.", "He got an 'A' in German.", ["die Zensur"], []),
    ("der Fehler, -", "hata, kusur", "mistake / error", "noun", "A1", "Aus Fehlern lernt man am meisten.", "İnsan en çok hatalardan öğrenir.", "One learns the most from mistakes.", ["der Irrtum"], []),
    ("die Lösung, -en", "çözüm", "solution / key", "noun", "A2", "Finden wir eine gemeinsame Lösung!", "Ortak bir çözüm bulalım!", "Let's find a common solution!", ["der Ausweg"], []),
    ("das Wörterbuch, -¨er", "sözlük", "dictionary", "noun", "A1", "Schlage unbekannte Wörter im Wörterbuch nach.", "Bilinmeyen kelimelere sözlükten bak.", "Look up unknown words in the dictionary.", ["das Lexikon"], []),
    ("die Sprache, -n", "dil, lisan", "language", "noun", "A1", "Wie viele Sprachen sprechen Sie?", "Kaç dil konuşuyorsunuz?", "How many languages do you speak?", ["die Zunge"], []),
    ("das Wort, -¨er", "tekil kelime", "word (individual)", "noun", "A1", "Lerne jeden Tag zehn neue Wörter!", "Her gün on yeni kelime öğren!", "Learn ten new words every day!", ["die Vokabel"], []),
    ("der Satz, -¨e", "cümle, set", "sentence / clause / set", "noun", "A1", "Bilden Sie bitte einen vollständigen Satz.", "Lütfen tam bir cümle kurunuz.", "Please form a complete sentence.", [], []),
    ("die Grammatik, -en", "dilbilgisi, gramer", "grammar", "noun", "A1", "Die deutsche Grammatik ist logisch aufgebaut.", "Almanca dilbilgisi mantıksal yapılandırılmıştır.", "German grammar is logically constructed.", [], []),

    # --- Behörden, Recht & Staat (Authorities, Law & State) ---
    ("die Behörde, -n", "resmi makam, kamu dairesi", "public authority / agency", "noun", "A2", "Sie müssen den Antrag bei der Behörde einreichen.", "Dilekçeyi resmi makama teslim etmelisiniz.", "You must submit the application to the authority.", ["das Amt"], []),
    ("das Amt, -¨er", "kamu dairesi, memuriyet", "office / official department", "noun", "A2", "Ich habe einen Termin beim Bürgeramt.", "Nüfus müdürlüğünde bir randevum var.", "I have an appointment at the civic registry office.", ["die Behörde"], []),
    ("das Bürgeramt, -¨er", "nüfus/vatandaşlık dairesi", "citizen services office", "noun", "A2", "Die Anmeldung erfolgt beim Bürgeramt.", "İkamet kaydı vatandaşlık dairesinde yapılır.", "Registration takes place at the citizen services office.", ["das Einwohnermeldeamt"], []),
    ("das Ausländeramt, -¨er", "yabancılar dairesi", "immigration office", "noun", "A2", "Mein Aufenthaltstitel wird im Ausländeramt verlängert.", "Oturum iznim yabancılar dairesinde uzatılıyor.", "My residence permit is renewed at the immigration office.", ["die Ausländerbehörde"], []),
    ("der Ausweis, -e", "kimlik kartı", "identity card / ID", "noun", "A1", "Zeigen Sie mir bitte Ihren Ausweis!", "Lütfen bana kimliğinizi gösteriniz!", "Please show me your ID card!", ["der Personalausweis"], []),
    ("der Reisepass, -¨e", "pasaport", "passport", "noun", "A1", "Für Reisen außerhalb der EU braucht man einen Reisepass.", "AB dışı seyahatlerde pasaport gerekir.", "For travel outside the EU you need a passport.", ["der Pass"], []),
    ("der Führerschein, -e", "sürücü belgesi, ehliyet", "driving licence / driver's license", "noun", "A1", "Er hat die Führerscheinprüfung bestanden.", "Ehliyet sınavını başarıyla geçti.", "He passed the driving test.", ["die Fahrerlaubnis"], []),
    ("die Anmeldung, -en", "kayıt (ikamet/kurs)", "registration", "noun", "A1", "Bringen Sie die Anmeldebestätigung mit.", "Kayıt onay belgesini yanınızda getiriniz.", "Bring the registration confirmation along.", [], ["die Abmeldung"]),
    ("die Abmeldung, -en", "kayıt sildirme", "deregistration", "noun", "A2", "Vor dem Umzug ins Ausland ist die Abmeldung nötig.", "Yurtdışına taşınmadan önce kayıt sildirme gereklidir.", "Before moving abroad deregistration is necessary.", [], ["die Anmeldung"]),
    ("das Gesetz, -e", "kanun, yasa", "law / statute", "noun", "A2", "Niemand steht über dem Gesetz.", "Hiç kimse kanundan üstün değildir.", "No one is above the law.", ["das Recht"], []),
    ("die Polizei (Sg.)", "polis", "police", "noun", "A1", "Rufen Sie im Notfall die Polizei!", "Acil durumda polisi arayınız!", "Call the police in an emergency!", [], []),
    ("der Polizist, -en", "polis memuru (erkek)", "police officer (male)", "noun", "A1", "Der Polizist regelte den Verkehr an der Kreuzung.", "Polis memuru kavşakta trafiği yönetti.", "The policeman directed the traffic at the intersection.", [], []),
    ("die Polizistin, -nen", "polis memuru (kadın)", "police officer (female)", "noun", "A1", "Die Polizistin half dem verlorenen Kind.", "Kadın polis kaybolan çocuğa yardım etti.", "The policewoman helped the lost child.", [], []),
    ("die Feuerwehr (Sg.)", "itfaiye", "fire department / fire brigade", "noun", "A1", "Die Feuerwehr löschte das Feuer schnell.", "İtfaiye yangını çabucak söndürdü.", "The fire department extinguished the fire quickly.", [], []),
    ("das Gericht, -e", "mahkeme, yargı", "court of law", "noun", "B1", "Der Fall wird vor Gericht verhandelt.", "Dava mahkeme huzurunda görüşülüyor.", "The case is being tried in court.", [], []),
    ("der Richter, -", "hakim, yargıç", "judge", "noun", "B1", "Der Richter verkündete das gerechte Urteil.", "Hakim adil kararı açıkladı.", "The judge announced the fair verdict.", [], []),
    ("der Anwalt, -¨e", "avukat (erkek)", "lawyer / attorney (male)", "noun", "A2", "Mein Anwalt prüft den Vertrag gründlich.", "Avukatım sözleşmeyi etraflıca inceliyor.", "My lawyer examines the contract thoroughly.", ["der Rechtsanwalt"], []),
    ("die Anwältin, -nen", "avukat (kadın)", "lawyer / attorney (female)", "noun", "A2", "Die Anwältin vertrat ihren Mandanten hervorragend.", "Kadın avukat müvekkilini mükemmel savundu.", "The female lawyer represented her client superbly.", [], []),
    ("die Steuer, -n", "vergi", "tax", "noun", "A2", "In Deutschland zahlt man Einkommensteuer.", "Almanya'da gelir vergisi ödenir.", "In Germany people pay income tax.", ["die Abgabe"], []),
    ("der Staat, -en", "devlet", "state / nation", "noun", "A2", "Der Staat fördert Familien mit Kindern.", "Devlet çocuklu aileleri destekler.", "The state supports families with children.", ["das Land"], []),
    ("die Politik (Sg.)", "siyaset, politika", "politics / policy", "noun", "A2", "Er interessiert sich brennend für Politik.", "Siyasete büyük ilgi duyuyor.", "He is keenly interested in politics.", [], []),
    ("die Regierung, -en", "hükümet", "government", "noun", "A2", "Die neue Regierung plant Reformen.", "Yeni hükümet reformlar planlıyor.", "The new government plans reforms.", [], []),
    ("die Wahl, -en", "seçim, tercih", "election / choice", "noun", "A2", "Im Herbst finden die Wahlen statt.", "Sonbaharda seçimler gerçekleşecek.", "In autumn the elections take place.", ["die Abstimmung"], []),

    # --- Freizeit, Medien & Natur (Leisure, Media & Nature) ---
    ("die Freizeit (Sg.)", "boş zaman", "free time / leisure", "noun", "A1", "Was machst du in deiner Freizeit?", "Boş zamanlarında ne yaparsın?", "What do you do in your free time?", ["die Muße"], ["die Arbeit"]),
    ("das Hobby, -s", "hobi", "hobby", "noun", "A1", "Mein Hobby ist Fotografieren.", "Hobim fotoğraf çekmektir.", "My hobby is photography.", ["die Leidenschaft"], []),
    ("der Sport (Sg.)", "spor", "sport / athletics", "noun", "A1", "Sport ist gut für Körper und Geist.", "Spor beden ve zihin için iyidir.", "Sport is good for body and mind.", ["die Bewegung"], []),
    ("die Musik (Sg.)", "müzik", "music", "noun", "A1", "Klassische Musik beruhigt die Nerven.", "Klasik müzik sinirleri yatıştırır.", "Classical music calms the nerves.", [], []),
    ("das Konzert, -e", "konser", "concert", "noun", "A1", "Wir gehen morgen auf ein Rockkonzert.", "Yarın bir rock konserine gidiyoruz.", "We are going to a rock concert tomorrow.", [], []),
    ("das Kino, -s", "sinema", "cinema / movies", "noun", "A1", "Im Kino läuft ein spannender Film.", "Sinemada heyecan verici bir film gösterimde.", "An exciting movie is playing in the cinema.", ["das Lichtspielhaus"], []),
    ("das Theater, -", "tiyatro", "theater", "noun", "A1", "Am Wochenende gehen wir ins Theater.", "Hafta sonu tiyatroya gidiyoruz.", "On the weekend we go to the theater.", ["die Bühne"], []),
    ("das Museum, Museen", "müze", "museum", "noun", "A1", "Das Museum ist montags geschlossen.", "Müze pazartesi günleri kapalıdır.", "The museum is closed on Mondays.", [], []),
    ("die Ausstellung, -en", "sergi", "exhibition", "noun", "A2", "Die Ausstellung zeigt moderne Gemälde.", "Sergi modern tablolar sergiliyor.", "The exhibition shows modern paintings.", ["die Schau"], []),
    ("die Natur (Sg.)", "doğa, tabiat", "nature", "noun", "A1", "Ich verbringe gerne Zeit in der freien Natur.", "Açık doğada zaman geçirmeyi çok severim.", "I like spending time in the open nature.", ["die Umwelt"], []),
    ("die Umwelt (Sg.)", "çevre", "environment", "noun", "A2", "Wir müssen unsere Umwelt schützen.", "Çevremizi korumak zorundayız.", "We must protect our environment.", ["die Natur"], []),
    ("der Baum, -¨e", "ağaç", "tree", "noun", "A1", "Der alte Baum spendet kühlen Schatten.", "Yaşlı ağaç serin bir gölge veriyor.", "The old tree gives cool shade.", [], []),
    ("die Blume, -n", "çiçek", "flower", "noun", "A1", "Er schenkte ihr einen Strauß bunter Blumen.", "Ona rengarenk çiçeklerden bir buket hediye etti.", "He gave her a bouquet of colorful flowers.", [], []),
    ("das Tier, -e", "hayvan", "animal", "noun", "A1", "Kinder lieben Tiere sehr.", "Çocuklar hayvanları çok sever.", "Children love animals very much.", [], []),
    ("der Hund, -e", "köpek", "dog", "noun", "A1", "Der Hund ist der beste Freund des Menschen.", "Köpek insanın en iyi dostudur.", "The dog is man's best friend.", [], []),
    ("die Katze, -n", "kedi", "cat", "noun", "A1", "Die Katze schläft auf dem Sofa.", "Kedi kanepede uyuyor.", "The cat sleeps on the sofa.", [], []),
    ("das Wetter (Sg.)", "hava durumu", "weather", "noun", "A1", "Wie ist das Wetter heute?", "Bugün hava nasıl?", "How is the weather today?", ["die Witterung"], []),
    ("die Sonne (Sg.)", "güneş", "sun", "noun", "A1", "Die Sonne scheint am blauen Himmel.", "Güneş mavi gökyüzünde parlıyor.", "The sun shines in the blue sky.", [], ["der Mond"]),
    ("der Regen (Sg.)", "yağmur", "rain", "noun", "A1", "Nach dem warmen Regen duftet die Erde.", "Sıcak yağmurun ardından toprak mis gibi kokuyor.", "After the warm rain the earth smells lovely.", ["der Niederschlag"], []),
    ("der Schnee (Sg.)", "kar", "snow", "noun", "A1", "Im Winter liegt weißer Schnee auf den Bergen.", "Kışın dağların üzerinde beyaz kar bulunur.", "In winter white snow lies on the mountains.", [], []),
    ("der Wind, -e", "rüzgar", "wind", "noun", "A1", "Ein kräftiger Wind weht von Westen.", "Batıdan kuvvetli bir rüzgar esiyor.", "A strong wind blows from the west.", ["die Brise"], []),
    ("die Wolke, -n", "bulut", "cloud", "noun", "A1", "Dunkle Wolken ziehen am Himmel auf.", "Gökyüzünde kara bulutlar toplanıyor.", "Dark clouds gather in the sky.", [], []),
    ("der Nebel, -", "sis", "fog / mist", "noun", "A2", "Wegen dichten Nebels sieht man kaum etwas.", "Yoğun sis yüzünden neredeyse hiçbir şey görünmüyor.", "Because of dense fog you can hardly see anything.", [], []),
    ("das Gewitter, -", "gök gürültülü fırtına", "thunderstorm", "noun", "A2", "Ein schweres Gewitter zog über das Tal.", "Vadinin üzerinden şiddetli bir fırtına geçti.", "A severe thunderstorm passed over the valley.", ["das Unwetter"], []),
]

print(f"Loaded {len(NOUNS_P3)} nouns in nouns_part3.py")
