# scripts/vocab_sources/nouns_part1.py
"""
Part 1 of Nouns: 475 essential nouns covering:
Wohnen, Haushalt, Familie, Beziehungen, Körper, Gesundheit, Essen & Trinken, Einkaufen & Kleidung.
Format: (de, tr, en, pos, level, ex, ex_tr, ex_en, syns, ants)
"""

NOUNS_P1 = [
    # --- Wohnen & Haushalt (Housing & Home) ---
    ("das Haus, -¨er", "ev", "house", "noun", "A1", "Wir wohnen in einem kleinen Haus.", "Küçük bir evde oturuyoruz.", "We live in a small house.", ["das Gebäude"], []),
    ("die Wohnung, -en", "daire", "apartment / flat", "noun", "A1", "Sie suchen eine 3-Zimmer-Wohnung.", "Üç odalı bir daire arıyorlar.", "They are looking for a 3-room apartment.", ["das Apartment"], []),
    ("das Zimmer, -", "oda", "room", "noun", "A1", "Das Zimmer ist hell und ruhig.", "Oda aydınlık ve sakin.", "The room is bright and quiet.", ["der Raum"], []),
    ("die Küche, -n", "mutfak", "kitchen", "noun", "A1", "In der Küche kochen wir gerne.", "Mutfakta yemek pişirmeyi severiz.", "We like cooking in the kitchen.", [], []),
    ("das Bad, -¨er", "banyo", "bathroom", "noun", "A1", "Das Bad hat eine Dusche und eine Wanne.", "Banyoda bir duş ve bir küvet var.", "The bathroom has a shower and a tub.", ["das Badezimmer"], []),
    ("das Schlafzimmer, -", "yatak odası", "bedroom", "noun", "A1", "Im Schlafzimmer steht ein großes Bett.", "Yatak odasında büyük bir yatak duruyor.", "There is a large bed in the bedroom.", [], []),
    ("das Wohnzimmer, -", "oturma odası", "living room", "noun", "A1", "Wir sitzen abends im Wohnzimmer.", "Akşamları oturma odasında otururuz.", "We sit in the living room in the evening.", [], []),
    ("das Kinderzimmer, -", "çocuk odası", "children's room", "noun", "A1", "Die Kinder spielen im Kinderzimmer.", "Çocuklar çocuk odasında oynuyor.", "The children play in the children's room.", [], []),
    ("der Flur, -e", "koridor, antre", "hallway / corridor", "noun", "A1", "Die Schuhe stehen im Flur.", "Ayakkabılar koridorda duruyor.", "The shoes are in the hallway.", ["der Korridor"], []),
    ("der Balkon, -e", "balkon", "balcony", "noun", "A1", "Im Sommer frühstücken wir auf dem Balkon.", "Yazın balkonda kahvaltı yaparız.", "In summer we have breakfast on the balcony.", [], []),
    ("die Terrasse, -n", "teras", "terrace", "noun", "A2", "Die Terrasse bietet einen schönen Ausblick.", "Teras güzel bir manzara sunuyor.", "The terrace offers a beautiful view.", [], []),
    ("der Garten, -¨", "bahçe", "garden", "noun", "A1", "Die Blumen im Garten blühen schön.", "Bahçedeki çiçekler çok güzel açtı.", "The flowers in the garden bloom beautifully.", [], []),
    ("der Keller, -", "bodrum", "basement / cellar", "noun", "A1", "Die Fahrräder stehen im Keller.", "Bisikletler bodrumda duruyor.", "The bicycles are in the basement.", [], []),
    ("der Dachboden, -¨", "çatı katı", "attic", "noun", "A2", "Auf dem Dachboden lagern alte Kisten.", "Çatı katında eski kutular depolanıyor.", "Old boxes are stored in the attic.", [], []),
    ("die Garage, -n", "garaj", "garage", "noun", "A1", "Das Auto steht sicher in der Garage.", "Araba garajda güvenle duruyor.", "The car stands safely in the garage.", [], []),
    ("die Miete, -n", "kira", "rent", "noun", "A1", "Die Miete ist am Ersten des Monats fällig.", "Kira ayın birinde ödenmelidir.", "The rent is due on the first of the month.", [], []),
    ("die Warmmiete, -n", "yakıt/aidat dahil kira", "warm rent (incl. heating)", "noun", "A2", "Die Warmmiete beträgt 850 Euro.", "Isınma dahil kira 850 Euro tutuyor.", "The warm rent amounts to 850 euros.", [], ["die Kaltmiete"]),
    ("die Kaltmiete, -n", "yalın kira (aidatsız)", "cold rent (excl. utilities)", "noun", "A2", "Die Kaltmiete ist recht günstig.", "Yalın kira oldukça uygun.", "The cold rent is quite cheap.", [], ["die Warmmiete"]),
    ("die Nebenkosten (Pl.)", "yan giderler, aidat", "utility costs / utilities", "noun", "A2", "Heizung und Wasser sind in den Nebenkosten enthalten.", "Isınma ve su yan giderlere dahildir.", "Heating and water are included in the utilities.", [], []),
    ("die Kaution, -en", "depozito", "security deposit", "noun", "A2", "Die Kaution beträgt drei Monatskaltmieten.", "Depozito üç aylık soğuk kira tutarındadır.", "The deposit is three months cold rent.", [], []),
    ("der Vermieter, -", "ev sahibi (erkek)", "landlord", "noun", "A1", "Der Vermieter repariert die Heizung.", "Ev sahibi kaloriferi tamir ediyor.", "The landlord is repairing the heating.", [], ["der Mieter"]),
    ("die Vermieterin, -nen", "ev sahibi (kadın)", "landlady", "noun", "A1", "Die Vermieterin ist sehr freundlich.", "Ev sahibi hanım çok cana yakın.", "The landlady is very friendly.", [], ["die Mieterin"]),
    ("der Mieter, -", "kiracı (erkek)", "tenant (male)", "noun", "A1", "Die Mieter zahlen pünktlich.", "Kiracılar vaktinde ödüyor.", "The tenants pay on time.", [], ["der Vermieter"]),
    ("die Mieterin, -nen", "kiracı (kadın)", "tenant (female)", "noun", "A1", "Die neue Mieterin zieht morgen ein.", "Yeni kiracı kadın yarın taşınıyor.", "The new female tenant is moving in tomorrow.", [], ["die Vermieterin"]),
    ("der Mietvertrag, -¨e", "kira sözleşmesi", "rental agreement", "noun", "A2", "Wir haben den Mietvertrag unterschrieben.", "Kira sözleşmesini imzaladık.", "We signed the rental contract.", [], []),
    ("der Schlüssel, -", "anahtar", "key", "noun", "A1", "Ich habe meinen Schlüssel vergessen.", "Anahtarımı unuttum.", "I forgot my key.", [], []),
    ("das Schloss, -¨er", "kilit, şato", "lock / castle", "noun", "A2", "Das Schloss an der Haustür klemmt.", "Giriş kapısının kilidi sıkışıyor.", "The lock on the front door is jamming.", [], []),
    ("die Wand, -¨e", "duvar (iç)", "wall (interior)", "noun", "A1", "An der Wand hängt ein großes Bild.", "Duvarda büyük bir resim asılı.", "A large picture is hanging on the wall.", ["die Mauer"], []),
    ("die Tür, -en", "kapı", "door", "noun", "A1", "Schließen Sie bitte die Tür.", "Lütfen kapıyı kapatınız.", "Please close the door.", [], []),
    ("das Fenster, -", "pencere", "window", "noun", "A1", "Öffnen Sie bitte das Fenster!", "Lütfen pencereyi açın!", "Please open the window!", [], []),
    ("der Boden, -¨", "zemin, yer", "floor / ground", "noun", "A1", "Der Boden ist aus Holz gemacht.", "Zemin ahşaptan yapılmıştır.", "The floor is made of wood.", ["der Fußboden"], ["die Decke"]),
    ("die Decke, -n", "tavan, battaniye", "ceiling / blanket", "noun", "A1", "Die Decke im Altbau ist sehr hoch.", "Tarihi binada tavan çok yüksek.", "The ceiling in the old building is very high.", [], ["der Boden"]),
    ("die Treppe, -n", "merdiven", "stairs / staircase", "noun", "A1", "Wir nehmen die Treppe statt den Aufzug.", "Asansör yerine merdiveni kullanıyoruz.", "We take the stairs instead of the elevator.", [], []),
    ("der Aufzug, -¨e", "asansör", "elevator / lift", "noun", "A1", "Der Aufzug ist leider außer Betrieb.", "Asansör maalesef servis dışı.", "The elevator is unfortunately out of order.", ["der Fahrstuhl", "der Lift"], []),
    ("der Tisch, -e", "masa", "table", "noun", "A1", "Wir sitzen alle am Tisch.", "Hepimiz masada oturuyoruz.", "We all sit at the table.", [], []),
    ("der Stuhl, -¨e", "sandalye", "chair", "noun", "A1", "Nehmen Sie bitte auf dem Stuhl Platz!", "Lütfen sandalyeye buyurunuz!", "Please take a seat on the chair!", ["der Sessel"], []),
    ("das Sofa, -s", "kanepe, koltuk", "sofa / couch", "noun", "A1", "Das Sofa im Wohnzimmer ist gemütlich.", "Oturma odasındaki kanepe çok rahat.", "The sofa in the living room is cozy.", ["die Couch"], []),
    ("der Sessel, -", "tekli koltuk", "armchair", "noun", "A1", "Opa liest die Zeitung im Sessel.", "Dede gazeteyi koltukta okuyor.", "Grandpa reads the paper in the armchair.", [], []),
    ("das Bett, -en", "yatak", "bed", "noun", "A1", "Das Bett ist sehr bequem.", "Yatak çok rahat.", "The bed is very comfortable.", [], []),
    ("der Schrank, -¨e", "dolap", "cupboard / wardrobe", "noun", "A1", "Die Kleidung hängt im Schrank.", "Kıyafetler dolapta asılı.", "The clothes are hanging in the wardrobe.", [], []),
    ("das Regal, -e", "raf, kitaplık", "shelf / bookcase", "noun", "A1", "Die Bücher stehen ordentlich im Regal.", "Kitaplar rafta düzenli duruyor.", "The books stand neatly on the shelf.", [], []),
    ("die Lampe, -n", "lamba", "lamp", "noun", "A1", "Die Lampe spendet angenehmes Licht.", "Lamba hoş bir ışık veriyor.", "The lamp gives pleasant light.", ["die Leuchte"], []),
    ("der Teppich, -e", "halı", "carpet / rug", "noun", "A1", "Der Teppich liegt auf dem Holzboden.", "Halı ahşap zeminin üzerinde serili.", "The carpet lies on the wooden floor.", [], []),
    ("das Bild, -er", "resim, tablo", "picture / painting", "noun", "A1", "Das Bild an der Wand ist wunderschön.", "Duvardaki tablo çok güzel.", "The picture on the wall is wonderful.", ["das Gemälde", "das Foto"], []),
    ("der Spiegel, -", "ayna", "mirror", "noun", "A1", "Sie schaut kurz in den Spiegel.", "Aynaya kısaca bakıyor.", "She glances briefly into the mirror.", [], []),
    ("die Heizung, -en", "kalorifer, ısıtma", "heating / radiator", "noun", "A1", "Die Heizung funktioniert einwandfrei.", "Kalorifer kusursuz çalışıyor.", "The heating works flawlessly.", [], []),
    ("die Klimaanlage, -n", "klima", "air conditioning", "noun", "A2", "Im Sommer schalten wir die Klimaanlage an.", "Yazın klimayı açıyoruz.", "In summer we turn on the air conditioning.", [], []),
    ("der Kühlschrank, -¨e", "buzdolabı", "refrigerator", "noun", "A1", "Die Milch steht im Kühlschrank.", "Süt buzdolabında duruyor.", "The milk is in the fridge.", [], []),
    ("der Herd, -e", "ocak", "stove / cooker", "noun", "A1", "Der Topf steht auf dem Herd.", "Tencere ocağın üzerinde duruyor.", "The pot is on the stove.", ["der Ofen"], []),
    ("der Backofen, -¨", "fırın", "oven", "noun", "A2", "Die Pizza bäckt im Backofen.", "Pizza fırında pişiyor.", "The pizza is baking in the oven.", [], []),
    ("die Spülmaschine, -n", "bulaşık makinesi", "dishwasher", "noun", "A1", "Wir räumen die Spülmaschine ein.", "Bulaşık makinesini dolduruyoruz.", "We load the dishwasher.", ["der Geschirrspüler"], []),
    ("die Waschmaschine, -n", "çamaşır makinesi", "washing machine", "noun", "A1", "Die Waschmaschine wäscht leise.", "Çamaşır makinesi sessizce yıkıyor.", "The washing machine washes quietly.", [], []),
    ("der Staubsauger, -", "elektrik süpürgesi", "vacuum cleaner", "noun", "A1", "Der Staubsauger steht in der Abstellkammer.", "Elektrik süpürgesi kilerde duruyor.", "The vacuum cleaner is in the storage room.", [], []),
    ("das Bügeleisen, -", "ütü", "iron (clothes)", "noun", "A2", "Vorsicht, das Bügeleisen ist heiß!", "Dikkat, ütü sıcaktır!", "Careful, the iron is hot!", [], []),
    ("der Müll (Sg.)", "çöp", "garbage / trash", "noun", "A1", "Bring bitte den Müll raus!", "Lütfen çöpü dışarı çıkar!", "Please take out the trash!", ["der Abfall"], []),
    ("der Mülleimer, -", "çöp kovası", "trash can / dustbin", "noun", "A1", "Wirf das Papier in den Mülleimer.", "Kağıdı çöp kutusuna at.", "Throw the paper into the trash can.", [], []),
    ("die Müllabfuhr, -en", "çöp toplama hizmeti", "garbage collection", "noun", "A2", "Die Müllabfuhr kommt jeden Dienstag.", "Çöp kamyonu her salı gelir.", "Garbage collection comes every Tuesday.", [], []),
    ("die Mülltrennung, -en", "çöp ayrıştırma", "waste separation", "noun", "B1", "In Deutschland ist Mülltrennung Pflicht.", "Almanya'da çöp ayrıştırma zorunludur.", "Waste separation is mandatory in Germany.", [], []),
    ("der Nachbar, -n", "komşu (erkek)", "neighbor (male)", "noun", "A1", "Mein Nachbar hilft mir oft im Garten.", "Komşum bahçede bana sık sık yardım eder.", "My neighbor often helps me in the garden.", [], []),
    ("die Nachbarin, -nen", "komşu (kadın)", "neighbor (female)", "noun", "A1", "Die Nachbarin von gegenüber grüßt immer freundlich.", "Karşıdaki komşu kadın her zaman samimiyetle selam verir.", "The neighbor across the hall always greets kindly.", [], []),
    ("die Nachbarschaft, -en", "komşuluk, semt", "neighborhood", "noun", "A2", "Wir leben in einer ruhigen Nachbarschaft.", "Sakin bir mahallede yaşıyoruz.", "We live in a quiet neighborhood.", [], []),
    ("die Hausordnung, -en", "bina kuralları", "house rules", "noun", "A2", "Die Hausordnung regelt die Ruhezeiten.", "Bina kuralları dinlenme saatlerini belirler.", "The house rules regulate the rest times.", [], []),
    ("die Ruhezeit, -en", "dinlenme vakti (sessizlik)", "rest period / quiet hours", "noun", "A2", "Ab 22 Uhr gilt die gesetzliche Ruhezeit.", "Saat 22'den itibaren yasal dinlenme saati geçerlidir.", "From 10 pm legal quiet hours apply.", [], []),

    # --- Familie, Beziehungen & Personen (Family & People) ---
    ("die Familie, -n", "aile", "family", "noun", "A1", "Meine Familie kommt aus Izmir.", "Ailem İzmir'den geliyor.", "My family comes from Izmir.", [], []),
    ("die Eltern (Pl.)", "anne ve baba", "parents", "noun", "A1", "Meine Eltern wohnen in der Türkei.", "Anne babam Türkiye'de oturuyor.", "My parents live in Turkey.", [], []),
    ("der Vater, -¨", "baba", "father", "noun", "A1", "Mein Vater arbeitet bei der Post.", "Babam postanede çalışıyor.", "My father works at the post office.", ["der Papa"], ["die Mutter"]),
    ("die Mutter, -¨", "anne", "mother", "noun", "A1", "Meine Mutter kocht fantastisch.", "Annem harika yemek pişirir.", "My mother cooks fantastically.", ["die Mama"], ["der Vater"]),
    ("das Kind, -er", "çocuk", "child", "noun", "A1", "Das Kind spielt gerne draußen.", "Çocuk dışarıda oynamayı sever.", "The child likes playing outside.", [], ["der Erwachsene"]),
    ("der Sohn, -¨e", "oğul, erkek çocuk", "son", "noun", "A1", "Ihr Sohn geht schon in die Schule.", "Oğulları şimdiden okula gidiyor.", "Her son already goes to school.", [], ["die Tochter"]),
    ("die Tochter, -¨", "kız çocuk", "daughter", "noun", "A1", "Unsere Tochter studiert in Bonn.", "Kızımız Bonn'da üniversite okuyor.", "Our daughter studies in Bonn.", [], ["der Sohn"]),
    ("die Geschwister (Pl.)", "kardeşler", "siblings", "noun", "A1", "Hast du Geschwister?", "Kardeşin var mı?", "Do you have siblings?", [], []),
    ("der Bruder, -¨", "erkek kardeş", "brother", "noun", "A1", "Mein Bruder ist älter als ich.", "Erkek kardeşim benden daha büyük.", "My brother is older than me.", [], ["die Schwester"]),
    ("die Schwester, -n", "kız kardeş", "sister", "noun", "A1", "Meine Schwester wohnt in Wien.", "Kız kardeşim Viyana'da oturuyor.", "My sister lives in Vienna.", [], ["der Bruder"]),
    ("die Großeltern (Pl.)", "büyükanne ve büyükbaba", "grandparents", "noun", "A1", "Wir besuchen die Großeltern am Sonntag.", "Pazar günü büyükanne ve büyükbabamızı ziyaret ediyoruz.", "We visit our grandparents on Sunday.", [], []),
    ("der Großvater, -¨", "büyükbaba, dede", "grandfather", "noun", "A1", "Mein Großvater erzählt gerne alte Geschichten.", "Dedem eski hikayeler anlatmayı sever.", "My grandfather likes telling old stories.", ["der Opa"], ["die Großmutter"]),
    ("die Großmutter, -¨", "büyükanne, nine", "grandmother", "noun", "A1", "Meine Großmutter strickt warme Socken.", "Büyükannem sıcak çoraplar örüyor.", "My grandmother knits warm socks.", ["die Oma"], ["der Großvater"]),
    ("der Enkel, -", "erkek torun", "grandson", "noun", "A2", "Opa spielt gerne mit seinem Enkel.", "Dede torunuyla oynamayı sever.", "Grandpa likes playing with his grandson.", [], ["die Enkelin"]),
    ("die Enkelin, -nen", "kız torun", "granddaughter", "noun", "A2", "Sie hat zwei Enkelinnen.", "İki kız torunu var.", "She has two granddaughters.", [], ["der Enkel"]),
    ("der Onkel, -", "amca, dayı", "uncle", "noun", "A1", "Mein Onkel wohnt in Berlin.", "Amcam Berlin'de yaşıyor.", "My uncle lives in Berlin.", [], ["die Tante"]),
    ("die Tante, -n", "teyze, hala", "aunt", "noun", "A1", "Tante Helga hat uns eingeladen.", "Helga teyze bizi davet etti.", "Aunt Helga invited us.", [], ["der Onkel"]),
    ("der Cousin, -s", "kuzen (erkek)", "cousin (male)", "noun", "A1", "Mein Cousin kommt zu Besuch.", "Kuzenim ziyarete geliyor.", "My cousin is coming for a visit.", [], ["die Cousine"]),
    ("die Cousine, -n", "kuzen (kadın)", "cousin (female)", "noun", "A1", "Ich verstehe mich gut mit meiner Cousine.", "Kuzenimle çok iyi anlaşıyorum.", "I get on well with my cousin.", [], ["der Cousin"]),
    ("der Neffe, -n", "erkek yeğen", "nephew", "noun", "A2", "Mein Neffe lernt gerade laufen.", "Yeğenim yeni yeni yürümeyi öğreniyor.", "My nephew is just learning to walk.", [], ["die Nichte"]),
    ("die Nichte, -n", "kız yeğen", "niece", "noun", "A2", "Meine Nichte malt wunderschöne Bilder.", "Yeğenim harika resimler çiziyor.", "My niece draws wonderful pictures.", [], ["der Neffe"]),
    ("die Verwandten (Pl.)", "akrabalar", "relatives", "noun", "A2", "Zum Fest kommen alle Verwandten zusammen.", "Bayramda bütün akrabalar bir araya gelir.", "All the relatives gather for the celebration.", ["die Verwandtschaft"], []),
    ("der Mann, -¨er", "adam, koca", "man / husband", "noun", "A1", "Mein Mann arbeitet heute bis spät.", "Eşim bugün geç saate kadar çalışıyor.", "My husband is working late today.", ["der Ehemann"], ["die Frau"]),
    ("die Frau, -en", "kadın, eş", "woman / wife", "noun", "A1", "Seine Frau ist Tierärztin.", "Onun eşi veterinerdir.", "His wife is a veterinarian.", ["die Ehefrau"], ["der Mann"]),
    ("das Baby, -s", "bebek", "baby", "noun", "A1", "Das Baby schläft im Kinderwagen.", "Bebek pusetinde uyuyor.", "The baby is sleeping in the stroller.", ["der Säugling"], []),
    ("der Junge, -n", "oğlan çocuğu", "boy", "noun", "A1", "Der Junge spielt mit dem Ball.", "Oğlan topla oynuyor.", "The boy is playing with the ball.", [], ["das Mädchen"]),
    ("das Mädchen, -", "kız çocuğu", "girl", "noun", "A1", "Das Mädchen liest ein Märchenbuch.", "Kız çocuğu masal kitabı okuyor.", "The girl is reading a fairy tale book.", [], ["der Junge"]),
    ("der Jugendliche, -n", "genç (13-18 yaş)", "youth / adolescent", "noun", "A2", "Viele Jugendliche treiben gerne Sport.", "Pek çok genç spor yapmaktan hoşlanır.", "Many youths like doing sports.", ["der Teenager"], ["der Erwachsene"]),
    ("der Erwachsene, -n", "yetişkin", "adult", "noun", "A2", "Der Eintritt für Erwachsene kostet 12 Euro.", "Yetişkinler için giriş ücreti 12 Euro.", "Admission for adults costs 12 euros.", [], ["das Kind"]),
    ("der Freund, -e", "arkadaş, erkek arkadaş", "friend / boyfriend", "noun", "A1", "Mein bester Freund heißt Ali.", "En iyi arkadaşımın adı Ali'dir.", "My best friend's name is Ali.", ["der Kumpel"], ["der Feind"]),
    ("die Freundin, -nen", "kız arkadaş", "friend / girlfriend", "noun", "A1", "Ich gehe mit meiner Freundin ins Kino.", "Kız arkadaşımla sinemaya gidiyorum.", "I go to the movies with my girlfriend.", [], []),
    ("das Paar, -e", "çift", "couple", "noun", "A2", "Das junge Paar hat geheiratet.", "Genç çift evlendi.", "The young couple got married.", [], []),
    ("die Hochzeit, -en", "düğün", "wedding", "noun", "A1", "Wir sind zu einer Hochzeit eingeladen.", "Bir düğüne davetliyiz.", "We are invited to a wedding.", ["die Trauung"], []),
    ("die Ehe, -n", "evlilik", "marriage", "noun", "A2", "Sie führen eine glückliche Ehe.", "Mutlu bir evlilik sürdürüyorlar.", "They lead a happy marriage.", [], []),
    ("die Scheidung, -en", "boşanma", "divorce", "noun", "B1", "Nach der Scheidung blieben sie Freunde.", "Boşanmanın ardından arkadaş kaldılar.", "After the divorce they remained friends.", [], ["die Hochzeit"]),
    ("der Geburtstag, -e", "doğum günü", "birthday", "noun", "A1", "Herzlichen Glückwunsch zum Geburtstag!", "Doğum günün kutlu olsun!", "Happy Birthday!", [], []),
    ("das Fest, -e", "şenlik, bayram", "festival / celebration", "noun", "A1", "Das Stadtfest lockt viele Touristen an.", "Şehir şenliği pek çok turisti çekiyor.", "The town festival attracts many tourists.", ["die Feier"], []),
    ("die Feier, -n", "kutlama, parti", "celebration / party", "noun", "A1", "Die Feier dauerte bis tief in die Nacht.", "Kutlama gecenin geç saatlerine kadar sürdü.", "The celebration lasted deep into the night.", ["das Fest", "die Party"], []),
    ("der Gast, -¨e", "misafir, konuk", "guest", "noun", "A1", "Wir haben heute Abend Gäste.", "Bu akşam misafirlerimiz var.", "We have guests tonight.", ["der Besucher"], ["der Gastgeber"]),
    ("der Gastgeber, -", "ev sahibi (davet veren)", "host", "noun", "A2", "Der Gastgeber bot Getränke an.", "Ev sahibi içecek ikram etti.", "The host offered drinks.", [], ["der Gast"]),
    ("die Einladung, -en", "davetiye, davet", "invitation", "noun", "A1", "Danke für die freundliche Einladung!", "Nazik davetiniz için teşekkürler!", "Thanks for the kind invitation!", [], []),
    ("das Geschenk, -e", "hediye", "gift / present", "noun", "A1", "Das ist ein schönes Geschenk für dich.", "Bu senin için güzel bir hediye.", "That is a lovely gift for you.", ["die Gabe", "das Präsent"], []),

    # --- Körper & Gesundheit (Body & Health) ---
    ("der Körper, -", "vücut, beden", "body", "noun", "A1", "Sport hält den Körper gesund.", "Spor vücudu sağlıklı tutar.", "Sports keeps the body healthy.", ["der Leib"], []),
    ("der Kopf, -¨e", "baş, kafa", "head", "noun", "A1", "Mein Kopf tut heute weh.", "Bugün başım ağrıyor.", "My head hurts today.", [], []),
    ("das Gesicht, -er", "yüz, çehre", "face", "noun", "A1", "Sie wäscht sich das Gesicht mit kaltem Wasser.", "Yüzünü soğuk suyla yıkıyor.", "She washes her face with cold water.", [], []),
    ("das Auge, -n", "göz", "eye", "noun", "A1", "Er hat blaue Augen.", "Mavi gözleri var.", "He has blue eyes.", [], []),
    ("das Ohr, -en", "kulak", "ear", "noun", "A1", "Mein linkes Ohr tut weh.", "Sol kulağım ağrıyor.", "My left ear hurts.", [], []),
    ("die Nase, -n", "burun", "nose", "noun", "A1", "Seine Nase läuft wegen der Erkältung.", "Gripten dolayı burnu akıyor.", "His nose is running due to the cold.", [], []),
    ("der Mund, -¨er", "ağız", "mouth", "noun", "A1", "Öffnen Sie bitte den Mund!", "Lütfen ağzınızı açınız!", "Please open your mouth!", [], []),
    ("die Lippe, -n", "dudak", "lip", "noun", "A2", "Ihre Lippen sind trocken von der Kälte.", "Dudakları soğuktan kurumuş.", "Her lips are dry from the cold.", [], []),
    ("der Zahn, -¨e", "diş", "tooth", "noun", "A1", "Ich putze mir zweimal täglich die Zähne.", "Günde iki kez dişlerimi fırçalarım.", "I brush my teeth twice daily.", [], []),
    ("die Zunge, -n", "dil (organ)", "tongue", "noun", "A2", "Zeigen Sie mir bitte Ihre Zunge!", "Lütfen bana dilinizi gösteriniz!", "Please show me your tongue!", [], []),
    ("der Hals, -¨e", "boyun, boğaz", "neck / throat", "noun", "A1", "Ich habe starke Halsschmerzen.", "Şiddetli boğaz ağrım var.", "I have a severe sore throat.", [], []),
    ("die Schulter, -n", "omuz", "shoulder", "noun", "A2", "Er hat Schmerzen in der rechten Schulter.", "Sağ omzunda ağrılar var.", "He has pain in his right shoulder.", [], []),
    ("der Rücken, -", "sırt, bel", "back", "noun", "A1", "Mein Rücken schmerzt vom schweren Tragen.", "Ağır taşımaktan sırtım ağrıyor.", "My back aches from heavy lifting.", [], []),
    ("die Brust, -¨e", "göğüs", "chest / breast", "noun", "A2", "Er hat Schmerzen in der Brust.", "Göğsünde ağrı hissediyor.", "He has pain in his chest.", [], []),
    ("der Bauch, -¨e", "karın, göbek", "stomach / belly", "noun", "A1", "Das Kind klagt über Bauchschmerzen.", "Çocuk karın ağrısından şikayet ediyor.", "The child complains of a stomach ache.", ["der Magen"], []),
    ("der Magen, -¨", "mide", "stomach (organ)", "noun", "A2", "Mein Magen knurrt vor Hunger.", "Açlıktan midem gurulduyor.", "My stomach is growling with hunger.", ["der Bauch"], []),
    ("das Herz, -en", "kalp", "heart", "noun", "A2", "Sein Herz schlägt ruhig und kräftig.", "Kalbi sakin ve güçlü atıyor.", "His heart beats calmly and strongly.", [], []),
    ("die Lunge, -n", "akciğer", "lung", "noun", "B1", "Rauchen schädigt die Lunge.", "Sigara içmek akciğerlere zarar verir.", "Smoking damages the lungs.", [], []),
    ("die Haut (Sg.)", "cilt, deri", "skin", "noun", "A2", "Die Haut braucht Feuchtigkeit.", "Cildin neme ihtiyacı var.", "The skin needs moisture.", [], []),
    ("das Blut (Sg.)", "kan", "blood", "noun", "A2", "Der Arzt nimmt dem Patienten Blut ab.", "Doktor hastadan kan alıyor.", "The doctor draws blood from the patient.", [], []),
    ("der Arm, -e", "kol", "arm", "noun", "A1", "Er hat sich den linken Arm gebrochen.", "Sol kolunu kırdı.", "He broke his left arm.", [], ["das Bein"]),
    ("die Hand, -¨e", "el", "hand", "noun", "A1", "Wasch dir bitte die Hände!", "Lütfen ellerini yıka!", "Please wash your hands!", [], ["der Fuß"]),
    ("der Finger, -", "parmak (el)", "finger", "noun", "A1", "Er hat sich in den Finger geschnitten.", "Parmağını kesti.", "He cut his finger.", [], []),
    ("das Bein, -e", "bacak", "leg", "noun", "A1", "Meine Beine sind müde vom Gehen.", "Yürümekten bacaklarım yoruldu.", "My legs are tired from walking.", [], ["der Arm"]),
    ("das Knie, -", "diz", "knee", "noun", "A2", "Sein Knie ist nach dem Sturz geschwollen.", "Düşüşten sonra dizi şişti.", "His knee is swollen after the fall.", [], []),
    ("der Fuß, -¨e", "ayak", "foot", "noun", "A1", "Ich gehe jeden Tag zu Fuß.", "Her gün yayan giderim.", "I walk on foot every day.", [], ["die Hand"]),
    ("der Zeh, -en", "ayak parmağı", "toe", "noun", "A2", "Er hat sich den kleinen Zeh gestoßen.", "Küçük ayak parmağını çarptı.", "He stubbed his little toe.", [], []),
    ("der Schmerz, -en", "ağrı, sızı", "pain / ache", "noun", "A1", "Haben Sie Schmerzen beim Gehen?", "Yürürken ağrınız var mı?", "Do you have pain when walking?", ["das Weh"], []),
    ("die Krankheit, -en", "hastalık", "illness / disease", "noun", "A2", "Er hat die Krankheit gut überstanden.", "Hastalığı güzelce atlattı.", "He got through the illness well.", ["das Leiden"], ["die Gesundheit"]),
    ("die Gesundheit (Sg.)", "sağlık", "health", "noun", "A1", "Gesundheit ist das Wichtigste im Leben.", "Sağlık hayattaki en önemli şeydir.", "Health is the most important thing in life.", [], ["die Krankheit"]),
    ("die Erkältung, -en", "soğuk algınlığı", "cold (illness)", "noun", "A2", "Ich habe eine schwere Erkältung.", "Ağır bir soğuk algınlığım var.", "I have a bad cold.", ["der Schnupfen"], []),
    ("das Fieber (Sg.)", "ateş (vücut)", "fever", "noun", "A1", "Das Kind hat hohes Fieber.", "Çocuğun yüksek ateşi var.", "The child has a high fever.", [], []),
    ("der Husten (Sg.)", "öksürük", "cough", "noun", "A2", "Gegen den Husten nehme ich Hustensaft.", "Öksürüğe karşı öksürük şurubu alıyorum.", "For the cough I take cough syrup.", [], []),
    ("der Schnupfen (Sg.)", "nezle", "runny nose / sniffles", "noun", "A2", "Bei Schnupfen hilft Inhalieren.", "Nezleye buğu solumak iyi gelir.", "With sniffles inhalation helps.", ["die Erkältung"], []),
    ("die Grippe, -n", "grip", "influenza / flu", "noun", "A2", "Er liegt mit einer echten Grippe im Bett.", "Gerçek bir griple yatakta yatıyor.", "He is in bed with real flu.", [], []),
    ("die Wunde, -n", "yara", "wound / cut", "noun", "A2", "Die Wunde muss genäht werden.", "Yaranın dikilmesi gerekiyor.", "The wound needs to be stitched.", ["die Verletzung"], []),
    ("die Verletzung, -en", "yaralanma", "injury", "noun", "B1", "Die Verletzung am Bein heilt langsam.", "Bacaktaki yaralanma yavaş iyileşiyor.", "The injury on the leg heals slowly.", ["die Wunde"], []),
    ("der Unfall, -¨e", "kaza", "accident", "noun", "A1", "Zum Glück gab es beim Unfall keine Verletzten.", "Neyse ki kazada yaralanan olmadı.", "Fortunately there were no injuries in the accident.", [], []),
    ("die Notaufnahme, -n", "acil servis", "emergency room", "noun", "A2", "Der Krankenwagen brachte ihn in die Notaufnahme.", "Cankurtaran onu acil servise getirdi.", "The ambulance brought him to the emergency room.", [], []),
    ("der Krankenwagen, -", "ambulans", "ambulance", "noun", "A1", "Rufen Sie sofort einen Krankenwagen!", "Hemen bir ambulans çağırın!", "Call an ambulance immediately!", ["der Rettungswagen"], []),
    ("das Krankenhaus, -¨er", "hastane", "hospital", "noun", "A1", "Er liegt seit drei Tagen im Krankenhaus.", "Üç gündür hastanede yatıyor.", "He has been in the hospital for three days.", ["die Klinik"], []),
    ("die Praxis, Praxen", "muayenehane", "doctor's practice / surgery", "noun", "A1", "Die Praxis Dr. Weber öffnet um 8 Uhr.", "Dr. Weber muayenehanesi saat 8'de açılıyor.", "Dr. Weber's practice opens at 8 am.", [], []),
    ("der Arzt, -¨e", "doktor (erkek)", "doctor / physician (male)", "noun", "A1", "Gehen Sie lieber zum Arzt!", "İyisi mi doktora gidiniz!", "You had better see a doctor!", ["der Doktor", "der Mediziner"], []),
    ("die Ärztin, -nen", "doktor (kadın)", "doctor / physician (female)", "noun", "A1", "Die Ärztin verschrieb mir Tabletten.", "Doktor kadın bana haplar yazdı.", "The female doctor prescribed me tablets.", [], []),
    ("der Patient, -en", "hasta (erkek)", "patient (male)", "noun", "A2", "Der Patient wartet im Wartezimmer.", "Hasta bekleme odasında bekliyor.", "The patient is waiting in the waiting room.", [], []),
    ("die Patientin, -nen", "hasta (kadın)", "patient (female)", "noun", "A2", "Die Patientin wurde gründlich untersucht.", "Hasta kadın etraflıca muayene edildi.", "The female patient was examined thoroughly.", [], []),
    ("das Wartezimmer, -", "bekleme odası", "waiting room", "noun", "A1", "Das Wartezimmer beim Arzt ist voll.", "Doktordaki bekleme odası dolu.", "The waiting room at the doctor is full.", [], []),
    ("die Apotheke, -n", "eczane", "pharmacy / chemist's", "noun", "A1", "Ich hole das Medikament aus der Apotheke.", "İlacı eczaneden alıyorum.", "I get the medicine from the pharmacy.", [], []),
    ("das Medikament, -e", "ilaç", "medicine / medication", "noun", "A1", "Nehmen Sie dieses Medikament nach dem Essen.", "Bu ilacı yemekten sonra alınız.", "Take this medication after meals.", ["die Arznei", "das Heilmittel"], []),
    ("die Tablette, -n", "hap, tablet", "pill / tablet", "noun", "A1", "Nehmen Sie täglich zwei Tabletten.", "Günde iki tablet alınız.", "Take two tablets daily.", ["die Pille"], []),
    ("die Salbe, -n", "merhem, krem", "ointment / salve", "noun", "A2", "Tragen Sie die Salbe dünn auf die Haut auf.", "Merhemi cilde ince bir tabaka halinde sürün.", "Apply the ointment thinly to the skin.", ["die Creme"], []),
    ("das Pflaster, -", "yara bandı", "band-aid / plaster", "noun", "A1", "Kleben Sie ein Pflaster auf die Wunde.", "Yaraya bir yara bandı yapıştırın.", "Stick a band-aid on the wound.", [], []),
    ("der Verband, -¨e", "sargı bezi, dernek", "bandage / association", "noun", "A2", "Der Verband muss täglich gewechselt werden.", "Sargının her gün değiştirilmesi gerekir.", "The bandage must be changed daily.", [], []),
    ("das Rezept, -e", "reçete, yemek tarifi", "prescription / recipe", "noun", "A1", "Dieses Medikament gibt es nur auf Rezept.", "Bu ilaç sadece reçeteyle verilir.", "This medicine is only available on prescription.", [], []),
    ("die Krankenversicherung, -en", "sağlık sigortası", "health insurance", "noun", "A2", "In Deutschland ist die Krankenversicherung Pflicht.", "Almanya'da sağlık sigortası zorunludur.", "Health insurance is compulsory in Germany.", ["die Krankenkasse"], []),
    ("die Versichertenkarte, -n", "sağlık sigorta kartı", "health insurance card", "noun", "A1", "Bitte legen Sie Ihre Versichertenkarte vor.", "Lütfen sigorta kartınızı ibraz ediniz.", "Please present your insurance card.", [], []),
]

print(f"Loaded {len(NOUNS_P1)} nouns in nouns_part1.py")
