# scripts/vocab_sources/verbs_a1_a2.py
"""
Core A1 & A2 Verbs with principal parts, TR/EN meanings, example sentences, synonyms, antonyms.
"""

VERBS_A1_A2 = [
    # Top Core Auxiliary & Modal Verbs
    ("sein (ist, war, ist gewesen)", "olmak", "to be", "verb", "A1", "Er ist mein bester Freund.", "O benim en iyi arkadaşımdır.", "He is my best friend.", ["existieren"], []),
    ("haben (hat, hatte, hat gehabt)", "sahip olmak", "to have", "verb", "A1", "Ich habe zwei Kinder.", "İki çocuğum var.", "I have two children.", ["besitzen"], []),
    ("werden (wird, wurde, ist geworden)", "olmak, haline gelmek", "to become", "verb", "A1", "Er möchte Arzt werden.", "O doktor olmak istiyor.", "He wants to become a doctor.", [], []),
    ("können (kann, konnte, hat gekonnt)", "-ebilmek, yapabilmek", "can / to be able to", "verb", "A1", "Kannst du Deutsch sprechen?", "Almanca konuşabiliyor musun?", "Can you speak German?", ["vermögen"], []),
    ("müssen (muss, musste, hat gemusst)", "zorunda olmak", "must / to have to", "verb", "A1", "Ich muss heute pünktlich sein.", "Bugün zamanında olmak zorundayım.", "I must be on time today.", [], []),
    ("wollen (will, wollte, hat gewollt)", "istemek (niyet)", "to want", "verb", "A1", "Wir wollen ein Haus kaufen.", "Bir ev satın almak istiyoruz.", "We want to buy a house.", ["beabsichtigen"], []),
    ("sollen (soll, sollte, hat gesollt)", "-meli/-malı (tavsiye)", "should / ought to", "verb", "A1", "Du sollst mehr Obst essen.", "Daha fazla meyve yemelisin.", "You should eat more fruit.", [], []),
    ("dürfen (darf, durfte, hat gedurft)", "izinli olmak", "may / to be allowed to", "verb", "A1", "Darf ich hier parken?", "Buraya park edebilir miyim?", "May I park here?", ["erlaubt sein"], ["verbieten"]),
    ("mögen (mag, mochte, hat gemocht)", "sevmek, hoşlanmak", "to like", "verb", "A1", "Ich mag frischen Orangensaft.", "Taze portakal suyunu çok severim.", "I like fresh orange juice.", ["gernhaben"], ["hassen"]),
    ("möchten (möchte)", "istemek (kibarca)", "would like", "verb", "A1", "Ich möchte einen Termin vereinbaren.", "Bir randevu ayarlamak istiyorum.", "I would like to make an appointment.", ["wollen"], []),
    ("wissen (weiß, wusste, hat gewusst)", "bilmek (bilgi)", "to know (fact)", "verb", "A1", "Ich weiß nicht, wo er wohnt.", "Nerede oturduğunu bilmiyorum.", "I don't know where he lives.", ["kennen"], []),

    # Daily Movement & Activity Verbs
    ("gehen (geht, ging, ist gegangen)", "gitmek, yürümek", "to go / walk", "verb", "A1", "Wir gehen spazieren.", "Yürüyüşe gidiyoruz.", "We are going for a walk.", ["laufen"], ["kommen", "bleiben"]),
    ("kommen (kommt, kam, ist gekommen)", "gelmek", "to come", "verb", "A1", "Kommst du heute Abend zu uns?", "Bu akşam bize geliyor musun?", "Are you coming to our place tonight?", ["anreisen"], ["gehen", "fortgehen"]),
    ("fahren (fährt, fuhr, ist gefahren)", "sürmek, araçla gitmek", "to drive / ride", "verb", "A1", "Er fährt jeden Tag mit der Bahn.", "Her gün trenle gidiyor.", "He rides the train every day.", ["steuern"], ["gehen"]),
    ("fliegen (fliegt, flog, ist geflogen)", "uçmak", "to fly", "verb", "A1", "Das Flugzeug fliegt nach Berlin.", "Uçak Berlin'e uçuyor.", "The plane is flying to Berlin.", [], []),
    ("laufen (läuft, lief, ist gelaufen)", "koşmak, yürümek", "to run / walk", "verb", "A1", "Die Kinder laufen im Garten.", "Çocuklar bahçede koşuyor.", "The children are running in the garden.", ["rennen", "joggen"], ["stehen"]),
    ("rennen (rennt, rannte, ist gerannt)", "koşmak, fırlamak", "to run fast", "verb", "A2", "Er rennt zum Bus.", "Otobüse doğru koşuyor.", "He is running to the bus.", ["laufen", "eilen"], ["bummeln"]),
    ("schwimmen (schwimmt, schwamm, ist geschwommen)", "yüzmek", "to swim", "verb", "A1", "Im Sommer schwimme ich im See.", "Yazın gölde yüzerim.", "In summer I swim in the lake.", ["baden"], []),
    ("reisen (reist, reiste, ist gereist)", "seyahat etmek", "to travel", "verb", "A1", "Ich reise sehr gerne.", "Seyahat etmeyi çok severim.", "I love traveling.", ["verreisen"], ["daheimbleiben"]),
    ("abfahren (fährt ab, fuhr ab, ist abgefahren)", "hareket etmek (araç)", "to depart", "verb", "A1", "Der Zug fährt um 10 Uhr ab.", "Tren saat 10'da hareket ediyor.", "The train departs at 10 o'clock.", ["starten"], ["ankommen"]),
    ("ankommen (kommt an, kam an, ist angekommen)", "varmak, ulaşmak", "to arrive", "verb", "A1", "Wann kommt der Zug an?", "Tren ne zaman varıyor?", "When does the train arrive?", ["eintreffen"], ["abfahren"]),
    ("einsteigen (steigt ein, stieg ein, ist eingestiegen)", "binmek (araca)", "to board / get in", "verb", "A1", "Bitte steigen Sie schnell ein!", "Lütfen hızlıca bininiz!", "Please get in quickly!", [], ["aussteigen"]),
    ("aussteigen (steigt aus, stieg aus, ist ausgestiegen)", "inmek (araçtan)", "to get off / exit", "verb", "A1", "Wir müssen an der nächsten Haltestelle aussteigen.", "Sonraki durakta inmemiz gerekiyor.", "We have to get off at the next stop.", [], ["einsteigen"]),
    ("umsteigen (steigt um, stieg um, ist umgestiegen)", "aktarma yapmak", "to transfer / change trains", "verb", "A1", "In Frankfurt müssen wir umsteigen.", "Frankfurt'ta aktarma yapmamız gerekiyor.", "We have to change trains in Frankfurt.", [], []),
    ("abfliegen (fliegt ab, flog ab, ist abgeflogen)", "havalanmak, uçuşa geçmek", "to take off / depart by plane", "verb", "A2", "Das Flugzeug fliegt pünktlich ab.", "Uçak zamanında kalkıyor.", "The plane departs on time.", ["starten"], ["landen"]),
    ("landen (landet, landete, ist gelandet)", "inmek (uçak)", "to land", "verb", "A2", "Wir landen in einer Stunde.", "Bir saat içinde iniş yapıyoruz.", "We land in an hour.", [], ["abfliegen", "starten"]),
    ("mitkommen (kommt mit, kam mit, ist mitgekommen)", "birlikte gelmek", "to come along", "verb", "A1", "Kommst du ins Kino mit?", "Sinemaya bizimle geliyor musun?", "Are you coming along to the cinema?", ["begleiten"], []),
    ("mitnehmen (nimmt mit, nahm mit, hat mitgenommen)", "yanına almak", "to take along", "verb", "A1", "Vergiss nicht, einen Regenschirm mitzunehmen.", "Yanına bir şemsiye almayı unutma.", "Don't forget to take an umbrella along.", [], ["dalassen"]),
    ("bringen (bringt, brachte, hat gebracht)", "getirmek", "to bring", "verb", "A1", "Bringen Sie mir bitte die Speisekarte.", "Bana lütfen menüyü getirin.", "Please bring me the menu.", ["holen"], ["wegbringen"]),
    ("mitbringen (bringt mit, brachte mit, hat mitgebracht)", "yanında getirmek", "to bring along", "verb", "A1", "Ich bringe einen Kuchen mit.", "Yanımda bir pasta getiriyorum.", "I am bringing a cake along.", [], []),
    ("holen (holt, holte, hat geholt)", "gidip getirmek, almak", "to fetch / get", "verb", "A1", "Ich hole schnell Brot vom Bäcker.", "Fırından hemen ekmek alıp geliyorum.", "I quickly fetch bread from the bakery.", ["besorgen"], []),

    # Routine, Home & Daily Life
    ("arbeiten (arbeitet, arbeitete, hat gearbeitet)", "çalışmak", "to work", "verb", "A1", "Er arbeitet als Ingenieur.", "O mühendis olarak çalışıyor.", "He works as an engineer.", ["tätig sein"], ["faulenzen"]),
    ("wohnen (wohnt, wohnte, hat gewohnt)", "oturmak, ikamet etmek", "to live / reside", "verb", "A1", "Ich wohne in einer ruhigen Straße.", "Sakin bir sokakta oturuyorum.", "I live in a quiet street.", ["leben"], []),
    ("leben (lebt, lebte, hat gelebt)", "yaşamak", "to live", "verb", "A1", "Wie lange leben Sie schon hier?", "Ne zamandır burada yaşıyorsunuz?", "How long have you lived here?", ["wohnen"], ["sterben"]),
    ("schlafen (schläft, schlief, hat geschlafen)", "uyumak", "to sleep", "verb", "A1", "Das Baby schläft ruhig.", "Bebek sessizce uyuyor.", "The baby is sleeping quietly.", ["ruhen"], ["wachen"]),
    ("aufstehen (steht auf, stand auf, ist aufgestanden)", "kalkmak", "to get up", "verb", "A1", "Ich stehe um sieben Uhr auf.", "Saat yedide kalkıyorum.", "I get up at seven o'clock.", ["erwachen"], ["schlafenlegen"]),
    ("aufwachen (wacht auf, wachte auf, ist aufgewacht)", "uyanmak", "to wake up", "verb", "A1", "Ich wache meist früh auf.", "Genelde erken uyanırım.", "I usually wake up early.", ["erwachen"], ["einschlafen"]),
    ("einschlafen (schläft ein, schlief ein, ist eingeschlafen)", "uykuya dalmak", "to fall asleep", "verb", "A2", "Gestern bin ich spät eingeschlafen.", "Dün geç uykuya daldım.", "Yesterday I fell asleep late.", [], ["aufwachen"]),
    ("duschen (duscht, duschte, hat geduscht)", "duş almak", "to shower", "verb", "A1", "Morgens dusche ich mich warm.", "Sabahları sıcak duş alırım.", "In the morning I take a warm shower.", ["baden"], []),
    ("baden (badet, badete, hat gebadet)", "banyo yapmak", "to bathe", "verb", "A1", "Am Sonntag bade ich gerne lange.", "Pazar günleri uzun banyo yapmayı severim.", "On Sunday I like to take a long bath.", ["duschen"], []),
    ("waschen (wäscht, wusch, hat gewaschen)", "yıkamak", "to wash", "verb", "A1", "Ich wasche mir die Hände.", "Ellerimi yıkıyorum.", "I wash my hands.", ["reinigen"], ["beschmutzen"]),
    ("putzen (putzt, putzte, hat geputzt)", "temizlemek, fırçalamak", "to clean / brush", "verb", "A1", "Ich putze mir die Zähne.", "Dişlerimi fırçalıyorum.", "I brush my teeth.", ["reinigen", "säubern"], ["schmutzig machen"]),
    ("aufräumen (räumt auf, räumte auf, hat aufgeräumt)", "toparlamak, düzenlemek", "to tidy up / clean up", "verb", "A1", "Räum bitte dein Zimmer auf!", "Lütfen odanı topla!", "Please tidy up your room!", ["ordnen"], ["verunreinigen"]),
    ("kochen (kocht, kochte, hat gekocht)", "yemek pişirmek", "to cook", "verb", "A1", "Wer kocht heute das Abendessen?", "Bugün akşam yemeğini kim pişiriyor?", "Who is cooking dinner today?", ["zubereiten"], []),
    ("backen (bäckt, backte, hat gebacken)", "fırında pişirmek", "to bake", "verb", "A1", "Meine Oma backt leckere Kekse.", "Büyükannem lezzetli kurabiyeler pişiriyor.", "My grandma bakes delicious cookies.", [], []),
    ("braten (brät, briet, hat gebraten)", "kızartmak", "to fry / roast", "verb", "A2", "Er brät Fleisch in der Pfanne.", "Tavada et kızartıyor.", "He is frying meat in the pan.", [], []),
    ("essen (isst, aß, hat gegessen)", "yemek", "to eat", "verb", "A1", "Isst du gerne Fisch?", "Balık yemeyi sever misin?", "Do you like eating fish?", ["speisen"], ["fasten"]),
    ("trinken (trinkt, trank, hat getrunken)", "içmek", "to drink", "verb", "A1", "Trink bitte mehr Wasser!", "Lütfen daha çok su iç!", "Please drink more water!", [], []),
    ("frühstücken (frühstückt, frühstückte, hat gefrühstückt)", "kahvaltı yapmak", "to have breakfast", "verb", "A1", "Wir frühstücken immer zusammen.", "Her zaman birlikte kahvaltı yaparız.", "We always have breakfast together.", [], []),
    ("schmecken (schmeckt, schmeckte, hat geschmeckt)", "tadında olmak, lezzetli olmak", "to taste (good)", "verb", "A1", "Das Essen schmeckt fantastisch!", "Yemek harika bir lezzette!", "The food tastes fantastic!", ["mundig sein"], []),
    ("probieren (probiert, probierte, hat probiert)", "tatmak, denemek", "to try / taste", "verb", "A1", "Probier mal diese Suppe!", "Bu çorbayı bir dene!", "Try this soup!", ["kosten", "versuchen"], []),

    # Communication, Language & Mind
    ("sprechen (spricht, sprach, hat gesprochen)", "konuşmak", "to speak", "verb", "A1", "Wir sprechen über Politik.", "Politika hakkında konuşuyoruz.", "We speak about politics.", ["reden"], ["schweigen"]),
    ("reden (redet, redete, hat geredet)", "konuşmak, sohbet etmek", "to talk", "verb", "A1", "Lass uns morgen reden.", "Yarın konuşalım.", "Let's talk tomorrow.", ["sprechen"], ["schweigen"]),
    ("sagen (sagt, sagte, hat gesagt)", "söylemek", "to say", "verb", "A1", "Was hast du gesagt?", "Ne söyledin?", "What did you say?", ["äußern"], []),
    ("erzählen (erzählt, erzählte, hat erzählt)", "anlatmak", "to tell / narrate", "verb", "A1", "Erzähl mir eine Geschichte!", "Bana bir hikaye anlat!", "Tell me a story!", ["berichten"], ["verschweigen"]),
    ("berichten (berichtet, berichtete, hat berichtet)", "rapor etmek, bildirmek", "to report", "verb", "A2", "Die Zeitung berichtet über den Unfall.", "Gazete kaza hakkında haber yapıyor.", "The newspaper reports about the accident.", ["erzählen", "melden"], []),
    ("fragen (fragt, fragte, hat gefragt)", "sormak", "to ask", "verb", "A1", "Ich möchte Sie etwas fragen.", "Size bir şey sormak istiyorum.", "I would like to ask you something.", ["erkundigen"], ["antworten"]),
    ("antworten (antwortet, antwortete, hat geantwortet)", "cevap vermek", "to answer", "verb", "A1", "Er antwortet schnell auf Briefe.", "Mektuplara hızlı cevap verir.", "He answers letters quickly.", ["erwidern"], ["fragen"]),
    ("beantworten (beantwortet, beantwortete, hat beantwortet)", "yanıtlamak (nesneyle)", "to answer (a question)", "verb", "A2", "Bitte beantworten Sie alle Fragen.", "Lütfen tüm soruları yanıtlayınız.", "Please answer all questions.", ["antworten auf"], []),
    ("erklären (erklärt, erklärte, hat erklärt)", "açıklamak", "to explain", "verb", "A1", "Können Sie die Grammatikregel erklären?", "Gramer kuralını açıklayabilir misiniz?", "Can you explain the grammar rule?", ["erläutern"], ["verwirren"]),
    ("verstehen (versteht, verstand, hat verstanden)", "anlamak", "to understand", "verb", "A1", "Haben Sie alles verstanden?", "Her şeyi anladınız mı?", "Did you understand everything?", ["begreifen"], ["missverstehen"]),
    ("begreifen (begreift, begriff, hat begriffen)", "kavramak, idrak etmek", "to comprehend", "verb", "A2", "Ich begreife dieses Problem nicht.", "Bu sorunu kavrayamıyorum.", "I don't comprehend this problem.", ["verstehen"], []),
    ("meinen (meint, meinte, hat gemeint)", "kastetmek, düşünmek", "to mean / think", "verb", "A1", "Was meinst du damit?", "Bununla ne demek istiyorsun?", "What do you mean by that?", ["denken", "glauben"], []),
    ("denken (denkt, dachte, hat gedacht)", "düşünmek", "to think", "verb", "A1", "Ich denke, dass du recht hast.", "Bence sen haklısın.", "I think that you are right.", ["glauben"], []),
    ("glauben (glaubt, glaubte, hat geglaubt)", "inanmak, sanmak", "to believe / think", "verb", "A1", "Ich glaube dir kein Wort.", "Sana tek bir kelime bile inanmıyorum.", "I don't believe a word you say.", ["vertrauen"], ["zweifeln"]),
    ("wünschen (wünscht, wünschte, hat gewünscht)", "dilemek, istemek", "to wish", "verb", "A1", "Ich wünsche dir alles Gute zum Geburtstag!", "Doğum günün kutlu olsun!", "I wish you all the best for your birthday!", ["hoffen"], []),
    ("hoffen (hofft, hoffte, hat gehofft)", "umut etmek", "to hope", "verb", "A2", "Wir hoffen auf gutes Wetter.", "Havanın güzel olmasını umuyoruz.", "We hope for good weather.", ["erwarten"], ["verzweifeln"]),
    ("vergessen (vergisst, vergaß, hat vergessen)", "unutmak", "to forget", "verb", "A1", "Vergiss bitte deinen Ausweis nicht!", "Kimliğini lütfen unutma!", "Please don't forget your ID!", [], ["erinnern"]),
    ("erinnern (erinnert, erinnerte, hat erinnert)", "hatırlamak, hatırlatmak", "to remember / remind", "verb", "A2", "Ich erinnere mich gut an jenen Tag.", "O günü çok iyi hatırlıyorum.", "I remember that day well.", ["gedenken"], ["vergessen"]),
    ("wiederholen (wiederholt, wiederholte, hat wiederholt)", "tekrar etmek", "to repeat", "verb", "A1", "Könnten Sie das bitte wiederholen?", "Bunu lütfen tekrar edebilir misiniz?", "Could you please repeat that?", ["nochmals sagen"], []),

    # Social, Family & Interaction
    ("kennen (kennt, kannte, hat gekannt)", "tanımak, bilmek", "to know (a person/place)", "verb", "A1", "Kennst du meinen Bruder?", "Kardeşimi tanıyor musun?", "Do you know my brother?", ["vertraut sein"], []),
    ("kennenlernen (lernt kennen, lernte kennen, hat kennengelernt)", "tanışmak", "to get to know / meet", "verb", "A1", "Ich möchte neue Leute kennenlernen.", "Yeni insanlarla tanışmak istiyorum.", "I want to get to know new people.", ["bekannt werden mit"], []),
    ("treffen (trifft, traf, hat getroffen)", "buluşmak", "to meet", "verb", "A1", "Wir treffen uns um 18 Uhr vor dem Theater.", "Saat 18'de tiyatronun önünde buluşuyoruz.", "We meet at 6 pm in front of the theater.", ["zusammenkommen"], []),
    ("einladen (lädt ein, lud ein, hat eingeladen)", "davet etmek", "to invite", "verb", "A1", "Darf ich dich zum Essen einladen?", "Seni yemeğe davet edebilir miyim?", "May I invite you to dinner?", ["bitten"], ["ausladen"]),
    ("besuchen (besucht, besuchte, hat besucht)", "ziyaret etmek", "to visit", "verb", "A1", "Wir besuchen am Wochenende unsere Verwandten.", "Hafta sonu akrabalarımızı ziyaret ediyoruz.", "We are visiting our relatives on the weekend.", ["aufsuchen"], []),
    ("helfen (hilft, half, hat geholfen)", "yardım etmek", "to help", "verb", "A1", "Er hilft seiner Nachbarin beim Tragen.", "Komşusuna taşımada yardım ediyor.", "He helps his neighbor carry things.", ["unterstützen"], ["schaden"]),
    ("unterstützen (unterstützt, unterstützte, hat unterstützt)", "desteklemek", "to support", "verb", "A2", "Meine Eltern unterstützen mich beim Studium.", "Ailem eğitimimde beni destekliyor.", "My parents support me in my studies.", ["helfen", "fördern"], ["behindern"]),
    ("schenken (schenkt, schenkte, hat geschenkt)", "hediye etmek", "to gift / give", "verb", "A1", "Ich schenke ihr ein schönes Buch.", "Ona güzel bir kitap hediye ediyorum.", "I give her a nice book as a gift.", ["geben"], []),
    ("gratulieren (gratuliert, gratulierte, hat gratuliert)", "tebrik etmek", "to congratulate", "verb", "A1", "Ich gratuliere dir herzlich zum Erfolg!", "Başarını yürekten tebrik ederim!", "I congratulate you warmly on your success!", ["beglückwünschen"], []),
    ("danken (dankt, dankte, hat gedankt)", "teşekkür etmek", "to thank", "verb", "A1", "Ich danke Ihnen für Ihre Hilfe.", "Yardımınız için size teşekkür ederim.", "I thank you for your help.", ["bedanken"], []),
    ("lieben (liebt, liebte, hat geliebt)", "sevmek", "to love", "verb", "A1", "Ich liebe meine Familie.", "Ailemi seviyorum.", "I love my family.", ["gernhaben"], ["hassen"]),
    ("hassen (hasst, hasste, hat gehasst)", "nefret etmek", "to hate", "verb", "A2", "Ich hasse Unpünktlichkeit.", "Dakik olmamaktan nefret ederim.", "I hate unpunctuality.", ["verabscheuen"], ["lieben"]),
    ("heiraten (heiratet, heiratete, hat geheiratet)", "evlenmek", "to marry", "verb", "A1", "Sie haben letztes Jahr geheiratet.", "Geçen yıl evlendiler.", "They got married last year.", ["ehelichen"], ["scheiden lassen"]),
    ("trennen (trennt, trennte, hat getrennt)", "ayrılmak, ayırmak", "to separate", "verb", "A2", "Sie haben sich nach fünf Jahren getrennt.", "Beş yılın ardından ayrıldılar.", "They separated after five years.", ["scheiden"], ["verbinden", "vereinigen"]),
    ("streiten (streitet, stritt, hat gestritten)", "tartışmak, kavga etmek", "to argue / fight", "verb", "A2", "Die Geschwister streiten oft.", "Kardeşler sık sık kavga eder.", "The siblings often argue.", ["zanken"], ["vertragen"]),
    ("vertragen (verträgt, vertrug, hat vertragen)", "anlaşmak, tahammül etmek", "to get along / tolerate", "verb", "A2", "Die Kinder vertragen sich wieder gut.", "Çocuklar yeniden iyi anlaşıyor.", "The children get along well again.", ["auskommen"], ["streiten"]),

    # Work, Study & Commerce
    ("arbeiten (arbeitet, arbeitete, hat gearbeitet)", "çalışmak", "to work", "verb", "A1", "Wo arbeiten Sie?", "Nerede çalışıyorsunuz?", "Where do you work?", ["tätig sein"], ["faulenzen"]),
    ("verdienen (verdient, verdiente, hat verdient)", "para kazanmak, hak etmek", "to earn / deserve", "verb", "A1", "Er verdient ein gutes Gehalt.", "İyi bir maaş kazanıyor.", "He earns a good salary.", ["einnehmen"], ["verlieren"]),
    ("sparen (spart, sparte, hat gespart)", "tasarruf etmek, biriktirmek", "to save (money)", "verb", "A1", "Wir sparen für ein neues Auto.", "Yeni bir araba için para biriktiriyoruz.", "We are saving for a new car.", ["zurücklegen"], ["ausgeben", "verschwenden"]),
    ("ausgeben (gibt aus, gab aus, hat ausgegeben)", "harcamak (para)", "to spend (money)", "verb", "A2", "Sie gibt viel Geld für Kleidung aus.", "Kıyafete çok para harcıyor.", "She spends a lot of money on clothes.", ["zahlen"], ["sparen"]),
    ("kaufen (kauft, kaufte, hat gekauft)", "satın almak", "to buy", "verb", "A1", "Ich kaufe im Supermarkt ein.", "Süpermarketten alışveriş yapıyorum.", "I buy things in the supermarket.", ["erwerben"], ["verkaufen"]),
    ("verkaufen (verkauft, verkaufte, hat verkauft)", "satmak", "to sell", "verb", "A1", "Wir verkaufen unser altes Fahrrad.", "Eski bisikletimizi satıyoruz.", "We are selling our old bicycle.", ["anbieten"], ["kaufen"]),
    ("bestellen (bestellt, bestellte, hat bestellt)", "sipariş vermek", "to order", "verb", "A1", "Haben Sie schon bestellt?", "Siparişinizi verdiniz mi?", "Have you already ordered?", ["ordern"], ["abbestellen"]),
    ("liefern (liefert, lieferte, hat geliefert)", "teslim etmek, göndermek", "to deliver", "verb", "A2", "Die Firma liefert die Möbel morgen.", "Firma mobilyaları yarın teslim edecek.", "The company will deliver the furniture tomorrow.", ["zustellen"], ["abholen"]),
    ("abholen (holt ab, holte ab, hat abgeholt)", "gidip almak, karşılamak", "to pick up", "verb", "A1", "Ich hole dich vom Bahnhof ab.", "Seni tren istasyonundan alacağım.", "I will pick you up from the train station.", ["empfangen"], ["hinbringen"]),
    ("zahlen (zahlt, zahlte, hat gezahlt)", "ödemek", "to pay", "verb", "A1", "Ich möchte bitte zahlen.", "Hesabı ödemek istiyorum lütfen.", "I would like to pay, please.", ["bezahlen"], []),
    ("kosten (kostet, kostete, hat gekostet)", "mal olmak, tutmak", "to cost", "verb", "A1", "Das Hemd kostet 29 Euro.", "Gömlek 29 Euro tutuyor.", "The shirt costs 29 euros.", ["betragen"], []),
    ("rechnen (rechnet, rechnete, hat gerechnet)", "hesaplamak", "to calculate", "verb", "A2", "Der Lehrer rechnet die Aufgabe an der Tafel.", "Öğretmen tahtadaki problemi hesaplıyor.", "The teacher calculates the problem on the board.", ["kalkulieren"], []),
    ("mieten (mietet, mietete, hat gemietet)", "kiralamak (kiracı olarak)", "to rent (as tenant)", "verb", "A1", "Wir mieten eine Wohnung im Zentrum.", "Merkezde bir daire kiralıyoruz.", "We are renting an apartment in the center.", ["leihen"], ["vermieten"]),
    ("vermieten (vermietet, vermietete, hat vermietet)", "kiraya vermek (ev sahibi olarak)", "to rent out", "verb", "A2", "Der Vermieter vermietet zwei Zimmer.", "Ev sahibi iki oda kiraya veriyor.", "The landlord rents out two rooms.", [], ["mieten"]),
    ("kündigen (kündigt, kündigte, hat gekündigt)", "feshetmek, istifa etmek", "to cancel / quit a job", "verb", "A2", "Er hat seine Stelle gekündigt.", "O işinden istifa etti.", "He quit his job.", ["beenden"], ["einstellen"]),
    ("unterschreiben (unterschreibt, unterschrieb, hat unterschrieben)", "imzalamak", "to sign", "verb", "A2", "Bitte unterschreiben Sie den Vertrag hier.", "Lütfen sözleşmeyi buradan imzalayınız.", "Please sign the contract here.", ["signieren"], []),
    ("studieren (studiert, studierte, hat studiert)", "üniversite okumak", "to study at university", "verb", "A1", "Mein Sohn studiert Medizin.", "Oğlum tıp okuyor.", "My son is studying medicine.", ["lernen"], []),
    ("prüfen (prüft, prüfte, hat geprüft)", "sınamak, denetlemek", "to examine / check", "verb", "A2", "Der Prüfer prüft die Sprachkenntnisse.", "Sınav görevlisi dil bilgisini sınıyor.", "The examiner tests the language skills.", ["kontrollieren", "testen"], []),
    ("bestehen (besteht, bestand, hat bestanden)", "başarmak, geçmek (sınav)", "to pass (exam)", "verb", "A2", "Sie hat die B1-Prüfung bestanden!", "B1 sınavını başarıyla geçti!", "She passed the B1 exam!", ["schaffen"], ["durchfallen"]),
    ("durchfallen (fällt durch, fiel durch, ist durchgefallen)", "sınavda kalmak", "to fail an exam", "verb", "A2", "Niemand ist durchgefallen.", "Kimse sınavda kalmadı.", "Nobody failed the exam.", ["scheitern"], ["bestehen"]),

    # Body, Health & Feelings
    ("fühlen (fühlt, fühlte, hat gefühlt)", "hissetmek", "to feel", "verb", "A1", "Ich fühle mich heute sehr gut.", "Bugün kendimi çok iyi hissediyorum.", "I feel very good today.", ["spüren"], []),
    ("schmerzen (schmerzt, schmerzte, hat geschmerzt)", "ağrımak, acımak", "to ache / hurt", "verb", "A2", "Mein Kopf schmerzt schrecklich.", "Başım korkunç ağrıyor.", "My head aches terribly.", ["wehtun"], []),
    ("wehtun (tut weh, tat weh, hat wehgetan)", "acımak, ağrımak", "to hurt", "verb", "A1", "Mein Rücken tut weh.", "Belim ağrıyor.", "My back hurts.", ["schmerzen"], []),
    ("husten (hustet, hustete, hat gehustet)", "öksürmek", "to cough", "verb", "A2", "Das Kind hustet schon die ganze Nacht.", "Çocuk bütün gece öksürüyor.", "The child has been coughing all night.", [], []),
    ("bluten (blutet, blutete, hat geblutet)", "kanamak", "to bleed", "verb", "A2", "Die Wunde blutet noch etwas.", "Yara hala biraz kanıyor.", "The wound is still bleeding a bit.", [], []),
    ("untersuchen (untersucht, untersuchte, hat untersucht)", "muayene etmek, araştırmak", "to examine / investigate", "verb", "A2", "Der Arzt untersucht den Patienten gründlich.", "Doktor hastayı etraflıca muayene ediyor.", "The doctor examines the patient thoroughly.", ["begutachten"], []),
    ("fehlen (fehlt, fehlte, hat gefehlt)", "eksik olmak, yok olmak", "to be missing / lack", "verb", "A1", "Was fehlt Ihnen denn?", "Neyiniz var? (Doktorda)", "What is ailing you?", ["mangeln"], []),
    ("erholen (erholt, erholte, hat erholt)", "dinlenmek, iyileşmek", "to recover / rest", "verb", "A2", "Im Urlaub konnte ich mich gut erholen.", "Tatilde güzelce dinlenebildim.", "On vacation I was able to recover well.", ["ausruhen", "genesen"], ["ermüden"]),
    ("ausruhen (ruht aus, ruhte aus, hat ausgeruht)", "dinlenmek", "to rest", "verb", "A2", "Ruh dich ein wenig aus!", "Biraz dinlen!", "Rest a little!", ["erholen"], ["anstrengen"]),
    ("weinen (weint, weinte, hat geweint)", "ağlamak", "to cry / weep", "verb", "A2", "Warum weinst du, mein Kind?", "Neden ağlıyorsun çocuğum?", "Why are you crying, my child?", ["schluchzen"], ["lachen"]),
    ("lachen (lacht, lachte, hat gelacht)", "gülmek", "to laugh", "verb", "A1", "Wir haben herzlich gelacht.", "Gönülden güldük.", "We laughed heartily.", ["schmunzeln"], ["weinen"]),
    ("lächeln (lächelt, lächelte, hat gelächelt)", "gülümsemek", "to smile", "verb", "A2", "Sie lächelt freundlich.", "O samimiyetle gülümsüyor.", "She smiles kindly.", ["grinsen"], ["stirnrunzeln"]),
    ("freuen (freut, freute, hat gefreut)", "sevinmek", "to be glad / look forward", "verb", "A1", "Ich freue mich auf das Wochenende!", "Hafta sonunu sabırsızlıkla bekliyorum!", "I am looking forward to the weekend!", ["jubeln"], ["ärgern", "trauern"]),
    ("ärgern (ärgert, ärgerte, hat geärgert)", "kızmak, sinirlenmek", "to annoy / get angry", "verb", "A2", "Ärgere dich nicht über das Wetter!", "Hava durumuna kızma!", "Don't get annoyed about the weather!", ["aufregen"], ["freuen"]),
    ("fürchten (fürchtet, fürchtete, hat gefürchtet)", "korkmak", "to fear", "verb", "A2", "Er fürchtet sich vor Hunden.", "O köpeklerden korkar.", "He is afraid of dogs.", ["Angst haben"], ["mutig sein"]),
    ("hoffen (hofft, hoffte, hat gehofft)", "umut etmek", "to hope", "verb", "A2", "Ich hoffe, dass alles gut klappt.", "Her şeyin yolunda gitmesini umuyorum.", "I hope that everything works out well.", ["erwarten"], ["verzweifeln"]),

    # Common Physical Actions & Senses
    ("öffnen (öffnet, öffnete, hat geöffnet)", "açmak", "to open", "verb", "A1", "Öffnen Sie bitte die Tür.", "Lütfen kapıyı açın.", "Please open the door.", ["aufmachen"], ["schließen", "zumachen"]),
    ("schließen (schließt, schloss, hat geschlossen)", "kapatmak", "to close", "verb", "A1", "Er schließt das Geschäft um 18 Uhr.", "Mağazayı saat 18'de kapatıyor.", "He closes the shop at 6 pm.", ["zumachen"], ["öffnen", "aufmachen"]),
    ("anmachen (macht an, machte an, hat angemacht)", "açmak (ışık, cihaz)", "to switch on / turn on", "verb", "A1", "Mach bitte das Licht an.", "Lütfen ışığı aç.", "Please turn on the light.", ["einschalten"], ["ausmachen", "ausschalten"]),
    ("ausmachen (macht aus, machte aus, hat ausgemacht)", "kapatmak (ışık, cihaz)", "to switch off / turn off", "verb", "A1", "Vergiss nicht, den Herd auszumachen.", "Ocağı kapatmayı unutma.", "Don't forget to turn off the stove.", ["ausschalten"], ["anmachen", "einschalten"]),
    ("einschalten (schaltet ein, schaltete ein, hat eingeschaltet)", "çalıştırmak, açmak", "to turn on / switch on", "verb", "A2", "Schalte das Radio ein!", "Radyoyu aç!", "Turn on the radio!", ["anmachen"], ["ausschalten"]),
    ("ausschalten (schaltet aus, schaltete aus, hat ausgeschaltet)", "kapatmak (cihaz)", "to turn off / switch off", "verb", "A2", "Bitte schalten Sie Handys aus.", "Lütfen cep telefonlarını kapatınız.", "Please turn off cell phones.", ["ausmachen"], ["einschalten"]),
    ("drücken (drückt, drückte, hat gedrückt)", "basmak, itmek", "to press / push", "verb", "A2", "Drücken Sie die grüne Taste.", "Yeşil düğmeye basınız.", "Press the green button.", ["pressen"], ["ziehen"]),
    ("ziehen (zieht, zog, hat gezogen)", "çekmek, taşınmak", "to pull / move", "verb", "A1", "An der Tür steht: 'Ziehen'.", "Kapıda 'Çekiniz' yazıyor.", "On the door it says: 'Pull'.", ["zerren"], ["drücken", "schieben"]),
    ("schieben (schiebt, schob, hat geschoben)", "itmek, ertelemek", "to push / shove", "verb", "A2", "Er schiebt das Fahrrad den Berg hinauf.", "Bisikleti tepeye doğru itiyor.", "He pushes the bicycle up the hill.", ["drücken"], ["ziehen"]),
    ("werfen (wirft, warf, hat geworfen)", "atmak, fırlatmak", "to throw", "verb", "A2", "Er wirft den Ball weit weg.", "Topu uzağa atıyor.", "He throws the ball far away.", ["schleudern"], ["fangen"]),
    ("fangen (fängt, fing, hat gefangen)", "yakalamak", "to catch", "verb", "A2", "Der Hund fängt den Ball.", "Köpek topu yakalıyor.", "The dog catches the ball.", ["greifen"], ["werfen", "verfehlen"]),
    ("fallen (fällt, fiel, ist gefallen)", "düşmek", "to fall", "verb", "A1", "Das Glas fiel auf den Boden.", "Bardak yere düştü.", "The glass fell to the floor.", ["stürzen"], ["aufstehen"]),
    ("aufheben (hebt auf, hob auf, hat aufgehoben)", "yerden kaldırmak, saklamak", "to pick up / keep", "verb", "A2", "Heb den Müll bitte auf!", "Lütfen çöpü yerden kaldır!", "Please pick up the trash!", ["aufsammeln"], ["fallenlassen"]),
    ("tragen (trägt, trug, hat getragen)", "taşımak, giymek", "to carry / wear", "verb", "A1", "Sie trägt einen warmen Mantel.", "Sıcak bir palto giyiyor.", "She is wearing a warm coat.", ["anhaben"], []),
    ("anziehen (zieht an, zog an, hat angezogen)", "giyinmek, giymek", "to put on / dress", "verb", "A1", "Zieh deine Jacke an, es ist kalt.", "Ceketini giy, hava soğuk.", "Put on your jacket, it is cold.", ["bekleiden"], ["ausziehen"]),
    ("ausziehen (zieht aus, zog aus, hat ausgezogen)", "çıkarmak (kıyafet), taşınmak", "to take off / move out", "verb", "A1", "Zieh die Schuhe bitte aus.", "Lütfen ayakkabılarını çıkar.", "Please take off your shoes.", ["ablegen"], ["anziehen"]),
    ("umziehen (zieht um, zog um, ist umgezogen)", "taşınmak, üstünü değiştirmek", "to move house / change clothes", "verb", "A1", "Wir ziehen nächsten Monat um.", "Gelecek ay yeni eve taşınıyoruz.", "We are moving house next month.", ["übersiedeln"], []),
    ("passen (passt, passte, hat gepasst)", "uymak, yakışmak", "to fit / suit", "verb", "A1", "Die Hose passt mir perfekt.", "Pantolon bana tam uyuyor.", "The trousers fit me perfectly.", ["sitzen"], []),
    ("gefallen (gefällt, gefiel, hat gefallen)", "hoşa gitmek, beğenilmek", "to please / like", "verb", "A1", "Wie gefällt dir mein neues Auto?", "Yeni arabamı nasıl buldun?", "How do you like my new car?", ["zusagen"], ["missfallen"]),
]

print(f"Loaded {len(VERBS_A1_A2)} verbs from verbs_a1_a2.py")
